{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.12.aar",
          "url": "core-0.80.12.aar",
          "size": 671245,
          "sha512": "09cf98781e9fdc44adcac1518fb69d9fa2632f5f309a2c2da9ab45c5ae4ec41d3efef734ab0e4dd7b9c9c6776b1bd39d8f877827d783c4dc7fc74d3210c674c9",
          "sha256": "06bd4524c982a7d0cface97e38ae0c310a5bbf8fbe3b62caadd57413ea3e318a",
          "sha1": "54875714def50515657b285f101800bd7301d543",
          "md5": "f33016270960bb291d9fadb16b40f1e5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.12.aar",
          "url": "core-0.80.12.aar",
          "size": 671245,
          "sha512": "09cf98781e9fdc44adcac1518fb69d9fa2632f5f309a2c2da9ab45c5ae4ec41d3efef734ab0e4dd7b9c9c6776b1bd39d8f877827d783c4dc7fc74d3210c674c9",
          "sha256": "06bd4524c982a7d0cface97e38ae0c310a5bbf8fbe3b62caadd57413ea3e318a",
          "sha1": "54875714def50515657b285f101800bd7301d543",
          "md5": "f33016270960bb291d9fadb16b40f1e5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.12-sources.jar",
          "url": "core-0.80.12-sources.jar",
          "size": 352511,
          "sha512": "71194504d5865caaa5c254011f8acd8030f9d670a4e9998eb70cd6860f03e871caab48a3d5c3bc2ebd1a6160782c3effe7bc556f95cd9e64c3c2d3beca9e5ef3",
          "sha256": "cd22ba02c5f1b20764af8f10f8d8edf3fd122740e10e265f8e3459adbdf8c0d5",
          "sha1": "df33659579202e1bd022b2683d044f498d66c833",
          "md5": "07ecf65c19aea94b58bc683fd8020d6d"
        }
      ]
    }
  ]
}
