{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.33.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tean77tudrg43fh3xguyqzorom"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.10.aar",
          "url": "firebase-detector-0.33.10.aar",
          "size": 40758,
          "sha512": "655dce75bb876ecdfd0dca46066ef5b3cc2c6b430e45dc84b5f6b43b42440c02d8396ed016495f2b6768245583d454a24374dd98e5498d4088acaa6610657776",
          "sha256": "bd78f473d45dd69c443538923389a17cd92bf4ac87ad069d766acfa1ea83041a",
          "sha1": "362c2fc1f75392b8a3e6d698b2254cab0fb31984",
          "md5": "e85dabf17caef9124dfa898e727e5022"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.10.aar",
          "url": "firebase-detector-0.33.10.aar",
          "size": 40758,
          "sha512": "655dce75bb876ecdfd0dca46066ef5b3cc2c6b430e45dc84b5f6b43b42440c02d8396ed016495f2b6768245583d454a24374dd98e5498d4088acaa6610657776",
          "sha256": "bd78f473d45dd69c443538923389a17cd92bf4ac87ad069d766acfa1ea83041a",
          "sha1": "362c2fc1f75392b8a3e6d698b2254cab0fb31984",
          "md5": "e85dabf17caef9124dfa898e727e5022"
        }
      ]
    }
  ]
}
