{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "23iz6pfvg5e5nctetag3umih5a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.11.aar",
          "url": "core-0.39.11.aar",
          "size": 368792,
          "sha512": "3e4439df6c8b586d4b1df6a4ceceba9b2d5589f794abc299e80a5cde840ef590602498f3cba8ab1d93d0b787687d2f873f8adf728bdb28271c6850537a90afe3",
          "sha256": "003b6bc1bcb9ec588eb8adbea85f4f09f05e937f61b505ca9f47766df9c52939",
          "sha1": "7d9c64e5e147b8c744aa3a7f75e8a0d6697c2aa7",
          "md5": "0473a4e4a819fba05a28fd3e951df4e4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.11"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.11.aar",
          "url": "core-0.39.11.aar",
          "size": 368792,
          "sha512": "3e4439df6c8b586d4b1df6a4ceceba9b2d5589f794abc299e80a5cde840ef590602498f3cba8ab1d93d0b787687d2f873f8adf728bdb28271c6850537a90afe3",
          "sha256": "003b6bc1bcb9ec588eb8adbea85f4f09f05e937f61b505ca9f47766df9c52939",
          "sha1": "7d9c64e5e147b8c744aa3a7f75e8a0d6697c2aa7",
          "md5": "0473a4e4a819fba05a28fd3e951df4e4"
        }
      ]
    }
  ]
}
