{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cekbw7vkgnerndfmmva5dxnj2m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.1.aar",
          "url": "ui-integration-0.35.1.aar",
          "size": 93098,
          "sha512": "92130fe0e9e5829c3f47f0ebdd3449797a7d6a911b12eb330bf03da71eff15a24da502ef3244d3183d28d8ab83721ed11446299db3d205318d3dcbdb990e3ff1",
          "sha256": "2e3d477beb927e0edb9eca1a94bee1c897af24bb8674a812656a2fd626450603",
          "sha1": "a09af5bdb1372005dd012ee9511077ee63a5b8f1",
          "md5": "47422a0ae5eb5ced206a787ee3565d84"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.1.aar",
          "url": "ui-integration-0.35.1.aar",
          "size": 93098,
          "sha512": "92130fe0e9e5829c3f47f0ebdd3449797a7d6a911b12eb330bf03da71eff15a24da502ef3244d3183d28d8ab83721ed11446299db3d205318d3dcbdb990e3ff1",
          "sha256": "2e3d477beb927e0edb9eca1a94bee1c897af24bb8674a812656a2fd626450603",
          "sha1": "a09af5bdb1372005dd012ee9511077ee63a5b8f1",
          "md5": "47422a0ae5eb5ced206a787ee3565d84"
        }
      ]
    }
  ]
}
