{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.34.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7wqcqhpzwnarvmbkfgqkjvi3ay"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.3.aar",
          "url": "ui-integration-0.34.3.aar",
          "size": 92927,
          "sha512": "5449a64a52190180bf38887a484881d10cf82c7f832b96f70e34301feb4874ea4c950aab0db35eb335f6fdfb76d5aaf41079e5f16d65e838588a7aa399145600",
          "sha256": "7ec49ae67048a9e458a2362b430cd626b7183f0e4c1ecf0ef16fc45422c810d5",
          "sha1": "f6f629d7296def4d992ac7e22fe8541e2e853b3b",
          "md5": "e8dd660d3f1abe0513bb49abdba3b437"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.34.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.34.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.3.aar",
          "url": "ui-integration-0.34.3.aar",
          "size": 92927,
          "sha512": "5449a64a52190180bf38887a484881d10cf82c7f832b96f70e34301feb4874ea4c950aab0db35eb335f6fdfb76d5aaf41079e5f16d65e838588a7aa399145600",
          "sha256": "7ec49ae67048a9e458a2362b430cd626b7183f0e4c1ecf0ef16fc45422c810d5",
          "sha1": "f6f629d7296def4d992ac7e22fe8541e2e853b3b",
          "md5": "e8dd660d3f1abe0513bb49abdba3b437"
        }
      ]
    }
  ]
}
