{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.datatrans",
    "module": "android-sdk",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ul7no6ditvdr5dputwfdpol2gi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-sdk-1.3.0.aar",
          "url": "android-sdk-1.3.0.aar",
          "size": 1586881,
          "sha512": "cdd8f5e9501d4112b672fd7239ad5e76aab924dbc7f140821bfae2dea98953e32fe5a51f68a34ca67eb2ab1f609635e973cfdc39a0fd4f6d0d0df07af6b1e24e",
          "sha256": "7f964ac4de0e93226a806a5d4be7e72177751f631b3d85641e76344b50027d40",
          "sha1": "fa0e9af529bbd3f56ca95a724e4cfcfa69639603",
          "md5": "ed1175e5825048c48fb17073f52c8da2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.twint.payment",
          "module": "twint-sdk-android",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "com.paypal.android",
          "module": "risk-component",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-rc02"
          }
        },
        {
          "group": "com.samsung.android.sdk",
          "module": "samsungpay",
          "version": {
            "requires": "2.8.00"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.card",
          "module": "android-sdk",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.3.0.aar",
          "url": "android-sdk-1.3.0.aar",
          "size": 1586881,
          "sha512": "cdd8f5e9501d4112b672fd7239ad5e76aab924dbc7f140821bfae2dea98953e32fe5a51f68a34ca67eb2ab1f609635e973cfdc39a0fd4f6d0d0df07af6b1e24e",
          "sha256": "7f964ac4de0e93226a806a5d4be7e72177751f631b3d85641e76344b50027d40",
          "sha1": "fa0e9af529bbd3f56ca95a724e4cfcfa69639603",
          "md5": "ed1175e5825048c48fb17073f52c8da2"
        }
      ]
    }
  ]
}
