{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.45.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.45.0.aar",
          "url": "firebase-detector-0.45.0.aar",
          "size": 44929,
          "sha512": "a32606ebc82da99ef09953b8f080ca9c85e1179fd97d4093ec223b3463b45b4c11e03fd1beb110dfee902cbe59d940b29818b0e6f35b04470e9fc5ef1ddb8e5a",
          "sha256": "f5f488433976f1b96e43f7b4e4b8d6418bb35f4e28bd4a2c9f63dc3093903f41",
          "sha1": "acae0ce44a551ef1409be9663bbc92efe261343c",
          "md5": "3f0b54f3473d88c6b1333007ebcccf7b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.45.0.aar",
          "url": "firebase-detector-0.45.0.aar",
          "size": 44929,
          "sha512": "a32606ebc82da99ef09953b8f080ca9c85e1179fd97d4093ec223b3463b45b4c11e03fd1beb110dfee902cbe59d940b29818b0e6f35b04470e9fc5ef1ddb8e5a",
          "sha256": "f5f488433976f1b96e43f7b4e4b8d6418bb35f4e28bd4a2c9f63dc3093903f41",
          "sha1": "acae0ce44a551ef1409be9663bbc92efe261343c",
          "md5": "3f0b54f3473d88c6b1333007ebcccf7b"
        }
      ]
    }
  ]
}
