{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.36.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "teeguhjzmvb4tocshtwrxjjqca"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.36.0.aar",
          "url": "core-0.36.0.aar",
          "size": 348980,
          "sha512": "ec86a96b42726926f69f542fac9cf74f901a9a6d070ff9bd95fb563f8d93c5a257fdf8c9dc4c9dcc0a18c1cbd5b85ac1dbc34c73ecec1dc70ca29c629f7d7f07",
          "sha256": "69fb604f3f9c3799fd0978048f01a626dc8f50a798ce0d113117e4715fc68279",
          "sha1": "5105987790481d80e1f0060a2566c6c7caae8154",
          "md5": "47525ef09f05c5497e89991f05eef2ee"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.36.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.36.0.aar",
          "url": "core-0.36.0.aar",
          "size": 348980,
          "sha512": "ec86a96b42726926f69f542fac9cf74f901a9a6d070ff9bd95fb563f8d93c5a257fdf8c9dc4c9dcc0a18c1cbd5b85ac1dbc34c73ecec1dc70ca29c629f7d7f07",
          "sha256": "69fb604f3f9c3799fd0978048f01a626dc8f50a798ce0d113117e4715fc68279",
          "sha1": "5105987790481d80e1f0060a2566c6c7caae8154",
          "md5": "47525ef09f05c5497e89991f05eef2ee"
        }
      ]
    }
  ]
}
