{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wuvcdliz3fbhlanb7jrxeryiqy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.3.aar",
          "url": "ui-integration-0.29.3.aar",
          "size": 74890,
          "sha512": "cf203b184692ad5a2a3eac6f7f503144cecdc803b7df8ac630842f03615bf4872d21fa4ccb28655c3585895282b70b3f5fa6365c1111597360549d93e7b5091f",
          "sha256": "dad94716203f7e29be1271d250565350296efa1a532f46a36eeabf274b2f50b8",
          "sha1": "240ceda006dd55a0e7f85c3e7bbf407d81ebdbdc",
          "md5": "6c245fb663ebb2085c5c6f5fecefb1e8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.3.aar",
          "url": "ui-integration-0.29.3.aar",
          "size": 74890,
          "sha512": "cf203b184692ad5a2a3eac6f7f503144cecdc803b7df8ac630842f03615bf4872d21fa4ccb28655c3585895282b70b3f5fa6365c1111597360549d93e7b5091f",
          "sha256": "dad94716203f7e29be1271d250565350296efa1a532f46a36eeabf274b2f50b8",
          "sha1": "240ceda006dd55a0e7f85c3e7bbf407d81ebdbdc",
          "md5": "6c245fb663ebb2085c5c6f5fecefb1e8"
        }
      ]
    }
  ]
}
