{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.2.aar",
          "url": "core-0.75.2.aar",
          "size": 637320,
          "sha512": "cf32c56494fe149f5a23515daa7be2e94f26267c987ec6cff12ae60a81bc2589ba81d325a5015f7dd491402fedb43f2f6aab6672550f8de41a8891a3fe2f6630",
          "sha256": "5d15f9da1a1e52badf0072870177adcc29f237426e1877b2d5470dc44a1586ed",
          "sha1": "6d41297242ebcec731d631e934bf8f0afe0569b8",
          "md5": "b1e4ea40bec93c480648009509de449e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.2.aar",
          "url": "core-0.75.2.aar",
          "size": 637320,
          "sha512": "cf32c56494fe149f5a23515daa7be2e94f26267c987ec6cff12ae60a81bc2589ba81d325a5015f7dd491402fedb43f2f6aab6672550f8de41a8891a3fe2f6630",
          "sha256": "5d15f9da1a1e52badf0072870177adcc29f237426e1877b2d5470dc44a1586ed",
          "sha1": "6d41297242ebcec731d631e934bf8f0afe0569b8",
          "md5": "b1e4ea40bec93c480648009509de449e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.2-sources.jar",
          "url": "core-0.75.2-sources.jar",
          "size": 342779,
          "sha512": "3d672fcfd8cf28356d4643ffcc5dd5c2556b7a721887ee72c38c44d6b876bbd41d33ddd34dff63da47f965f3f26e9710f4caf544090e047be3a53d44aeffbaaa",
          "sha256": "21f4efc633a7b311b3d2f464ce8a6622f2d2a0b6ca43cbb246cf49d2f6cc104f",
          "sha1": "e2728628b95128c253b8f2ddd67da17bcf86c5af",
          "md5": "556806ffc4aa0e2971e65b5d4d36214a"
        }
      ]
    }
  ]
}
