{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sx5lzouqpvf7tj3mqx2kopdhwm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.0.aar",
          "url": "ui-integration-0.29.0.aar",
          "size": 74886,
          "sha512": "1dae6ca942f8d1a399986cc03598fd8420c2842288f4e456ab4e800cd166606b319575ae96a8fd4d851f1304991a597575f30de45f73b197ab8113f1d46c841a",
          "sha256": "c9eeafcaa645dbf3f3e7f78bdd1ba8468abfafebb327c19ffcd3d61a78266fdf",
          "sha1": "d2fbdd412438a1dcfaee35aef081354c032ddc69",
          "md5": "fc5a467ec147ddcc32c6120950699993"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.0.aar",
          "url": "ui-integration-0.29.0.aar",
          "size": 74886,
          "sha512": "1dae6ca942f8d1a399986cc03598fd8420c2842288f4e456ab4e800cd166606b319575ae96a8fd4d851f1304991a597575f30de45f73b197ab8113f1d46c841a",
          "sha256": "c9eeafcaa645dbf3f3e7f78bdd1ba8468abfafebb327c19ffcd3d61a78266fdf",
          "sha1": "d2fbdd412438a1dcfaee35aef081354c032ddc69",
          "md5": "fc5a467ec147ddcc32c6120950699993"
        }
      ]
    }
  ]
}
