{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.42.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.42.0.aar",
          "url": "utils-0.42.0.aar",
          "size": 43207,
          "sha512": "bfd96bd5a4725baa4856fc0d53c3874242e0d5792295653dd521714c4ea85a8db310744eb7c69462f4896039db2d6326d78e24dcde9764e94b34fe5b20369448",
          "sha256": "47327174215d1ee9b67e2c5db47c5b4f73a64ce5802781e2d02c869dda35d7f2",
          "sha1": "a04a005ede71e8c6dba2eff5d13c0b94eb90255c",
          "md5": "e28700af529816310b0539aff20f5bcc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.42.0.aar",
          "url": "utils-0.42.0.aar",
          "size": 43207,
          "sha512": "bfd96bd5a4725baa4856fc0d53c3874242e0d5792295653dd521714c4ea85a8db310744eb7c69462f4896039db2d6326d78e24dcde9764e94b34fe5b20369448",
          "sha256": "47327174215d1ee9b67e2c5db47c5b4f73a64ce5802781e2d02c869dda35d7f2",
          "sha1": "a04a005ede71e8c6dba2eff5d13c0b94eb90255c",
          "md5": "e28700af529816310b0539aff20f5bcc"
        }
      ]
    }
  ]
}
