{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.79.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.79.0.aar",
          "url": "core-0.79.0.aar",
          "size": 646709,
          "sha512": "fd233853ca104f1c4478d7f84605c9eccbeaed45460e99e347e6e90e3036349f92ca1e3968b6f2e86b310f9e547cb2e00e9dc82668b56f04bd874b83f59f3524",
          "sha256": "b9aceff16afafde943a7667d79085236c1e3cfad0ab7d511b76275adf87fb95f",
          "sha1": "55059a66c3759af6a5c712542d83a5823e8c19ed",
          "md5": "5b143da75cd8c9ae338be3b0ba5ad564"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.79.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.79.0.aar",
          "url": "core-0.79.0.aar",
          "size": 646709,
          "sha512": "fd233853ca104f1c4478d7f84605c9eccbeaed45460e99e347e6e90e3036349f92ca1e3968b6f2e86b310f9e547cb2e00e9dc82668b56f04bd874b83f59f3524",
          "sha256": "b9aceff16afafde943a7667d79085236c1e3cfad0ab7d511b76275adf87fb95f",
          "sha1": "55059a66c3759af6a5c712542d83a5823e8c19ed",
          "md5": "5b143da75cd8c9ae338be3b0ba5ad564"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.79.0-sources.jar",
          "url": "core-0.79.0-sources.jar",
          "size": 348303,
          "sha512": "1f7e85de478a4033b7e9969dc22185ad41979680303632d782a1e7a84923f02ffaac43dec62d15608ffb8dc42606c92a069047f7c23c5721cc2b4c0f7450dd0b",
          "sha256": "fbfd41cbb7c0733e10559c8cc72dfbf7dd50acb04663e8e754691fe256e7eaae",
          "sha1": "b90c61daf56b1250d8049e366e8e15c6a8a26010",
          "md5": "f39cc3d61d578f32c73a46699ad2c69c"
        }
      ]
    }
  ]
}
