{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tu7p3w3mcfajtebu4zeryl5uvi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-detector-0.26.2.aar",
          "url": "firebase-detector-0.26.2.aar",
          "size": 31217,
          "sha512": "f17051a3a7b5f9571b15c71588fa468903baa258bf275c9495ec2e3d722e3b96a02497db016042feed5b8ce039631908324f204cc69fbd4826facdb6e5226e8d",
          "sha256": "ac8ba388e0936556ead728180feab2b3f76244105ae7758165df2d67a9cdcaeb",
          "sha1": "004d759be83d2cc5b75942d26afc1d4f45888f5b",
          "md5": "412fa910fddb2c1b4172717e1dc56e7e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.26.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.26.2.aar",
          "url": "firebase-detector-0.26.2.aar",
          "size": 31217,
          "sha512": "f17051a3a7b5f9571b15c71588fa468903baa258bf275c9495ec2e3d722e3b96a02497db016042feed5b8ce039631908324f204cc69fbd4826facdb6e5226e8d",
          "sha256": "ac8ba388e0936556ead728180feab2b3f76244105ae7758165df2d67a9cdcaeb",
          "sha1": "004d759be83d2cc5b75942d26afc1d4f45888f5b",
          "md5": "412fa910fddb2c1b4172717e1dc56e7e"
        }
      ]
    }
  ]
}
