{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.0.0.aar",
          "url": "core-3.0.0.aar",
          "size": 144920,
          "sha512": "df001b8a3e14f28c7ff635276d9120511523cfc1c96ba814163c533eb520e574ef94fbb6f1472d5b260ee2b67f7ad68078e9d80edecebd110735c2d8fb017cac",
          "sha256": "d3ea77480c0699f88019dc2d175ef35431f863974bd345b248a3b24510e9c76f",
          "sha1": "3d4bcc48c86211764bdb129269b46c66b59dabd5",
          "md5": "87e343d98f02f474fd64b584b4f0632e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.0.0.aar",
          "url": "core-3.0.0.aar",
          "size": 144920,
          "sha512": "df001b8a3e14f28c7ff635276d9120511523cfc1c96ba814163c533eb520e574ef94fbb6f1472d5b260ee2b67f7ad68078e9d80edecebd110735c2d8fb017cac",
          "sha256": "d3ea77480c0699f88019dc2d175ef35431f863974bd345b248a3b24510e9c76f",
          "sha1": "3d4bcc48c86211764bdb129269b46c66b59dabd5",
          "md5": "87e343d98f02f474fd64b584b4f0632e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.0.0-sources.jar",
          "url": "core-3.0.0-sources.jar",
          "size": 26603,
          "sha512": "08842b77e8b537873b8203d64d329ac06139a7937493c49fe4bdc648c5db97a37831ef6ee40ace022e72932cd8159f7cea8734926cb67600ab112d5fc2c9df75",
          "sha256": "b2a111eeaf64dd5f90a4a58e3dffc9be10d778fe014eacf7284a299cf707292c",
          "sha1": "80906e15e07e922554e77bbd56af92df28370bfd",
          "md5": "2cc7fb1bd165caad226a4a85ebd1a3a1"
        }
      ]
    }
  ]
}
