{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smu23jnbtvdbvnisogafvrovii"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.5.aar",
          "url": "utils-0.32.5.aar",
          "size": 42927,
          "sha512": "def6eb01cadf82a22cccccc3682b8706e902003c944feeeb367a2f49b4ed29dd287c0de2400573680affa51dba9b21295571168c696fa4a0fd07b77995dc1cd0",
          "sha256": "e0cfd76ea831158b229277b4f8e6ecb0efd1da89ad3bfd0f889a564c481767fb",
          "sha1": "6cbf2e53538b7e2f2bb50ab9d952930ab55aa9aa",
          "md5": "b2eed3824d63066466e1b6f41ccff54c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.5.aar",
          "url": "utils-0.32.5.aar",
          "size": 42927,
          "sha512": "def6eb01cadf82a22cccccc3682b8706e902003c944feeeb367a2f49b4ed29dd287c0de2400573680affa51dba9b21295571168c696fa4a0fd07b77995dc1cd0",
          "sha256": "e0cfd76ea831158b229277b4f8e6ecb0efd1da89ad3bfd0f889a564c481767fb",
          "sha1": "6cbf2e53538b7e2f2bb50ab9d952930ab55aa9aa",
          "md5": "b2eed3824d63066466e1b6f41ccff54c"
        }
      ]
    }
  ]
}
