{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.27.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kpma7flhhrbh3fzlac4443wfzi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.27.2.aar",
          "url": "ui-0.27.2.aar",
          "size": 830716,
          "sha512": "79884b3437aaef1f643a9465ee7e2e4fa82385d1c7365863c017edc43a1187badad0b3cea8a5ff91737a2c14543bd208dc2a606dac46cc0f3351733d33d5b7f2",
          "sha256": "93d13f075cfb90379aefdf858438f35937950bc23dfee76e51e7461de9dea947",
          "sha1": "30c513b18b2dcb929ac98c29363bdb4bda6ea77f",
          "md5": "dcef72ef565f0776bbd5a1c6a87dcd6a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.27.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.27.2.aar",
          "url": "ui-0.27.2.aar",
          "size": 830716,
          "sha512": "79884b3437aaef1f643a9465ee7e2e4fa82385d1c7365863c017edc43a1187badad0b3cea8a5ff91737a2c14543bd208dc2a606dac46cc0f3351733d33d5b7f2",
          "sha256": "93d13f075cfb90379aefdf858438f35937950bc23dfee76e51e7461de9dea947",
          "sha1": "30c513b18b2dcb929ac98c29363bdb4bda6ea77f",
          "md5": "dcef72ef565f0776bbd5a1c6a87dcd6a"
        }
      ]
    }
  ]
}
