{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.25.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r3ppg4lgpfbpngvcbn4c6acnme"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-detector-0.25.3.aar",
          "url": "firebase-detector-0.25.3.aar",
          "size": 31200,
          "sha512": "c2f0f5f93365647d3c802ac1be5b15e8ab7e8f4216d86178606d1d9172e5ae9b0b434ed8f6948c4c8b85fbd52639a7e45990a94ed3d58baaadde05c57d4d6e79",
          "sha256": "aee4d9e4d468e456174d5fbd802697fa2e73bf59651b36e4905d684d1b78d59c",
          "sha1": "791581fc5f179200603a581189e7b9f4d8058742",
          "md5": "7331e0ece1b62e6a64e60916a63a02e2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.25.3.aar",
          "url": "firebase-detector-0.25.3.aar",
          "size": 31200,
          "sha512": "c2f0f5f93365647d3c802ac1be5b15e8ab7e8f4216d86178606d1d9172e5ae9b0b434ed8f6948c4c8b85fbd52639a7e45990a94ed3d58baaadde05c57d4d6e79",
          "sha256": "aee4d9e4d468e456174d5fbd802697fa2e73bf59651b36e4905d684d1b78d59c",
          "sha1": "791581fc5f179200603a581189e7b9f4d8058742",
          "md5": "7331e0ece1b62e6a64e60916a63a02e2"
        }
      ]
    }
  ]
}
