{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.35.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "p4oipcf3fjdwrpskpquedrcsbe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.8.aar",
          "url": "firebase-detector-0.35.8.aar",
          "size": 41025,
          "sha512": "7b09a99efd1a5615154e09dbd4613728fb50b5c02afdca1e76fef3b058dac1f21ec079700aa111151d471f8a4a363f46c6d50ba747021bcb02f2a4a0001156c6",
          "sha256": "387326f782f9d419b29431ab56f7cce036c9b3a78bfe6de6e70af091661ebd2d",
          "sha1": "5a90ba7aa180e46e4cbd832d43eb98c879f9941e",
          "md5": "213113bf38165bdfdd7cb7e52545942b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.8.aar",
          "url": "firebase-detector-0.35.8.aar",
          "size": 41025,
          "sha512": "7b09a99efd1a5615154e09dbd4613728fb50b5c02afdca1e76fef3b058dac1f21ec079700aa111151d471f8a4a363f46c6d50ba747021bcb02f2a4a0001156c6",
          "sha256": "387326f782f9d419b29431ab56f7cce036c9b3a78bfe6de6e70af091661ebd2d",
          "sha1": "5a90ba7aa180e46e4cbd832d43eb98c879f9941e",
          "md5": "213113bf38165bdfdd7cb7e52545942b"
        }
      ]
    }
  ]
}
