{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.datatrans",
    "module": "android-sdk",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ljy5cdy3rresxbjb4qofwue54u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-sdk-1.5.0.aar",
          "url": "android-sdk-1.5.0.aar",
          "size": 1841880,
          "sha512": "f6bdadabeb3c5a9336547341d4b43e6a223a33d5fb008fb37a7f67663b2c406433e6179e75ea6aab91085d9f266fc382a68e82df89df7ba162be8e13ee4c2eb4",
          "sha256": "006e4fa2e80cc8ce45abb6d4a81a356b499c04a33408d77a3e7a98c1f8d9ce32",
          "sha1": "9a5170a6227820a437323dd4d0c54f070b28998f",
          "md5": "cc9f2434ceac53bf74f2133a4a638f34"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.twint.payment",
          "module": "twint-sdk-android",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "com.paypal.android",
          "module": "risk-component",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-rc02"
          }
        },
        {
          "group": "com.samsung.android.sdk",
          "module": "samsungpay",
          "version": {
            "requires": "2.8.00"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.card",
          "module": "android-sdk",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.5.0.aar",
          "url": "android-sdk-1.5.0.aar",
          "size": 1841880,
          "sha512": "f6bdadabeb3c5a9336547341d4b43e6a223a33d5fb008fb37a7f67663b2c406433e6179e75ea6aab91085d9f266fc382a68e82df89df7ba162be8e13ee4c2eb4",
          "sha256": "006e4fa2e80cc8ce45abb6d4a81a356b499c04a33408d77a3e7a98c1f8d9ce32",
          "sha1": "9a5170a6227820a437323dd4d0c54f070b28998f",
          "md5": "cc9f2434ceac53bf74f2133a4a638f34"
        }
      ]
    }
  ]
}
