{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "network",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.0.jar",
          "url": "network-1.0.0.jar",
          "size": 25031,
          "sha512": "12795c04e255a53c409d0ec45e67e6fde6001d46291ddc76faeda5ad21c424a699f081cdb669b01b61c6938b83092ad8ee8face3fc604c53781ec3e7652dcf62",
          "sha256": "86c468d4d31830e8698cf53358c22e67335f8b8b3bd95f32da5b2066c4d58b58",
          "sha1": "5babbb521ff52f119b349d3241b4bc0a991962c7",
          "md5": "8ea38ce3b9d3cb7d24f94ddd9f56a76b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.0.jar",
          "url": "network-1.0.0.jar",
          "size": 25031,
          "sha512": "12795c04e255a53c409d0ec45e67e6fde6001d46291ddc76faeda5ad21c424a699f081cdb669b01b61c6938b83092ad8ee8face3fc604c53781ec3e7652dcf62",
          "sha256": "86c468d4d31830e8698cf53358c22e67335f8b8b3bd95f32da5b2066c4d58b58",
          "sha1": "5babbb521ff52f119b349d3241b4bc0a991962c7",
          "md5": "8ea38ce3b9d3cb7d24f94ddd9f56a76b"
        }
      ]
    }
  ]
}
