{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4ugdjqljuzcqbimdc5l2ngplkm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.9.aar",
          "url": "utils-0.32.9.aar",
          "size": 42927,
          "sha512": "277f03574022b468d4409838623310d1ad0ee96a975329300588d52b4dbc2dd7bf19e68474f1a7fc10d04915ec9a4f6958682ad060966498f826cb13bdba1b13",
          "sha256": "e2fbb39553bff0830e4d5ccdc57b7b04162cc533ee0ec291fdd97d0725675992",
          "sha1": "7085b8ee283bea6997637dcd9cb9c24ae80ca95c",
          "md5": "3fbbd7e9df110f605c7e4fe6e45400f7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.9.aar",
          "url": "utils-0.32.9.aar",
          "size": 42927,
          "sha512": "277f03574022b468d4409838623310d1ad0ee96a975329300588d52b4dbc2dd7bf19e68474f1a7fc10d04915ec9a4f6958682ad060966498f826cb13bdba1b13",
          "sha256": "e2fbb39553bff0830e4d5ccdc57b7b04162cc533ee0ec291fdd97d0725675992",
          "sha1": "7085b8ee283bea6997637dcd9cb9c24ae80ca95c",
          "md5": "3fbbd7e9df110f605c7e4fe6e45400f7"
        }
      ]
    }
  ]
}
