{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7xnk7aj5prhfvhghio4a2dcuqq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.5.aar",
          "url": "ui-integration-0.29.5.aar",
          "size": 74890,
          "sha512": "b2a7fc1827f70c0f32240352c1d89da49eab291b14e6270f6bbbacac74e54cfb18dd647dc135ea4281cb3b96b817f1f686b6564204165ef10323470526e966a6",
          "sha256": "aa90bd973b9d637bd67b6819bc0b004d469b8dee0a5cd0db081472afe82aeada",
          "sha1": "9145e8559bbac6d345dd829ff658284f25e620f3",
          "md5": "eedbe878fe2378cd62f7d4fdad726788"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.5.aar",
          "url": "ui-integration-0.29.5.aar",
          "size": 74890,
          "sha512": "b2a7fc1827f70c0f32240352c1d89da49eab291b14e6270f6bbbacac74e54cfb18dd647dc135ea4281cb3b96b817f1f686b6564204165ef10323470526e966a6",
          "sha256": "aa90bd973b9d637bd67b6819bc0b004d469b8dee0a5cd0db081472afe82aeada",
          "sha1": "9145e8559bbac6d345dd829ff658284f25e620f3",
          "md5": "eedbe878fe2378cd62f7d4fdad726788"
        }
      ]
    }
  ]
}
