{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.32.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smu23jnbtvdbvnisogafvrovii"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.5.aar",
          "url": "ui-integration-0.32.5.aar",
          "size": 75110,
          "sha512": "50fb0161d71d5f0404e4794c4074c5b4ed0766a2bcf2ab1ad8568721a1e992b4a12b778459c9f79861a24d7b67c5794f11c441534441f05c56c9e3bb58adfc61",
          "sha256": "cf1ca3c84f0558af13b1144e8ddf5ed061a32330524612927925d7334b4b1dc1",
          "sha1": "53b8dbc7a5efe5a1187c4d0537b8f711fcb281f2",
          "md5": "5c9860f40c46dd3a7034a8cc451560ba"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.32.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.32.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.5"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.5.aar",
          "url": "ui-integration-0.32.5.aar",
          "size": 75110,
          "sha512": "50fb0161d71d5f0404e4794c4074c5b4ed0766a2bcf2ab1ad8568721a1e992b4a12b778459c9f79861a24d7b67c5794f11c441534441f05c56c9e3bb58adfc61",
          "sha256": "cf1ca3c84f0558af13b1144e8ddf5ed061a32330524612927925d7334b4b1dc1",
          "sha1": "53b8dbc7a5efe5a1187c4d0537b8f711fcb281f2",
          "md5": "5c9860f40c46dd3a7034a8cc451560ba"
        }
      ]
    }
  ]
}
