{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.29.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pxwkauswsvh2la5rhzsezbbsem"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.6.aar",
          "url": "firebase-detector-0.29.6.aar",
          "size": 32730,
          "sha512": "48a5b8ccde9a44de6eeb82a9262b374eb4a79c68989f09eb5d26d07c7d616d9ae073ed6fbb6ff06a81d8da3af854da7abd8609f09418213569ef88dff60341d2",
          "sha256": "96518b1edf779037d408bfadb9067390d775eb75cf2f0c7286e82410f1676804",
          "sha1": "ba5f3b8df01e43e67f417e2de8087c32bf81ec46",
          "md5": "bd1e7aa9bdd07198d1c80259b36f7da9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.6"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.6.aar",
          "url": "firebase-detector-0.29.6.aar",
          "size": 32730,
          "sha512": "48a5b8ccde9a44de6eeb82a9262b374eb4a79c68989f09eb5d26d07c7d616d9ae073ed6fbb6ff06a81d8da3af854da7abd8609f09418213569ef88dff60341d2",
          "sha256": "96518b1edf779037d408bfadb9067390d775eb75cf2f0c7286e82410f1676804",
          "sha1": "ba5f3b8df01e43e67f417e2de8087c32bf81ec46",
          "md5": "bd1e7aa9bdd07198d1c80259b36f7da9"
        }
      ]
    }
  ]
}
