{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.26.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37u6vglxv5dqddffadzdsvbv4e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-detector-0.26.6.aar",
          "url": "firebase-detector-0.26.6.aar",
          "size": 31217,
          "sha512": "2d0c41e413779f3a211f621728428a463172937f85eb4f5f3db7a59fbff3b5744853067524a1d31b371e7cf5b40a09304333d0ca74f3b4ebebf6351f0b77022c",
          "sha256": "53bfa604938f483a0b02213a794504dd7219eafd2e947e8ed73fe1977c3be6bf",
          "sha1": "936c5951216cb66b8ebbf820dde2d4981b473478",
          "md5": "cf56fe4adc9f35b5b4e55b975f04e234"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.26.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.6"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.26.6.aar",
          "url": "firebase-detector-0.26.6.aar",
          "size": 31217,
          "sha512": "2d0c41e413779f3a211f621728428a463172937f85eb4f5f3db7a59fbff3b5744853067524a1d31b371e7cf5b40a09304333d0ca74f3b4ebebf6351f0b77022c",
          "sha256": "53bfa604938f483a0b02213a794504dd7219eafd2e947e8ed73fe1977c3be6bf",
          "sha1": "936c5951216cb66b8ebbf820dde2d4981b473478",
          "md5": "cf56fe4adc9f35b5b4e55b975f04e234"
        }
      ]
    }
  ]
}
