{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.35.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cxwollak2bhpdinsvzain3fecu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.6.aar",
          "url": "firebase-detector-0.35.6.aar",
          "size": 41009,
          "sha512": "719869117158dd197d50e1bdb0d172dbc4c517fa7649981fc5691a8c2da44c229c83eb9f4603bc07993310cffc9484f3b6b16e6990a7279a3585bb10f7fa707f",
          "sha256": "9f9a761c89ddc5323a882fb8cca251e2945a434b599d7e087da2ed04660dfae9",
          "sha1": "81b56e9c3332df26ee7e5c099f26a04f023ec99a",
          "md5": "42af9e2a23dcf5a3391310682cbd5a0a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.6"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.6.aar",
          "url": "firebase-detector-0.35.6.aar",
          "size": 41009,
          "sha512": "719869117158dd197d50e1bdb0d172dbc4c517fa7649981fc5691a8c2da44c229c83eb9f4603bc07993310cffc9484f3b6b16e6990a7279a3585bb10f7fa707f",
          "sha256": "9f9a761c89ddc5323a882fb8cca251e2945a434b599d7e087da2ed04660dfae9",
          "sha1": "81b56e9c3332df26ee7e5c099f26a04f023ec99a",
          "md5": "42af9e2a23dcf5a3391310682cbd5a0a"
        }
      ]
    }
  ]
}
