{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i5laplrhrfahll6lxbe7a4qkqm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.0.aar",
          "url": "core-0.32.0.aar",
          "size": 325900,
          "sha512": "0a7522de5c3086b7977a038df51f91c17edbb0cc00aec392057c2d00aa6094d3d7321b81cfcb9f1457e9667080a4a19dfac558fab9385341d728f2b26a1ebc27",
          "sha256": "662715c369ce679352209f99e6be7fe1d3805ab5f4a0e35aca52a172ebdef83b",
          "sha1": "5830b7dda5c6ed2eb6292805c8423b580de4ef2c",
          "md5": "9ae207a52c0052c18b8edc5fc5acfe42"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.0.aar",
          "url": "core-0.32.0.aar",
          "size": 325900,
          "sha512": "0a7522de5c3086b7977a038df51f91c17edbb0cc00aec392057c2d00aa6094d3d7321b81cfcb9f1457e9667080a4a19dfac558fab9385341d728f2b26a1ebc27",
          "sha256": "662715c369ce679352209f99e6be7fe1d3805ab5f4a0e35aca52a172ebdef83b",
          "sha1": "5830b7dda5c6ed2eb6292805c8423b580de4ef2c",
          "md5": "9ae207a52c0052c18b8edc5fc5acfe42"
        }
      ]
    }
  ]
}
