{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.34.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5gw7267myzcbvkhbrhqmed3q3a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.2.aar",
          "url": "core-0.34.2.aar",
          "size": 330130,
          "sha512": "87d14b90c1375dd31825d618207170ecbbd59e42330233a7bafe10e101c6658acccfa7ef868be11c2a87d7601f5e906dd943be8a22e69905633153632046d54e",
          "sha256": "c5349463db67d07aa45a1abb673a5050d78d0190ea1cc4f7a8c4c64c0090d1bf",
          "sha1": "0c1fd4fca2ca2bac093c45bb8f6be19041c73745",
          "md5": "d221f6f71e4bc2f2c9048304e977717b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.2.aar",
          "url": "core-0.34.2.aar",
          "size": 330130,
          "sha512": "87d14b90c1375dd31825d618207170ecbbd59e42330233a7bafe10e101c6658acccfa7ef868be11c2a87d7601f5e906dd943be8a22e69905633153632046d54e",
          "sha256": "c5349463db67d07aa45a1abb673a5050d78d0190ea1cc4f7a8c4c64c0090d1bf",
          "sha1": "0c1fd4fca2ca2bac093c45bb8f6be19041c73745",
          "md5": "d221f6f71e4bc2f2c9048304e977717b"
        }
      ]
    }
  ]
}
