{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.69.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.8.aar",
          "url": "utils-0.69.8.aar",
          "size": 55424,
          "sha512": "55b43a13edbd7d11a256b003836f9f83d365ea5bca790bafbe588bd2387283d9f801c79bf92353198265cd493b76d778528e2b3619154848ec86c704ce9d63e6",
          "sha256": "ae9ca52296d6cd2186c47b0fad1e1c4e7ecfc2eccd6cb55c40973dd249db8e2d",
          "sha1": "a4f6c97b1691cddf46e7e6a93d4524c021cda79d",
          "md5": "7bd0ad9c11d6a716c86b4aaf2dd25497"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.8.aar",
          "url": "utils-0.69.8.aar",
          "size": 55424,
          "sha512": "55b43a13edbd7d11a256b003836f9f83d365ea5bca790bafbe588bd2387283d9f801c79bf92353198265cd493b76d778528e2b3619154848ec86c704ce9d63e6",
          "sha256": "ae9ca52296d6cd2186c47b0fad1e1c4e7ecfc2eccd6cb55c40973dd249db8e2d",
          "sha1": "a4f6c97b1691cddf46e7e6a93d4524c021cda79d",
          "md5": "7bd0ad9c11d6a716c86b4aaf2dd25497"
        }
      ]
    }
  ]
}
