{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7xnk7aj5prhfvhghio4a2dcuqq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.5.aar",
          "url": "core-0.29.5.aar",
          "size": 287572,
          "sha512": "dec4887cb7e8b2721f2e8a14f5d48968804843a1af8ca798fe6b8c50f2838c174b9f3875436df8e6ce6df39397ba5af73b2401f42b21ace809197a1a164bdfc1",
          "sha256": "827a4561586dabb3eb3fb4776d2075278e8bd389809249059c4070124a366d62",
          "sha1": "e06a1894add8c6d28ffa5d03284dd9f247bc1bf8",
          "md5": "18c6cdbe38a556ad8c8f80c5c02d7424"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.5.aar",
          "url": "core-0.29.5.aar",
          "size": 287572,
          "sha512": "dec4887cb7e8b2721f2e8a14f5d48968804843a1af8ca798fe6b8c50f2838c174b9f3875436df8e6ce6df39397ba5af73b2401f42b21ace809197a1a164bdfc1",
          "sha256": "827a4561586dabb3eb3fb4776d2075278e8bd389809249059c4070124a366d62",
          "sha1": "e06a1894add8c6d28ffa5d03284dd9f247bc1bf8",
          "md5": "18c6cdbe38a556ad8c8f80c5c02d7424"
        }
      ]
    }
  ]
}
