{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4hiutxtlnjboni5ho6s4oitmpm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.1.aar",
          "url": "ui-integration-0.29.1.aar",
          "size": 74889,
          "sha512": "d001689773a2b89dcfbe2ada3ae252146ba0c3d610775aabe5f71ade2e1c51af0f47bd5fe496e4382eed699fc96c9cb8f1f66113906f865864fbca06c2001294",
          "sha256": "aa63587277f04d94b97f4ee9206abe32cbfd3f233de2a9082724d4a9e8d7f50a",
          "sha1": "df8ef21962b8123b1a0eb39668d31eabff26846f",
          "md5": "0775d7779735485ba37d7d68f7f35066"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.1.aar",
          "url": "ui-integration-0.29.1.aar",
          "size": 74889,
          "sha512": "d001689773a2b89dcfbe2ada3ae252146ba0c3d610775aabe5f71ade2e1c51af0f47bd5fe496e4382eed699fc96c9cb8f1f66113906f865864fbca06c2001294",
          "sha256": "aa63587277f04d94b97f4ee9206abe32cbfd3f233de2a9082724d4a9e8d7f50a",
          "sha1": "df8ef21962b8123b1a0eb39668d31eabff26846f",
          "md5": "0775d7779735485ba37d7d68f7f35066"
        }
      ]
    }
  ]
}
