{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7basjsi6wfdgnn3afl4tnvdeue"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.4.aar",
          "url": "core-0.39.4.aar",
          "size": 367795,
          "sha512": "dde60a0b246d489777855fb449b14297e27c0decfa8673e7912860f747d32a1a3bb6439ac6ffd5b130d2918140e8787850b68a2637aad3a0f3050602959c28b9",
          "sha256": "f639f375d63f64d3f3dd31bbd37970b80396b7fb3dc93cf47ca0ca7713794477",
          "sha1": "07265caa7480fcb534ef97e77e8ea77297193d39",
          "md5": "70c77f6f905125c038a9046eac09aa35"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.4.aar",
          "url": "core-0.39.4.aar",
          "size": 367795,
          "sha512": "dde60a0b246d489777855fb449b14297e27c0decfa8673e7912860f747d32a1a3bb6439ac6ffd5b130d2918140e8787850b68a2637aad3a0f3050602959c28b9",
          "sha256": "f639f375d63f64d3f3dd31bbd37970b80396b7fb3dc93cf47ca0ca7713794477",
          "sha1": "07265caa7480fcb534ef97e77e8ea77297193d39",
          "md5": "70c77f6f905125c038a9046eac09aa35"
        }
      ]
    }
  ]
}
