{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.74.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.74.1.aar",
          "url": "core-0.74.1.aar",
          "size": 637215,
          "sha512": "9406f85919853c52cd618b6bec480a7a27a975681651714b58f1a131380e55f27932c4b6a282e6af2b18cbfbcdfb4af354afb93f70d5ad3378da43fd7624e6c5",
          "sha256": "71f18d138d3654b66686a5b6d0fdc2146a2d1105ea90452ce56ffbba292bf491",
          "sha1": "0a45045ee2337f755699407d6a499db052d03cd2",
          "md5": "4b9e7304a7c3a586b6edbc3eb1e46e47"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.74.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.74.1.aar",
          "url": "core-0.74.1.aar",
          "size": 637215,
          "sha512": "9406f85919853c52cd618b6bec480a7a27a975681651714b58f1a131380e55f27932c4b6a282e6af2b18cbfbcdfb4af354afb93f70d5ad3378da43fd7624e6c5",
          "sha256": "71f18d138d3654b66686a5b6d0fdc2146a2d1105ea90452ce56ffbba292bf491",
          "sha1": "0a45045ee2337f755699407d6a499db052d03cd2",
          "md5": "4b9e7304a7c3a586b6edbc3eb1e46e47"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.74.1-sources.jar",
          "url": "core-0.74.1-sources.jar",
          "size": 342711,
          "sha512": "760c80a42546c1bca045726f34e7b73ad06c391ce9ed0b3345c2844055a098a892b014c15d717c436c1822f057cada88eab5853113c869f2b5a17d261f5d3b5d",
          "sha256": "f7cb5a82a7b6cb4a1a2c8819673a2d649c133d42d0d6c109ffbf0f9ee60b27a3",
          "sha1": "c4ca3d0e154f6c53f738e893a59cdcdc405b500c",
          "md5": "b89da0a7c10d4f2f447206d50ec8acaf"
        }
      ]
    }
  ]
}
