{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.76.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.76.0.aar",
          "url": "core-0.76.0.aar",
          "size": 640173,
          "sha512": "8709c452f923274814bc080950ad66f35e46ee9c3248413681d7f04993c23feff35e9f5bd801925e7242153a6fe6b5e4c28cc3b2cbbdbe87ba6d5ea71daee9eb",
          "sha256": "4e4ca16847105f37802bebca46b61a9ca519bce0326cfff7d37096d9efaf8d29",
          "sha1": "3d7e0421978f6e5ea62a25188b6e6acb24d2010a",
          "md5": "808106fb99a82fb4687d205b66ea5368"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.76.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.76.0.aar",
          "url": "core-0.76.0.aar",
          "size": 640173,
          "sha512": "8709c452f923274814bc080950ad66f35e46ee9c3248413681d7f04993c23feff35e9f5bd801925e7242153a6fe6b5e4c28cc3b2cbbdbe87ba6d5ea71daee9eb",
          "sha256": "4e4ca16847105f37802bebca46b61a9ca519bce0326cfff7d37096d9efaf8d29",
          "sha1": "3d7e0421978f6e5ea62a25188b6e6acb24d2010a",
          "md5": "808106fb99a82fb4687d205b66ea5368"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.76.0-sources.jar",
          "url": "core-0.76.0-sources.jar",
          "size": 345679,
          "sha512": "55ad4cea125860c081e88c56a6e648ba2554784cba7bd09857715443d8e63e29d5a2083c796eaeaf53d69631b8486d35ac353729f6be63c0a2329c4c564ca5e8",
          "sha256": "cd242447d7d28fb62b481a8eafd7ff2eb209a7d391ec7bd2194b991cb77b1df9",
          "sha1": "6e827ff303a19bca57333168c05b66dfb11bc24a",
          "md5": "f9e0243a8e80d3f9eb4fdc1a9fcd18aa"
        }
      ]
    }
  ]
}
