{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.32.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4fidkbhpcfc5ncwzvfc7lt4zwy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.2.aar",
          "url": "ui-integration-0.32.2.aar",
          "size": 75110,
          "sha512": "1f906e1b9cca56596793c838e4044114d7cd5ff06efe54ae48f1d82caf5d4055e5a8172f4e57ad9d99716cd872648eef37919bf3fce962a68da683fd7937f3a9",
          "sha256": "d6a7c0ec2e9f2c26ed6a0dc71a2c06b90c77352aea2958a88a63d5bfa79589ea",
          "sha1": "54f632c953d57828a8d7dcdfbaed533a999deda1",
          "md5": "be4a34bc17c93eba6d7547e53a24c974"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.32.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.32.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.2.aar",
          "url": "ui-integration-0.32.2.aar",
          "size": 75110,
          "sha512": "1f906e1b9cca56596793c838e4044114d7cd5ff06efe54ae48f1d82caf5d4055e5a8172f4e57ad9d99716cd872648eef37919bf3fce962a68da683fd7937f3a9",
          "sha256": "d6a7c0ec2e9f2c26ed6a0dc71a2c06b90c77352aea2958a88a63d5bfa79589ea",
          "sha1": "54f632c953d57828a8d7dcdfbaed533a999deda1",
          "md5": "be4a34bc17c93eba6d7547e53a24c974"
        }
      ]
    }
  ]
}
