{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.8.aar",
          "url": "core-0.75.8.aar",
          "size": 644265,
          "sha512": "7ab365e29d9bb1eb36b2f416584bceab8df982e11b37ecb9413ce79bfe74d0f94a19ca71f84a99c0c009fc403b7a1b097e0e56a7251e7da38337db3d397c321d",
          "sha256": "446e5da257f071804f0470524330335b373dbf99e6bffba95aa44834d019e318",
          "sha1": "46915931caa68c1918d191002ae8324dc3141ac4",
          "md5": "b5efa1d0fe08fd4b4b9a0518773aeaac"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.8.aar",
          "url": "core-0.75.8.aar",
          "size": 644265,
          "sha512": "7ab365e29d9bb1eb36b2f416584bceab8df982e11b37ecb9413ce79bfe74d0f94a19ca71f84a99c0c009fc403b7a1b097e0e56a7251e7da38337db3d397c321d",
          "sha256": "446e5da257f071804f0470524330335b373dbf99e6bffba95aa44834d019e318",
          "sha1": "46915931caa68c1918d191002ae8324dc3141ac4",
          "md5": "b5efa1d0fe08fd4b4b9a0518773aeaac"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.8-sources.jar",
          "url": "core-0.75.8-sources.jar",
          "size": 345429,
          "sha512": "890f37b2c10c699e53248116e85310f3ff0969db062c7a302dcacc9c57357b9bd590309fb1924aff8d809302c07faa5ee26132fbb96c3f2dc289720901da702e",
          "sha256": "6646e8af995e48d3696a7fec6ab6aafe0bc5ecc567f5df276e0a3130f89547e3",
          "sha1": "e4752361e8ee3d73fef562f887e9c23688680c39",
          "md5": "1076db1a17fc85ecbde839ab7489deae"
        }
      ]
    }
  ]
}
