{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.61.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.61.1.aar",
          "url": "utils-0.61.1.aar",
          "size": 44640,
          "sha512": "7fff925b045686a2fe796534bfea3d64043e9dee80fec5c06fa609d71bf0b953c69268b55443298694377c3a43733707505d0794d56ab474f0986fcf4654c750",
          "sha256": "c2b099c4970cc17facdc6ef883dcfe0fb083a5b932fb7606ca782c1f0e697a69",
          "sha1": "ab514dcf494f5b2bf615107c932bfb40e1da6efc",
          "md5": "7b48c88bd4250e0dbeae0069d698f171"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.61.1.aar",
          "url": "utils-0.61.1.aar",
          "size": 44640,
          "sha512": "7fff925b045686a2fe796534bfea3d64043e9dee80fec5c06fa609d71bf0b953c69268b55443298694377c3a43733707505d0794d56ab474f0986fcf4654c750",
          "sha256": "c2b099c4970cc17facdc6ef883dcfe0fb083a5b932fb7606ca782c1f0e697a69",
          "sha1": "ab514dcf494f5b2bf615107c932bfb40e1da6efc",
          "md5": "7b48c88bd4250e0dbeae0069d698f171"
        }
      ]
    }
  ]
}
