{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3nyxzpnzzvg4zbdubvx56dggea"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.27.0.aar",
          "url": "ui-0.27.0.aar",
          "size": 830713,
          "sha512": "c229d0681f9853a32ee8dfdd64770c502014977491700ab65b5d8dfd7c67612c51394a88dafb215eef31d0cb19b4c1a60b605100d1cf83d6d50afc8f65f74177",
          "sha256": "df57ec182e93b663b995c78e64b682e869548c557993a3b6d8b587d7377de8e0",
          "sha1": "2ea8108c6993851e5b5353bfd37084762ddd9c05",
          "md5": "fc0cd6ca6e7d63b0687860944025b27a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.27.0.aar",
          "url": "ui-0.27.0.aar",
          "size": 830713,
          "sha512": "c229d0681f9853a32ee8dfdd64770c502014977491700ab65b5d8dfd7c67612c51394a88dafb215eef31d0cb19b4c1a60b605100d1cf83d6d50afc8f65f74177",
          "sha256": "df57ec182e93b663b995c78e64b682e869548c557993a3b6d8b587d7377de8e0",
          "sha1": "2ea8108c6993851e5b5353bfd37084762ddd9c05",
          "md5": "fc0cd6ca6e7d63b0687860944025b27a"
        }
      ]
    }
  ]
}
