{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.52.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.52.0-beta01.aar",
          "url": "utils-0.52.0-beta01.aar",
          "size": 44504,
          "sha512": "1939d0078b9a1379f6bd850c03bb9f0083196db96008c7ed9bb001eff57dbd2fde006598fd2fbadbdfed70ffad4c2533a31743babae61a7f4f4b1e47cb94ad8f",
          "sha256": "29b2799c68ba4d9879c94df08e91042e467680a18fb9fb52a50f4eccba39e025",
          "sha1": "1326faccdfa8c7e20c08b17036ea00020bf52d01",
          "md5": "04567003c24e8640fb3c75add3bfc27a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.52.0-beta01.aar",
          "url": "utils-0.52.0-beta01.aar",
          "size": 44504,
          "sha512": "1939d0078b9a1379f6bd850c03bb9f0083196db96008c7ed9bb001eff57dbd2fde006598fd2fbadbdfed70ffad4c2533a31743babae61a7f4f4b1e47cb94ad8f",
          "sha256": "29b2799c68ba4d9879c94df08e91042e467680a18fb9fb52a50f4eccba39e025",
          "sha1": "1326faccdfa8c7e20c08b17036ea00020bf52d01",
          "md5": "04567003c24e8640fb3c75add3bfc27a"
        }
      ]
    }
  ]
}
