{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rki2fzqsmbd5neolp47hawt4ou"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.30.0.aar",
          "url": "utils-0.30.0.aar",
          "size": 42926,
          "sha512": "175615884835d6686aab7da477d4bd9a5c7311756b46eb0e8de1e20343070708ec17522f079f55a6e66cd0d67bced3fa28eec5092ced9e66e3902c0f5e9b593a",
          "sha256": "b6a42c55eafcb44617910157ded1eb08819d77de5cf55de4285d9dd6e8ed4bd6",
          "sha1": "46be7a985a6eb50602fd6a09de94a2df7a5f0c91",
          "md5": "98aee2cca386bf71d9b739c788fc98a3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.30.0.aar",
          "url": "utils-0.30.0.aar",
          "size": 42926,
          "sha512": "175615884835d6686aab7da477d4bd9a5c7311756b46eb0e8de1e20343070708ec17522f079f55a6e66cd0d67bced3fa28eec5092ced9e66e3902c0f5e9b593a",
          "sha256": "b6a42c55eafcb44617910157ded1eb08819d77de5cf55de4285d9dd6e8ed4bd6",
          "sha1": "46be7a985a6eb50602fd6a09de94a2df7a5f0c91",
          "md5": "98aee2cca386bf71d9b739c788fc98a3"
        }
      ]
    }
  ]
}
