{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.30.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "iznr6wigofczhg5nhsz32yhe34"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.30.1.aar",
          "url": "firebase-detector-0.30.1.aar",
          "size": 32737,
          "sha512": "893ec75b1c6f27b7cb48fb3249ab7cc193110ab21a83d3d6a2790384aebb02492fb1322f4678bc4a04c4d303b1bec360825fb8c0cae16e16fefe822dac0149ca",
          "sha256": "039f61dfe947fa07fd88b02bf54db3ae429ef712effeccb5a8f47d09a9b16e17",
          "sha1": "30d028c14763f82c2a17d1615eb1595911d6b6db",
          "md5": "ab39ac841f14f14aa2f79b645ff9762f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.30.1.aar",
          "url": "firebase-detector-0.30.1.aar",
          "size": 32737,
          "sha512": "893ec75b1c6f27b7cb48fb3249ab7cc193110ab21a83d3d6a2790384aebb02492fb1322f4678bc4a04c4d303b1bec360825fb8c0cae16e16fefe822dac0149ca",
          "sha256": "039f61dfe947fa07fd88b02bf54db3ae429ef712effeccb5a8f47d09a9b16e17",
          "sha1": "30d028c14763f82c2a17d1615eb1595911d6b6db",
          "md5": "ab39ac841f14f14aa2f79b645ff9762f"
        }
      ]
    }
  ]
}
