{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bhd4zr4wb5fopglwd7lkbaztd4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.2.aar",
          "url": "ui-integration-0.35.2.aar",
          "size": 93297,
          "sha512": "c8095a8befaa7b4a9f26180f3f49eb67dd6a7cdbf66a74085e8e57118eb0ac343af09fd7493f5cf404dd090e9f9284d8d6c4ec7821cef4cfb8dc5f14bb2d01e4",
          "sha256": "55d93d06fd1c22a2a1c0fb9e0d18a4a6979c730feb2f4c72b8d21c509db66d73",
          "sha1": "325f9e1be6e0d62fa35a547205d738314f4f5501",
          "md5": "2df8ee7abb6a00a7ae2b9433955c7322"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.2.aar",
          "url": "ui-integration-0.35.2.aar",
          "size": 93297,
          "sha512": "c8095a8befaa7b4a9f26180f3f49eb67dd6a7cdbf66a74085e8e57118eb0ac343af09fd7493f5cf404dd090e9f9284d8d6c4ec7821cef4cfb8dc5f14bb2d01e4",
          "sha256": "55d93d06fd1c22a2a1c0fb9e0d18a4a6979c730feb2f4c72b8d21c509db66d73",
          "sha1": "325f9e1be6e0d62fa35a547205d738314f4f5501",
          "md5": "2df8ee7abb6a00a7ae2b9433955c7322"
        }
      ]
    }
  ]
}
