{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.25.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jdjaink725hpjcqmmejphu4w7m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-detector-0.25.5.aar",
          "url": "firebase-detector-0.25.5.aar",
          "size": 31196,
          "sha512": "da261483059cf188091b7fc1b2e396101dd72513bce87c965ce7fd2ed57856ffab2f7546a40b27d0104022b87aaa129b498d2a86cb57953f1631485047d7b396",
          "sha256": "d7e2344af5cedbc8814f36c5fcbefedc226ae17a222772e32a1acc6e1c91f12c",
          "sha1": "4dd076163db26085c257acb58d4e0011fd18b9d5",
          "md5": "2eefd280341ca1b5fd9aca6a324e5ec6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.25.5.aar",
          "url": "firebase-detector-0.25.5.aar",
          "size": 31196,
          "sha512": "da261483059cf188091b7fc1b2e396101dd72513bce87c965ce7fd2ed57856ffab2f7546a40b27d0104022b87aaa129b498d2a86cb57953f1631485047d7b396",
          "sha256": "d7e2344af5cedbc8814f36c5fcbefedc226ae17a222772e32a1acc6e1c91f12c",
          "sha1": "4dd076163db26085c257acb58d4e0011fd18b9d5",
          "md5": "2eefd280341ca1b5fd9aca6a324e5ec6"
        }
      ]
    }
  ]
}
