{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "betsic4dyrehzcu3ysf6cxv24a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.1.aar",
          "url": "core-0.32.1.aar",
          "size": 325898,
          "sha512": "ee0e0fab05852976c3a123a8854af12adae5cee3afefe7e146bb12c32ae92dc4320903720635957158a200f703c3326e9f94cc999c47d19aef74cb42e7911af8",
          "sha256": "e5c30c3527faf163d8dac3069822a8d809805f36b3252678f9784d4ab4d1a90b",
          "sha1": "6854d2e09c0b633aafcd347af1c83f8b85cb3576",
          "md5": "924c7daea7541e62b81e467cfbf22c54"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.1.aar",
          "url": "core-0.32.1.aar",
          "size": 325898,
          "sha512": "ee0e0fab05852976c3a123a8854af12adae5cee3afefe7e146bb12c32ae92dc4320903720635957158a200f703c3326e9f94cc999c47d19aef74cb42e7911af8",
          "sha256": "e5c30c3527faf163d8dac3069822a8d809805f36b3252678f9784d4ab4d1a90b",
          "sha1": "6854d2e09c0b633aafcd347af1c83f8b85cb3576",
          "md5": "924c7daea7541e62b81e467cfbf22c54"
        }
      ]
    }
  ]
}
