{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lu5zwczqn5bzhkzih5ir6fb76i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-integration-0.26.0.aar",
          "url": "ui-integration-0.26.0.aar",
          "size": 73390,
          "sha512": "086a31ea1544ba99e5159383275a14fa4fbbefee56d0e73abd71f1e3b0edac9f2ed06ad3fb76dcc13b1c76c1a85e423a2d70db846ad0b2137751a7eb90c3f443",
          "sha256": "ffef43f3d90abfbae91f2522b84ad185e87c2651ab2fa13ce1d310d920293933",
          "sha1": "747da33128b54c35dd3e9b068b14a725e887f7a3",
          "md5": "9bc6b64bc8386868cc46d21225a3c5d6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.26.0.aar",
          "url": "ui-integration-0.26.0.aar",
          "size": 73390,
          "sha512": "086a31ea1544ba99e5159383275a14fa4fbbefee56d0e73abd71f1e3b0edac9f2ed06ad3fb76dcc13b1c76c1a85e423a2d70db846ad0b2137751a7eb90c3f443",
          "sha256": "ffef43f3d90abfbae91f2522b84ad185e87c2651ab2fa13ce1d310d920293933",
          "sha1": "747da33128b54c35dd3e9b068b14a725e887f7a3",
          "md5": "9bc6b64bc8386868cc46d21225a3c5d6"
        }
      ]
    }
  ]
}
