{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.24.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4hu6kew2fnfs5mmeyqbymjjzou"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.24.6-SNAPSHOT.aar",
          "url": "ui-0.24.6-SNAPSHOT.aar",
          "size": 804284,
          "sha512": "0674764dd45b59084a5cf293b8b96036b7f42405cf17c5d56eb5977af64bada423e8b799b3fb1138c50a46d14758f71be8f44d6ce894dce74d1cf295b80cd6e8",
          "sha256": "81e5b644b8720694bc03f3b20ad3eb06ad021c1cb46f1b5d2520f64a4f851dc0",
          "sha1": "c780fadd1a9457e4f043081e12dc7b7824994b66",
          "md5": "d97fab4bbffbd59f29df1a01abb81229"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.24.6-SNAPSHOT"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.24.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.24.6-SNAPSHOT.aar",
          "url": "ui-0.24.6-SNAPSHOT.aar",
          "size": 804284,
          "sha512": "0674764dd45b59084a5cf293b8b96036b7f42405cf17c5d56eb5977af64bada423e8b799b3fb1138c50a46d14758f71be8f44d6ce894dce74d1cf295b80cd6e8",
          "sha256": "81e5b644b8720694bc03f3b20ad3eb06ad021c1cb46f1b5d2520f64a4f851dc0",
          "sha1": "c780fadd1a9457e4f043081e12dc7b7824994b66",
          "md5": "d97fab4bbffbd59f29df1a01abb81229"
        }
      ]
    }
  ]
}
