{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.29.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2iqt364jrfa67og6wb4xwnqb5q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.9.aar",
          "url": "firebase-detector-0.29.9.aar",
          "size": 32729,
          "sha512": "53534f996a5cc3e1570eaefd10f79d7fd1b8ef036d1b857cb96604852148b371f03da47dbc6fc5a43b9ffc57ebf731012b02ce13e9791fb807d10329cae37b5a",
          "sha256": "f6d142dcca28665beaabdf701a8ea787464b27c8c4adc0ddcfc8c5ed3204adf1",
          "sha1": "b66476aa8d0f4351770e3aeb184b9a8920a4db78",
          "md5": "8138036833864d74d87e2305181e82b1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.9"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.9"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.9"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.9.aar",
          "url": "firebase-detector-0.29.9.aar",
          "size": 32729,
          "sha512": "53534f996a5cc3e1570eaefd10f79d7fd1b8ef036d1b857cb96604852148b371f03da47dbc6fc5a43b9ffc57ebf731012b02ce13e9791fb807d10329cae37b5a",
          "sha256": "f6d142dcca28665beaabdf701a8ea787464b27c8c4adc0ddcfc8c5ed3204adf1",
          "sha1": "b66476aa8d0f4351770e3aeb184b9a8920a4db78",
          "md5": "8138036833864d74d87e2305181e82b1"
        }
      ]
    }
  ]
}
