{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.73.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.73.0.aar",
          "url": "mlkit-scanner-engine-0.73.0.aar",
          "size": 63939,
          "sha512": "0aa871af253046f066c8e9c26306ea7813d23a5e87aa592f0996f10d18a5926cdbb6885e763b5d3df5a098e53b30868215ddec23701f347b56e73a0ef6a30aea",
          "sha256": "ee5eebf3a2c840b64f65b86d20a8a43ae8d52e1de33da167e566fdf1057e775b",
          "sha1": "47ffdd2251c2f8186e8963b9ff46946f82d1d216",
          "md5": "747fe5c0513403986f553bed15989c88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.73.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.73.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.73.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.73.0.aar",
          "url": "mlkit-scanner-engine-0.73.0.aar",
          "size": 63939,
          "sha512": "0aa871af253046f066c8e9c26306ea7813d23a5e87aa592f0996f10d18a5926cdbb6885e763b5d3df5a098e53b30868215ddec23701f347b56e73a0ef6a30aea",
          "sha256": "ee5eebf3a2c840b64f65b86d20a8a43ae8d52e1de33da167e566fdf1057e775b",
          "sha1": "47ffdd2251c2f8186e8963b9ff46946f82d1d216",
          "md5": "747fe5c0513403986f553bed15989c88"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.73.0-sources.jar",
          "url": "mlkit-scanner-engine-0.73.0-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
