{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mpvjd33lrnczjicks3ngo5gw54"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.2.aar",
          "url": "core-0.39.2.aar",
          "size": 367731,
          "sha512": "a4e924008bdb5e2b50d5a7bd9fca188c9d913f4883a8b3d880d4444224a9b7e905ec9ab8dbe57e831fd87d34c03d085ac14fe11439ba95d3f6a5d2946647e9d9",
          "sha256": "6cf80e75d957e77592a9b43c638e22ff5ee85c5ca912e12c0d10e6488f50ad08",
          "sha1": "547fc8ddf7a71c07d9dc47cc8d1bac8c052ae8e5",
          "md5": "b2a7f600d7d37ad6b8a070eab7dbb30d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.2.aar",
          "url": "core-0.39.2.aar",
          "size": 367731,
          "sha512": "a4e924008bdb5e2b50d5a7bd9fca188c9d913f4883a8b3d880d4444224a9b7e905ec9ab8dbe57e831fd87d34c03d085ac14fe11439ba95d3f6a5d2946647e9d9",
          "sha256": "6cf80e75d957e77592a9b43c638e22ff5ee85c5ca912e12c0d10e6488f50ad08",
          "sha1": "547fc8ddf7a71c07d9dc47cc8d1bac8c052ae8e5",
          "md5": "b2a7f600d7d37ad6b8a070eab7dbb30d"
        }
      ]
    }
  ]
}
