{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sju4g5fjoze6pnwveeiadmeyny"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.6.aar",
          "url": "core-0.25.6.aar",
          "size": 272161,
          "sha512": "af488baaa1d71c9c2979155977b6c61910a1728546ded75809b15d79d97817a6621fd658b2d2cae7bbb9cbf0ab31ab68f0cc592e34e9a730c4b1c6ef49371b47",
          "sha256": "1e16a20ebac487d30963b890563ae28461ec338e871e3a5ca21ae68452830881",
          "sha1": "126717c445361ae8860773a7acfc7719a9b7cbf9",
          "md5": "215a663b7cce47048fdf858d998f090e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.6.aar",
          "url": "core-0.25.6.aar",
          "size": 272161,
          "sha512": "af488baaa1d71c9c2979155977b6c61910a1728546ded75809b15d79d97817a6621fd658b2d2cae7bbb9cbf0ab31ab68f0cc592e34e9a730c4b1c6ef49371b47",
          "sha256": "1e16a20ebac487d30963b890563ae28461ec338e871e3a5ca21ae68452830881",
          "sha1": "126717c445361ae8860773a7acfc7719a9b7cbf9",
          "md5": "215a663b7cce47048fdf858d998f090e"
        }
      ]
    }
  ]
}
