{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.32.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4pup4szq2neoldqbonx2hyf2ly"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.32.6.aar",
          "url": "firebase-detector-0.32.6.aar",
          "size": 32955,
          "sha512": "54630e700545af044fca496c311e8292530477dd58c9882b5a15cae0305723e93f2317af0b8181c0526954dd688099802698daad85ebeb0c218d0a928176c111",
          "sha256": "e50a370b54f3e45353d429e34cf29d04b85266d604226522c7cce58e77b2a0e5",
          "sha1": "31d6b0b20bbf5d594580989c4e1ce3d912d6ab83",
          "md5": "be3fa8b5aaa2db3d70c308d1fe7baef4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.32.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.32.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.6"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.32.6.aar",
          "url": "firebase-detector-0.32.6.aar",
          "size": 32955,
          "sha512": "54630e700545af044fca496c311e8292530477dd58c9882b5a15cae0305723e93f2317af0b8181c0526954dd688099802698daad85ebeb0c218d0a928176c111",
          "sha256": "e50a370b54f3e45353d429e34cf29d04b85266d604226522c7cce58e77b2a0e5",
          "sha1": "31d6b0b20bbf5d594580989c4e1ce3d912d6ab83",
          "md5": "be3fa8b5aaa2db3d70c308d1fe7baef4"
        }
      ]
    }
  ]
}
