{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "usmtob6fsrekbhydgqdqxeqkdm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.6.aar",
          "url": "core-0.39.6.aar",
          "size": 368351,
          "sha512": "382461a8329d4af2766a1a8cf10585c5d2882d034aa86eba643c8a2c55907e95027a7170a76db45d55163ea92b37360fb2d4430ef1013c4ac6a7a06f70745a0a",
          "sha256": "61a5e9a873704a00c9cce4f21f6bb8449e815ee8345d92889910703dad7d55c7",
          "sha1": "ca5d8ebe164b7a3a0b34cddfcb82f851ac016eff",
          "md5": "5332d08e0d269619bfce96be21e37e3c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.6.aar",
          "url": "core-0.39.6.aar",
          "size": 368351,
          "sha512": "382461a8329d4af2766a1a8cf10585c5d2882d034aa86eba643c8a2c55907e95027a7170a76db45d55163ea92b37360fb2d4430ef1013c4ac6a7a06f70745a0a",
          "sha256": "61a5e9a873704a00c9cce4f21f6bb8449e815ee8345d92889910703dad7d55c7",
          "sha1": "ca5d8ebe164b7a3a0b34cddfcb82f851ac016eff",
          "md5": "5332d08e0d269619bfce96be21e37e3c"
        }
      ]
    }
  ]
}
