{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4hiutxtlnjboni5ho6s4oitmpm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.1.aar",
          "url": "utils-0.29.1.aar",
          "size": 40158,
          "sha512": "61f42605885d52b221d8af1a57cc3dfb48dc2dd356c749589632d308d80ac8c8970fc679de76c8b3b5f40964942fd6c578ceb72afa9eaaf7ec20cd5c48325ada",
          "sha256": "2359f485254f18e1931e57fd3028cb82448d6b17afcc9ca1e8b678c18fff9eeb",
          "sha1": "31f84e7a96044586e12c4c206e485c7ed1afad56",
          "md5": "0ba86c7d1eb4287a8b3dd9198f858a97"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.1.aar",
          "url": "utils-0.29.1.aar",
          "size": 40158,
          "sha512": "61f42605885d52b221d8af1a57cc3dfb48dc2dd356c749589632d308d80ac8c8970fc679de76c8b3b5f40964942fd6c578ceb72afa9eaaf7ec20cd5c48325ada",
          "sha256": "2359f485254f18e1931e57fd3028cb82448d6b17afcc9ca1e8b678c18fff9eeb",
          "sha1": "31f84e7a96044586e12c4c206e485c7ed1afad56",
          "md5": "0ba86c7d1eb4287a8b3dd9198f858a97"
        }
      ]
    }
  ]
}
