{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.35.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r35ykfg6ajcobowcbmzibvcpfm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.35.4.aar",
          "url": "utils-0.35.4.aar",
          "size": 43033,
          "sha512": "f2b9cff5670be13a0fb9146dda3e2bbb5c65cfdaab1e214808560d2491b7741de3532634f876f9cfcaba9496dcadb873f7693df0b55a7299c53eda38e4c68b3f",
          "sha256": "94e34e3f097987fa5e7aa643cb6f435d1155059b79c5098a639946fd787e786b",
          "sha1": "29f6321a6b5e2f3bc7bd68965c2e6dd170832a28",
          "md5": "f77fc992ecc927329a1b349044ea6ec1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.35.4.aar",
          "url": "utils-0.35.4.aar",
          "size": 43033,
          "sha512": "f2b9cff5670be13a0fb9146dda3e2bbb5c65cfdaab1e214808560d2491b7741de3532634f876f9cfcaba9496dcadb873f7693df0b55a7299c53eda38e4c68b3f",
          "sha256": "94e34e3f097987fa5e7aa643cb6f435d1155059b79c5098a639946fd787e786b",
          "sha1": "29f6321a6b5e2f3bc7bd68965c2e6dd170832a28",
          "md5": "f77fc992ecc927329a1b349044ea6ec1"
        }
      ]
    }
  ]
}
