{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.11.aar",
          "url": "core-0.80.11.aar",
          "size": 668649,
          "sha512": "6d2ef13018351be3a272f51b19712651ebf4ea9dc50b9392417ae659eb7dc442db93cd03a23f1ef4d040abc37446cc330d1386e597a1741c626869e9083c246c",
          "sha256": "bcd2f135585b849eaa4e1d15454e27c5d6b8bc871ff7e6c43c05ae7ef370aa49",
          "sha1": "f7a1e50f83671d711b4a0428ed9bd4f2dde0a12a",
          "md5": "2cc662243ec70531af80c95f82b28112"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.11"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.11.aar",
          "url": "core-0.80.11.aar",
          "size": 668649,
          "sha512": "6d2ef13018351be3a272f51b19712651ebf4ea9dc50b9392417ae659eb7dc442db93cd03a23f1ef4d040abc37446cc330d1386e597a1741c626869e9083c246c",
          "sha256": "bcd2f135585b849eaa4e1d15454e27c5d6b8bc871ff7e6c43c05ae7ef370aa49",
          "sha1": "f7a1e50f83671d711b4a0428ed9bd4f2dde0a12a",
          "md5": "2cc662243ec70531af80c95f82b28112"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.11-sources.jar",
          "url": "core-0.80.11-sources.jar",
          "size": 352215,
          "sha512": "b3f9b69251ba01709519440b97e7c56aaaf50de676c4ad436915b11637d5c46b2de4c7323e3edb027deffbe454cbe5ad36d5b6d9e01d1b65fc5b17ffd13fa6f7",
          "sha256": "4b1c3473d540e8904b394dec98d0902d4591eb7fca840b4243516c235f341b69",
          "sha1": "03ef4c491de12ebf3057390c47228e5d3a9a2b87",
          "md5": "41ea61bf35676dd549698bb06133b995"
        }
      ]
    }
  ]
}
