{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "e6cbextnvvawhnnaseimdvekli"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.7.aar",
          "url": "ui-integration-0.35.7.aar",
          "size": 93309,
          "sha512": "cbaff9dce023f4e6f5ac29628ae65da625d10fa2fc4a27cf007e0441ba8f3ad9fc6a26fcd5da91bc6ea39a9b2b8882fef926c55c565cbe5a7db50d62ebe69fa2",
          "sha256": "5650df6c5daa38ba9dc9a798b79aefcb602974f8a6288f32f9123c536edd5780",
          "sha1": "e147f49f73287a3c193c1d60ea6708c477e539c2",
          "md5": "73a44bd4b16d79de5531728f63af9b19"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.7"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.7.aar",
          "url": "ui-integration-0.35.7.aar",
          "size": 93309,
          "sha512": "cbaff9dce023f4e6f5ac29628ae65da625d10fa2fc4a27cf007e0441ba8f3ad9fc6a26fcd5da91bc6ea39a9b2b8882fef926c55c565cbe5a7db50d62ebe69fa2",
          "sha256": "5650df6c5daa38ba9dc9a798b79aefcb602974f8a6288f32f9123c536edd5780",
          "sha1": "e147f49f73287a3c193c1d60ea6708c477e539c2",
          "md5": "73a44bd4b16d79de5531728f63af9b19"
        }
      ]
    }
  ]
}
