{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.37.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6aj7vn6jdvee7afwfbc5e3xw7y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.6.aar",
          "url": "core-0.37.6.aar",
          "size": 351966,
          "sha512": "27c44782476b65b32c69d450ee9b0a08d66d18d2ce8247e32b78a758b9650aa27b2cef4b1e1237f393c7e7f8d89a971f2c44d235b0b1ae15b87188b03611cbe3",
          "sha256": "a0f032f2bd023b1dfc89771149ec6092633337836d8c542271d218efcda90f8e",
          "sha1": "7c1d9d82d585dd872a3e9247a261ed63210fe807",
          "md5": "5a40293219f67b3078341e6ce6a29613"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.6.aar",
          "url": "core-0.37.6.aar",
          "size": 351966,
          "sha512": "27c44782476b65b32c69d450ee9b0a08d66d18d2ce8247e32b78a758b9650aa27b2cef4b1e1237f393c7e7f8d89a971f2c44d235b0b1ae15b87188b03611cbe3",
          "sha256": "a0f032f2bd023b1dfc89771149ec6092633337836d8c542271d218efcda90f8e",
          "sha1": "7c1d9d82d585dd872a3e9247a261ed63210fe807",
          "md5": "5a40293219f67b3078341e6ce6a29613"
        }
      ]
    }
  ]
}
