{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "p4oipcf3fjdwrpskpquedrcsbe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.8.aar",
          "url": "ui-integration-0.35.8.aar",
          "size": 93308,
          "sha512": "bfa335087b1ec0ca01e93f1a271dbfc999086420bc4ddd6d0a89689e895245ac288f13591e7c59fd35ede2ebef597daec0ba5c4260f4d01111b5eb743f77623b",
          "sha256": "7d4762859d5e253c8e19b69e5e25c7be4776224ac2b5c18b4929a7f988aa5906",
          "sha1": "7387c857e3735cd8914fa9898f5d766c27f13891",
          "md5": "ff29827a47ffc2524c76869df1514620"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.8.aar",
          "url": "ui-integration-0.35.8.aar",
          "size": 93308,
          "sha512": "bfa335087b1ec0ca01e93f1a271dbfc999086420bc4ddd6d0a89689e895245ac288f13591e7c59fd35ede2ebef597daec0ba5c4260f4d01111b5eb743f77623b",
          "sha256": "7d4762859d5e253c8e19b69e5e25c7be4776224ac2b5c18b4929a7f988aa5906",
          "sha1": "7387c857e3735cd8914fa9898f5d766c27f13891",
          "md5": "ff29827a47ffc2524c76869df1514620"
        }
      ]
    }
  ]
}
