{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.75.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.75.8.aar",
          "url": "mlkit-scanner-engine-0.75.8.aar",
          "size": 64034,
          "sha512": "678bc604da3617d3c70f67fee29e61f0917da70d8e2b1af88315d6b8f604fb6116686b5127c9f4ec50f43cb28ed7884df7e601dcd31ee6e8d5d397ee948a9d38",
          "sha256": "4b7e48ca4af568bacad7ad73b9121e5f6263d53ba8f99a569457f9dd08eea7d3",
          "sha1": "b1e9ac975038f1efcf194de17c2ca97a041c941a",
          "md5": "e18e1e1cf6c2caf48bf1a24c9aae3e88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.75.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.75.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.8"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.75.8.aar",
          "url": "mlkit-scanner-engine-0.75.8.aar",
          "size": 64034,
          "sha512": "678bc604da3617d3c70f67fee29e61f0917da70d8e2b1af88315d6b8f604fb6116686b5127c9f4ec50f43cb28ed7884df7e601dcd31ee6e8d5d397ee948a9d38",
          "sha256": "4b7e48ca4af568bacad7ad73b9121e5f6263d53ba8f99a569457f9dd08eea7d3",
          "sha1": "b1e9ac975038f1efcf194de17c2ca97a041c941a",
          "md5": "e18e1e1cf6c2caf48bf1a24c9aae3e88"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.75.8-sources.jar",
          "url": "mlkit-scanner-engine-0.75.8-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
