{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.37.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "isjfzwozkfecnno43fswrlvivm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.2.aar",
          "url": "ui-integration-0.37.2.aar",
          "size": 99926,
          "sha512": "33772ae2ca164f4701583dbe10280edcc586f53185f9cb4726db492808f8241f593dfca988bb6973172417f2ab2d5aa06a033ed9f2dc6514dbefa87e08775847",
          "sha256": "df4552cd004ce2b641db1afded65eeae9ad2b3ad49319f07b0f73ce750e952af",
          "sha1": "aef9ed370a294413f968feab31d51fa4bcf3e931",
          "md5": "665b28d3de3ac5c8fa66b68a568b0399"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.37.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.37.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.2.aar",
          "url": "ui-integration-0.37.2.aar",
          "size": 99926,
          "sha512": "33772ae2ca164f4701583dbe10280edcc586f53185f9cb4726db492808f8241f593dfca988bb6973172417f2ab2d5aa06a033ed9f2dc6514dbefa87e08775847",
          "sha256": "df4552cd004ce2b641db1afded65eeae9ad2b3ad49319f07b0f73ce750e952af",
          "sha1": "aef9ed370a294413f968feab31d51fa4bcf3e931",
          "md5": "665b28d3de3ac5c8fa66b68a568b0399"
        }
      ]
    }
  ]
}
