{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.39.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7znmgncnbbewndme27bsnj3shm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.39.0.aar",
          "url": "ui-integration-0.39.0.aar",
          "size": 100134,
          "sha512": "40fe149c7524caf6a1b6622db29aba05ca2e381f94900f81cb4efcd01f3ae5b39a6264e2fbf69b425a5a3a1900685efccc47a47c18bffb441ea4a83628ce5236",
          "sha256": "812b2a33ff6c9035294ad0eb187cd71f518a9dfb8f737bf9f5e6f0ff8b1b64d3",
          "sha1": "e25157c3fed8a201889406f9cfd5173a3a14702e",
          "md5": "7b64e099c4dfe053df8c354d78395a4f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.39.0.aar",
          "url": "ui-integration-0.39.0.aar",
          "size": 100134,
          "sha512": "40fe149c7524caf6a1b6622db29aba05ca2e381f94900f81cb4efcd01f3ae5b39a6264e2fbf69b425a5a3a1900685efccc47a47c18bffb441ea4a83628ce5236",
          "sha256": "812b2a33ff6c9035294ad0eb187cd71f518a9dfb8f737bf9f5e6f0ff8b1b64d3",
          "sha1": "e25157c3fed8a201889406f9cfd5173a3a14702e",
          "md5": "7b64e099c4dfe053df8c354d78395a4f"
        }
      ]
    }
  ]
}
