{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lu5zwczqn5bzhkzih5ir6fb76i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.26.0.aar",
          "url": "ui-0.26.0.aar",
          "size": 829049,
          "sha512": "c7172e0b6321b958a46ea8e40bda943bd4ce2853705bd2100385fdae25c84dfbbfbeeb1981205ad594e473900756848bdc78c176f83d22d4ff4ce6cd752d2f50",
          "sha256": "eabe4276d1a9b57b8bb1076f7c7aebc3c3f2824ba018d8dcfa1963543cbd80a3",
          "sha1": "893881db8c40c0b086bcf0ce606b236a1c4e42ef",
          "md5": "1d420285f07dfe8f7a421a5e4d8954b7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.26.0.aar",
          "url": "ui-0.26.0.aar",
          "size": 829049,
          "sha512": "c7172e0b6321b958a46ea8e40bda943bd4ce2853705bd2100385fdae25c84dfbbfbeeb1981205ad594e473900756848bdc78c176f83d22d4ff4ce6cd752d2f50",
          "sha256": "eabe4276d1a9b57b8bb1076f7c7aebc3c3f2824ba018d8dcfa1963543cbd80a3",
          "sha1": "893881db8c40c0b086bcf0ce606b236a1c4e42ef",
          "md5": "1d420285f07dfe8f7a421a5e4d8954b7"
        }
      ]
    }
  ]
}
