{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.72.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.5.aar",
          "url": "core-0.72.5.aar",
          "size": 597424,
          "sha512": "7c67a51e06032b1c6070b52d27f8e496c4f9562bce7efa0b252b41b9d9a3200ac4e9ff9bb0aacac0404d5d57610084ba2cb53fbc3e350fa70a241a4df0c626ff",
          "sha256": "bdd95bec39f3c43a569cbb6501c8c0c241d9e89617d053d3164a96d3c825c499",
          "sha1": "5c2ae1e8ad29fd542147a71fa5108851ee653f0c",
          "md5": "448da53d9c3132db95f91d0da5f70218"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.5.aar",
          "url": "core-0.72.5.aar",
          "size": 597424,
          "sha512": "7c67a51e06032b1c6070b52d27f8e496c4f9562bce7efa0b252b41b9d9a3200ac4e9ff9bb0aacac0404d5d57610084ba2cb53fbc3e350fa70a241a4df0c626ff",
          "sha256": "bdd95bec39f3c43a569cbb6501c8c0c241d9e89617d053d3164a96d3c825c499",
          "sha1": "5c2ae1e8ad29fd542147a71fa5108851ee653f0c",
          "md5": "448da53d9c3132db95f91d0da5f70218"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.72.5-sources.jar",
          "url": "core-0.72.5-sources.jar",
          "size": 330663,
          "sha512": "d9974a03c153b2fbeceac5d22a913728260f69b547261d8a593f4238be9b24ff4bb77e05eb97901e0ea095e30ba0c35787fbcb055ac194dd883df46f732549a4",
          "sha256": "668e2ee3c15236b497983a07db32e2005ee0e42c25c55c22288449d7498090fa",
          "sha1": "007b8d2ce9a6c93cc787a7e1de2419c637696282",
          "md5": "2971cde44b69236023df531326b6317d"
        }
      ]
    }
  ]
}
