{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.35.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "55q4jl7qxrcpvkxgcg2mlj3xuu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.35.9.aar",
          "url": "utils-0.35.9.aar",
          "size": 43704,
          "sha512": "892257dd1ffda88d99a7445703c4044efcbf7198f7b0e300fa0ed3fc4018712b746c4a1c30697783505d7ca70265feadfa46321210e5b16779dfa658583c81c2",
          "sha256": "ee77d22979bae0c04f3eb0a97d42c5581d51ab6d3c6031db4e468090a0fb67c7",
          "sha1": "77e7b28d6847b96e50681ad0d6ac7f8802a3d80d",
          "md5": "899caceccd4ce4a97a8893005b44f36d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.35.9.aar",
          "url": "utils-0.35.9.aar",
          "size": 43704,
          "sha512": "892257dd1ffda88d99a7445703c4044efcbf7198f7b0e300fa0ed3fc4018712b746c4a1c30697783505d7ca70265feadfa46321210e5b16779dfa658583c81c2",
          "sha256": "ee77d22979bae0c04f3eb0a97d42c5581d51ab6d3c6031db4e468090a0fb67c7",
          "sha1": "77e7b28d6847b96e50681ad0d6ac7f8802a3d80d",
          "md5": "899caceccd4ce4a97a8893005b44f36d"
        }
      ]
    }
  ]
}
