{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "V0.81.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-V0.81.1.aar",
          "url": "mlkit-scanner-engine-V0.81.1.aar",
          "size": 64085,
          "sha512": "0370b4345ab9d35f51c01c8b65f9882cf9da9f4e9a02bda64391fd3e1c7c50d8d1643b82a789f430632c9e944ac997ba5ac235f9dd1420a3af8b3e2fc84b8001",
          "sha256": "68d4815fb39e87f1c0e74b0c9f38b6d8bd19bc2e119f99f4cb1de140992285ca",
          "sha1": "0a6ea4439b369e865c5b239ebc764456fa9c0741",
          "md5": "1e4e1425e882c72ae254ca6bfb6d4b2d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "V0.81.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "V0.81.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "V0.81.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-V0.81.1.aar",
          "url": "mlkit-scanner-engine-V0.81.1.aar",
          "size": 64085,
          "sha512": "0370b4345ab9d35f51c01c8b65f9882cf9da9f4e9a02bda64391fd3e1c7c50d8d1643b82a789f430632c9e944ac997ba5ac235f9dd1420a3af8b3e2fc84b8001",
          "sha256": "68d4815fb39e87f1c0e74b0c9f38b6d8bd19bc2e119f99f4cb1de140992285ca",
          "sha1": "0a6ea4439b369e865c5b239ebc764456fa9c0741",
          "md5": "1e4e1425e882c72ae254ca6bfb6d4b2d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-V0.81.1-sources.jar",
          "url": "mlkit-scanner-engine-V0.81.1-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
