{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sx5lzouqpvf7tj3mqx2kopdhwm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.0.aar",
          "url": "core-0.29.0.aar",
          "size": 286818,
          "sha512": "938e32b326de99ebce10ee39337b7179b8556dff5802674145d27323191632c4149aee65b02e197f7bbd17f39787cc4ab2bd2a20245db35a57c24cc2530d82ab",
          "sha256": "3a546fcd293823a94a803f3ddd1dfc4bcfab0204ca1c68cf4c7aa124e4eeead0",
          "sha1": "13052b2ce339a6aa27667abf37dc9f2baf2d2ce1",
          "md5": "20ac175130067e1e931bf047139675ec"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.0.aar",
          "url": "core-0.29.0.aar",
          "size": 286818,
          "sha512": "938e32b326de99ebce10ee39337b7179b8556dff5802674145d27323191632c4149aee65b02e197f7bbd17f39787cc4ab2bd2a20245db35a57c24cc2530d82ab",
          "sha256": "3a546fcd293823a94a803f3ddd1dfc4bcfab0204ca1c68cf4c7aa124e4eeead0",
          "sha1": "13052b2ce339a6aa27667abf37dc9f2baf2d2ce1",
          "md5": "20ac175130067e1e931bf047139675ec"
        }
      ]
    }
  ]
}
