{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.82.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.0.aar",
          "url": "mlkit-scanner-engine-0.82.0.aar",
          "size": 64117,
          "sha512": "cb3eb83837f9dda6f1313336ad61bdbcd0077cd287af815626eccc3776d0a0c223369ba9ac09c69dc60215fed9cb22a1a774febbab528a01338c0bf0c4da72d8",
          "sha256": "1868ab6dcaeeed1cfd3525460dd37d86c04f97506b67d947cc8ddd086689833b",
          "sha1": "bdaed6804e43358b7da2d717d7f23e41a5078679",
          "md5": "6c44dd863ac1dab1ec42439102e3b129"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.82.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.82.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.0.aar",
          "url": "mlkit-scanner-engine-0.82.0.aar",
          "size": 64117,
          "sha512": "cb3eb83837f9dda6f1313336ad61bdbcd0077cd287af815626eccc3776d0a0c223369ba9ac09c69dc60215fed9cb22a1a774febbab528a01338c0bf0c4da72d8",
          "sha256": "1868ab6dcaeeed1cfd3525460dd37d86c04f97506b67d947cc8ddd086689833b",
          "sha1": "bdaed6804e43358b7da2d717d7f23e41a5078679",
          "md5": "6c44dd863ac1dab1ec42439102e3b129"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.0-sources.jar",
          "url": "mlkit-scanner-engine-0.82.0-sources.jar",
          "size": 7461,
          "sha512": "221159708b9b3989fce5be7004949d5bc0fd9004ca06e5e7133c8463ef545036a99acfbbff07d8a5f7c45086a01c1027bb7ab5ed21ab5a39c3a946d89a0d1642",
          "sha256": "4c1778dc04c1bff7ab6efb7aef8d27e937239e5676c3213b6d304cf1b24234f8",
          "sha1": "2568d2be894590900c461738ce35d7ec6f448558",
          "md5": "652b419bbfc5db29899d2c1abb8fc63c"
        }
      ]
    }
  ]
}
