{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.52.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.52.0-beta04.aar",
          "url": "ui-integration-0.52.0-beta04.aar",
          "size": 108324,
          "sha512": "9ce83915132f08a156cac2faf3477d059f3804ebdab61443c4d5c75780b43f7625d2119dc01bdcdefbcb7d91f84ec1dbc3d83a6e7d4581122a46ab5206f40b5b",
          "sha256": "12861ec653cb2944f97f523451817b186791478810a876ec67d381074dcd3b41",
          "sha1": "a03256c4b259a8f44f5f8a5b07b41c835cf92f8a",
          "md5": "28002fa390dac613694781ca53f2676e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.52.0-beta04"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.52.0-beta04"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.52.0-beta04"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.52.0-beta04.aar",
          "url": "ui-integration-0.52.0-beta04.aar",
          "size": 108324,
          "sha512": "9ce83915132f08a156cac2faf3477d059f3804ebdab61443c4d5c75780b43f7625d2119dc01bdcdefbcb7d91f84ec1dbc3d83a6e7d4581122a46ab5206f40b5b",
          "sha256": "12861ec653cb2944f97f523451817b186791478810a876ec67d381074dcd3b41",
          "sha1": "a03256c4b259a8f44f5f8a5b07b41c835cf92f8a",
          "md5": "28002fa390dac613694781ca53f2676e"
        }
      ]
    }
  ]
}
