{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.29.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6yyo6zayljgyvb43z64zn45arm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.29.8.aar",
          "url": "ui-0.29.8.aar",
          "size": 833817,
          "sha512": "d7e4131fe33a5b4122ea0fce52bf444ffbb4945708e4d7fabf8ca1680f0d5652082dfb1835cede69e31a75a8816d84157658c05137063ddc32acfc6f61971d7f",
          "sha256": "acdac3ebdfb30ec998b2601cbb1105f70f47dc2797d3cd43856eb3b03dfaa448",
          "sha1": "bf2c4cf20ba171e377f3247a10d249e404f8a8a0",
          "md5": "2cc8c4603085d1167cb49bccf7165a64"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.8"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.29.8.aar",
          "url": "ui-0.29.8.aar",
          "size": 833817,
          "sha512": "d7e4131fe33a5b4122ea0fce52bf444ffbb4945708e4d7fabf8ca1680f0d5652082dfb1835cede69e31a75a8816d84157658c05137063ddc32acfc6f61971d7f",
          "sha256": "acdac3ebdfb30ec998b2601cbb1105f70f47dc2797d3cd43856eb3b03dfaa448",
          "sha1": "bf2c4cf20ba171e377f3247a10d249e404f8a8a0",
          "md5": "2cc8c4603085d1167cb49bccf7165a64"
        }
      ]
    }
  ]
}
