{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.26.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qnnc5xf27nhqdblyvtq6zbodxu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.4.aar",
          "url": "core-0.26.4.aar",
          "size": 273022,
          "sha512": "73e72a7d5d9d69bb30fcb4d12510d880ca772f3762cdf9feca8d11fdc9871fea7b4fc46fc502832838ce4db00f3c8d62feb6aa5f55e61f551c5cc4f697f63fd7",
          "sha256": "6046a5a58b178836535d7e7200353db390143cd56e2eb9f84b31adc0be5ca73b",
          "sha1": "c0fdbfd325f68571d6cd7651cfad33ab47786e8d",
          "md5": "30862ef9ed0dc3ec264d619cdb75e9d1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.4.aar",
          "url": "core-0.26.4.aar",
          "size": 273022,
          "sha512": "73e72a7d5d9d69bb30fcb4d12510d880ca772f3762cdf9feca8d11fdc9871fea7b4fc46fc502832838ce4db00f3c8d62feb6aa5f55e61f551c5cc4f697f63fd7",
          "sha256": "6046a5a58b178836535d7e7200353db390143cd56e2eb9f84b31adc0be5ca73b",
          "sha1": "c0fdbfd325f68571d6cd7651cfad33ab47786e8d",
          "md5": "30862ef9ed0dc3ec264d619cdb75e9d1"
        }
      ]
    }
  ]
}
