{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lu5zwczqn5bzhkzih5ir6fb76i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.26.0.aar",
          "url": "utils-0.26.0.aar",
          "size": 39923,
          "sha512": "33605e7eb25f486be285f0b1c868675d44f55238a3923beae20837ef89e6e07eb633c206eebc22d8de32ace98704d012c9aede7d0953788ae7965d5d4d14acec",
          "sha256": "51a24f4ffc6e2f0f0a1fe6b82c9e49fb9905c13437846ecc89f301e71d2051c8",
          "sha1": "eaf916beacdadcf8426c94cbf7b553133e4dd9d3",
          "md5": "252d7f04d172b1870f273e36fd07f28c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.26.0.aar",
          "url": "utils-0.26.0.aar",
          "size": 39923,
          "sha512": "33605e7eb25f486be285f0b1c868675d44f55238a3923beae20837ef89e6e07eb633c206eebc22d8de32ace98704d012c9aede7d0953788ae7965d5d4d14acec",
          "sha256": "51a24f4ffc6e2f0f0a1fe6b82c9e49fb9905c13437846ecc89f301e71d2051c8",
          "sha1": "eaf916beacdadcf8426c94cbf7b553133e4dd9d3",
          "md5": "252d7f04d172b1870f273e36fd07f28c"
        }
      ]
    }
  ]
}
