{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.71.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.71.0.aar",
          "url": "mlkit-scanner-engine-0.71.0.aar",
          "size": 64266,
          "sha512": "1c271812ac0199130ba25cb29b4f8eae5f2c9a65dac5d6bab2f17cd41cfb64142ad428fbaadb4c3eecb43bde5a6371b4c54ecddbc53f616f9f74c2c1d6572418",
          "sha256": "59ce6f04830513cb76f8422c6547fa40e8bd38ca90b7c682c2163d3b794c6eda",
          "sha1": "4067f7349a721150e148428237c6b488a4cdbeed",
          "md5": "d91e99324be7c3f4f233c1eb8b6c74be"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.71.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.71.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.71.0.aar",
          "url": "mlkit-scanner-engine-0.71.0.aar",
          "size": 64266,
          "sha512": "1c271812ac0199130ba25cb29b4f8eae5f2c9a65dac5d6bab2f17cd41cfb64142ad428fbaadb4c3eecb43bde5a6371b4c54ecddbc53f616f9f74c2c1d6572418",
          "sha256": "59ce6f04830513cb76f8422c6547fa40e8bd38ca90b7c682c2163d3b794c6eda",
          "sha1": "4067f7349a721150e148428237c6b488a4cdbeed",
          "md5": "d91e99324be7c3f4f233c1eb8b6c74be"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.71.0-sources.jar",
          "url": "mlkit-scanner-engine-0.71.0-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
