{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.71.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.6.aar",
          "url": "core-0.71.6.aar",
          "size": 591524,
          "sha512": "e076ffcc99280382392359bb57baa5e895c2d6d09fa158f81a672fd06e654ec858b2e2a861c8e6fad1499f9f7db8e7d0bb3a525b9302b0fb8686adfea6d89b68",
          "sha256": "39c57a41fb7405d81be2ce8baff1072cce5fa537c36444253def1097f17d76c1",
          "sha1": "3301edef16bb0fc356cface813ae1c4e9813f8b3",
          "md5": "c3bcc81ba6d24c4001f0f40c8ddf5a3c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.6.aar",
          "url": "core-0.71.6.aar",
          "size": 591524,
          "sha512": "e076ffcc99280382392359bb57baa5e895c2d6d09fa158f81a672fd06e654ec858b2e2a861c8e6fad1499f9f7db8e7d0bb3a525b9302b0fb8686adfea6d89b68",
          "sha256": "39c57a41fb7405d81be2ce8baff1072cce5fa537c36444253def1097f17d76c1",
          "sha1": "3301edef16bb0fc356cface813ae1c4e9813f8b3",
          "md5": "c3bcc81ba6d24c4001f0f40c8ddf5a3c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.71.6-sources.jar",
          "url": "core-0.71.6-sources.jar",
          "size": 327593,
          "sha512": "cde1046288abcd387a1d965dfe9b19932c79376be2626342cbd241ad35e3515710781b3ef1678142e2ff6ef75433ddcfad6fddecff76a50b179729eeee16e787",
          "sha256": "5ab1cb700d5bbaf42b1b89dbceac621adc610ca72415e8c1529cb93616e87021",
          "sha1": "78c207eb74378291c294f372e8bd8bf44a3fa4aa",
          "md5": "15d79ca70395269a67833cb6d7ea4267"
        }
      ]
    }
  ]
}
