{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "V0.81.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-V0.81.1.aar",
          "url": "accessibility-toolbox-V0.81.1.aar",
          "size": 24596,
          "sha512": "db98368bc00e3b826028bbad7f090c7938fae66e18bd13cbf3a2791fe40330fcfedebaac3cbf15c31fb43ea217953e67b9d7421162db053ac69db6e784b958be",
          "sha256": "a2467de09bc6317926b6e5ef3489390102188f7b5aa758492951e31e17332833",
          "sha1": "ec1376c6e695caff8ecca9e59304aef7e7bffa02",
          "md5": "3afd35a7d6581939d4cbf45f11927a5e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "V0.81.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-V0.81.1.aar",
          "url": "accessibility-toolbox-V0.81.1.aar",
          "size": 24596,
          "sha512": "db98368bc00e3b826028bbad7f090c7938fae66e18bd13cbf3a2791fe40330fcfedebaac3cbf15c31fb43ea217953e67b9d7421162db053ac69db6e784b958be",
          "sha256": "a2467de09bc6317926b6e5ef3489390102188f7b5aa758492951e31e17332833",
          "sha1": "ec1376c6e695caff8ecca9e59304aef7e7bffa02",
          "md5": "3afd35a7d6581939d4cbf45f11927a5e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "accessibility-toolbox-V0.81.1-sources.jar",
          "url": "accessibility-toolbox-V0.81.1-sources.jar",
          "size": 10295,
          "sha512": "5cd29f4679905852d3b741cab239637196dccba323905c9fe947558f3a8e62bd0b26a00d2d2bb061b568f3faff12727b6c27c32d970552f771c22982f80e67c7",
          "sha256": "26c23b54c32a953d82ff453d1871c552d9ecf3928458ebfaf3991c5f5c9692fd",
          "sha1": "e16662017954d97e50f42be15de5f88d1b3a235a",
          "md5": "f430e93992df8383536f3605cfca7c82"
        }
      ]
    }
  ]
}
