{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.74.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.74.2.aar",
          "url": "utils-0.74.2.aar",
          "size": 58379,
          "sha512": "d0ab539cfce17a1e169d51924ddebb83ffda9dde40158f630610d2977c22c5843b63ecfca83a439415d751923b1d19616a4515be840da8d8977fcdc61b40ce3b",
          "sha256": "13399e7cd5379c6b3f8ac3ceb645b6c5e9b890f26d1a7469f268f4475665a7f2",
          "sha1": "6b737be63efc57dc077f1b3442d4a7f551056e67",
          "md5": "87e9a6971fed52e43f4352eb25123003"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.74.2.aar",
          "url": "utils-0.74.2.aar",
          "size": 58379,
          "sha512": "d0ab539cfce17a1e169d51924ddebb83ffda9dde40158f630610d2977c22c5843b63ecfca83a439415d751923b1d19616a4515be840da8d8977fcdc61b40ce3b",
          "sha256": "13399e7cd5379c6b3f8ac3ceb645b6c5e9b890f26d1a7469f268f4475665a7f2",
          "sha1": "6b737be63efc57dc077f1b3442d4a7f551056e67",
          "md5": "87e9a6971fed52e43f4352eb25123003"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.74.2-sources.jar",
          "url": "utils-0.74.2-sources.jar",
          "size": 45527,
          "sha512": "6323429672ff5f66b6109c16210fcf4d10e84648a2a1aad592b451930d9780e769bf76842b54dd61a20ed081c426f77053677e27ba3c76a2d94f9e2f52d89492",
          "sha256": "4f8d42603fa2159b6ccafbe6782e5ffa766ed656bcac3d65cc40c354df11cc34",
          "sha1": "19e41563e77d2e27391471ade0f4d2d27dc18985",
          "md5": "bbf2a45207b95b7a785c85e06e385660"
        }
      ]
    }
  ]
}
