{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.33.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dax35mg2nreplfqoglg2jm2bzu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.2.aar",
          "url": "firebase-detector-0.33.2.aar",
          "size": 33046,
          "sha512": "2d72b6255e82f90ddddd35762dd673bc9bc8cdbf1188c6b0104b1d9e30b7f6856efb1c28f7d63be82e1d581a026892cc21e55c8491377205d88097bd0f371703",
          "sha256": "2bbd7e1ef7e00e82448bc05b4d4d7eb72d41b47f59e0afe152d0cc940a176c1c",
          "sha1": "dbed178c3b43c8b639b3825c59f739000a653b6e",
          "md5": "c16458c544b9b1948224d73997483650"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.2.aar",
          "url": "firebase-detector-0.33.2.aar",
          "size": 33046,
          "sha512": "2d72b6255e82f90ddddd35762dd673bc9bc8cdbf1188c6b0104b1d9e30b7f6856efb1c28f7d63be82e1d581a026892cc21e55c8491377205d88097bd0f371703",
          "sha256": "2bbd7e1ef7e00e82448bc05b4d4d7eb72d41b47f59e0afe152d0cc940a176c1c",
          "sha1": "dbed178c3b43c8b639b3825c59f739000a653b6e",
          "md5": "c16458c544b9b1948224d73997483650"
        }
      ]
    }
  ]
}
