{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.71.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.8.aar",
          "url": "core-0.71.8.aar",
          "size": 591702,
          "sha512": "1d936d2a7b0918897259b490d3427ca969db41a46ac0e114cfb0fbd06f3a1890764fd4bb5d4db60a3dbd74fd52d33922b530291f963d5c9e94f126b92e71bd26",
          "sha256": "54a46b0e5091d3e06203b8c1d51605ff6bbd5d03022de606a6423dd1152c3c3b",
          "sha1": "1d978553197b42df0059cf85ce980c2155e1b80e",
          "md5": "1664d8ceeb2d44d2873461e6da964bf9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.8.aar",
          "url": "core-0.71.8.aar",
          "size": 591702,
          "sha512": "1d936d2a7b0918897259b490d3427ca969db41a46ac0e114cfb0fbd06f3a1890764fd4bb5d4db60a3dbd74fd52d33922b530291f963d5c9e94f126b92e71bd26",
          "sha256": "54a46b0e5091d3e06203b8c1d51605ff6bbd5d03022de606a6423dd1152c3c3b",
          "sha1": "1d978553197b42df0059cf85ce980c2155e1b80e",
          "md5": "1664d8ceeb2d44d2873461e6da964bf9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.71.8-sources.jar",
          "url": "core-0.71.8-sources.jar",
          "size": 327703,
          "sha512": "c34b15dcbacf8a42bb1f7979b0cdec25e0a15af486ea9cd860494e211baae5a61289beb40908eabce69a1334ce8faa650915bf6977d1910fb4c99452559897f6",
          "sha256": "d7c3f03ffa91d7e0c4c781447deb2fe950d8e4dccd032147368c364f8d863055",
          "sha1": "2913b26151ad86e8c926d7706228e7cc1a9946c7",
          "md5": "0a62177d8848257c842d12ccb6f5480c"
        }
      ]
    }
  ]
}
