{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.34.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "d2aydc6bnva3djtvmpm7benw5m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.0.aar",
          "url": "core-0.34.0.aar",
          "size": 330129,
          "sha512": "b9657fb2726f4d625b763fd1b04b67aa3f90ee391721b8effbd674b70417aa272364afa2ac030ca45ce07155853c9f4e0f65ea498e5d38752689a967725d34c7",
          "sha256": "844dd6b03e34e36f773643faa798d2f1e99b1b28389761e4d9a84b584a959f5a",
          "sha1": "d2d31623a2dfa444466715187f2a474fe7f4512d",
          "md5": "b459baf3558ff3cb5afc4af6afbbd9b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.0.aar",
          "url": "core-0.34.0.aar",
          "size": 330129,
          "sha512": "b9657fb2726f4d625b763fd1b04b67aa3f90ee391721b8effbd674b70417aa272364afa2ac030ca45ce07155853c9f4e0f65ea498e5d38752689a967725d34c7",
          "sha256": "844dd6b03e34e36f773643faa798d2f1e99b1b28389761e4d9a84b584a959f5a",
          "sha1": "d2d31623a2dfa444466715187f2a474fe7f4512d",
          "md5": "b459baf3558ff3cb5afc4af6afbbd9b2"
        }
      ]
    }
  ]
}
