{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.pay",
    "module": "mandate",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "mandate-1.0.0.aar",
          "url": "mandate-1.0.0.aar",
          "size": 52138,
          "sha512": "aa02b725e2c48a41a682b243d3e071ea0d4c97633c9369c7cca1d075133aab28b35c376e88553daaa1b1a2b2a6c8db5dae4d070fc47a6649852cc942dccc0321",
          "sha256": "4439dbed3df3fc9ebea02b60ca2657cb7ae2de30880f1b2352175635345fedd5",
          "sha1": "46021d1d5fd5f8b4a5eaf6db582ff0cb29c74777",
          "md5": "0ad360c230762b4b6272de9e416fb52c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.pay",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "mandate-1.0.0.aar",
          "url": "mandate-1.0.0.aar",
          "size": 52138,
          "sha512": "aa02b725e2c48a41a682b243d3e071ea0d4c97633c9369c7cca1d075133aab28b35c376e88553daaa1b1a2b2a6c8db5dae4d070fc47a6649852cc942dccc0321",
          "sha256": "4439dbed3df3fc9ebea02b60ca2657cb7ae2de30880f1b2352175635345fedd5",
          "sha1": "46021d1d5fd5f8b4a5eaf6db582ff0cb29c74777",
          "md5": "0ad360c230762b4b6272de9e416fb52c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mandate-1.0.0-sources.jar",
          "url": "mandate-1.0.0-sources.jar",
          "size": 8917,
          "sha512": "ea8ec6f3d8463a3a6b2a5553a88a990f82dd06803e291a70df4173a5520f1658336f95a1227aa2122c4bc754434ad9c76a9d8ed3fb7406cbb54388daddbf64ec",
          "sha256": "0b952c61b162d04b5a204f598ffd4bc8b085c7197b4bc8221cc4efff8770ae32",
          "sha1": "e7ee90d977aacd028227c9a64e894ca7111ec69f",
          "md5": "47159b06041e4383ca72331d3170189c"
        }
      ]
    }
  ]
}
