{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.78.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.78.0.aar",
          "url": "core-0.78.0.aar",
          "size": 643356,
          "sha512": "a384a193dfbd86e25e8750af45be73b47f8bb54c1792022762ee51fab1ffadc01708c58963e2c8020cf6df7dcc595baf60f0f7df679c2da6f6d7354664d86dee",
          "sha256": "f2f01629a0d9e620b05f6dbb3c2dc08278762ae3243388c4f64c988cbee01b72",
          "sha1": "55acac5b5388a81ed821d49be8c6d9290d190bfb",
          "md5": "8f3e77b2ff643d4c4e43a995f30546f3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.78.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.78.0.aar",
          "url": "core-0.78.0.aar",
          "size": 643356,
          "sha512": "a384a193dfbd86e25e8750af45be73b47f8bb54c1792022762ee51fab1ffadc01708c58963e2c8020cf6df7dcc595baf60f0f7df679c2da6f6d7354664d86dee",
          "sha256": "f2f01629a0d9e620b05f6dbb3c2dc08278762ae3243388c4f64c988cbee01b72",
          "sha1": "55acac5b5388a81ed821d49be8c6d9290d190bfb",
          "md5": "8f3e77b2ff643d4c4e43a995f30546f3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.78.0-sources.jar",
          "url": "core-0.78.0-sources.jar",
          "size": 347205,
          "sha512": "64b1b1a392d64f52d752a8f178132355c1acec5ac499ee6391adaef0d60d6c942ec825fb5305d50e854d87f0c57e20509bbee4b92291b968059f6d9d525b39b6",
          "sha256": "ff979765c8cd9943bb82a074c31b665d16020812cd1acccb576f58fe3acc6cb2",
          "sha1": "3faefcdd7b2363089c278eb9f8ed34da49f9785b",
          "md5": "561837b3293043fae2de67014d44582f"
        }
      ]
    }
  ]
}
