{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.4.aar",
          "url": "core-0.80.4.aar",
          "size": 668603,
          "sha512": "bf843dbd57043c2711783a851bc178161054e543eced48465db4e40b4e52842dd4a7cee71c3e8578f1f8fddb6fb6fd7c8adf5f7dd33ce9335f2d2c47cf9453b8",
          "sha256": "8fa008c35ee3c1f4f0e35d1b3383d10f977eabecb80d38ddde27b90e5222c6fa",
          "sha1": "8f2565af767bf2aaaaaa2ba5f4ffd44313ff5609",
          "md5": "58fe01237c1ee85732a8361e83965707"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.4.aar",
          "url": "core-0.80.4.aar",
          "size": 668603,
          "sha512": "bf843dbd57043c2711783a851bc178161054e543eced48465db4e40b4e52842dd4a7cee71c3e8578f1f8fddb6fb6fd7c8adf5f7dd33ce9335f2d2c47cf9453b8",
          "sha256": "8fa008c35ee3c1f4f0e35d1b3383d10f977eabecb80d38ddde27b90e5222c6fa",
          "sha1": "8f2565af767bf2aaaaaa2ba5f4ffd44313ff5609",
          "md5": "58fe01237c1ee85732a8361e83965707"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.4-sources.jar",
          "url": "core-0.80.4-sources.jar",
          "size": 352183,
          "sha512": "c0fb50c386cfe08d07b738bd07f791523fb01323d8ff3b31030f87226d0f910c29e4f9c49dafee9ef5f56f7cb91027dba76bbcb0467b7dec65d34d65a647832d",
          "sha256": "d5542ede0d5b552b535c1edb7df75127ebcadb67fdd7c81e23b879191528cb51",
          "sha1": "7a06ae0bfa68e27ca32079637a9274aa78580e63",
          "md5": "38f5d1f0b2228a499347cef770728202"
        }
      ]
    }
  ]
}
