{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r5jlfxzouzffviprjrzm3wrs74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.0-beta03.aar",
          "url": "utils-0.33.0-beta03.aar",
          "size": 42949,
          "sha512": "24e75f26eeacb9862316f45d65fd4528660de466dd61701f1881121659945e5e4ad95ae442684902fb526e69c9ede1e916aad2e1b320410236d98e7c4c161a1c",
          "sha256": "0604e4bcca9a4dc4f61c503be4eee68ff775c2d79f0a7dad709e320bf82a82f3",
          "sha1": "2fe8465eaf0322b74e2c8a27f7624c8dafb3b647",
          "md5": "db36e15a649da907a1aba999aefd2605"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.0-beta03.aar",
          "url": "utils-0.33.0-beta03.aar",
          "size": 42949,
          "sha512": "24e75f26eeacb9862316f45d65fd4528660de466dd61701f1881121659945e5e4ad95ae442684902fb526e69c9ede1e916aad2e1b320410236d98e7c4c161a1c",
          "sha256": "0604e4bcca9a4dc4f61c503be4eee68ff775c2d79f0a7dad709e320bf82a82f3",
          "sha1": "2fe8465eaf0322b74e2c8a27f7624c8dafb3b647",
          "md5": "db36e15a649da907a1aba999aefd2605"
        }
      ]
    }
  ]
}
