{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qvpcucnmzrb4lhoa6wtow3rtda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.2.aar",
          "url": "ui-0.25.2.aar",
          "size": 827612,
          "sha512": "21909e8f29b25a4dccaa0d7910011e0ad4ab657d4e9befb0afd9a0594cddc4c217f875e3dd6a22a408e019f1c4f5bf52258e81a051da959a4d84511185e24338",
          "sha256": "db805e5b8152634800aefa1968ea5f0231628eb87b1453bcda251c1f02a01611",
          "sha1": "de53e187eae8596cf9ccb9bf9c0776a45ad9b1d8",
          "md5": "1c8f7a09710f799a8a8edd3111080bfe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.2.aar",
          "url": "ui-0.25.2.aar",
          "size": 827612,
          "sha512": "21909e8f29b25a4dccaa0d7910011e0ad4ab657d4e9befb0afd9a0594cddc4c217f875e3dd6a22a408e019f1c4f5bf52258e81a051da959a4d84511185e24338",
          "sha256": "db805e5b8152634800aefa1968ea5f0231628eb87b1453bcda251c1f02a01611",
          "sha1": "de53e187eae8596cf9ccb9bf9c0776a45ad9b1d8",
          "md5": "1c8f7a09710f799a8a8edd3111080bfe"
        }
      ]
    }
  ]
}
