{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.31.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jzpu23fbyrgxji2shb5gg6dx6m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.31.3.aar",
          "url": "core-0.31.3.aar",
          "size": 325596,
          "sha512": "55bc7309d26f7f9ba4eeb25b6411a5efa98e11af4c04c940cf43863466afc370aeb0c887e38c058c9b515681e7b6204a57e9bd7694d86a3259b9357ae20e5029",
          "sha256": "976be2a5009c3b86ad2a502eb4bfba711b3ac45e59db36ffbca0d9d18d4d1729",
          "sha1": "91e8ad0c8fdefbbabdb24598fa919c50dd23bcf0",
          "md5": "90ffeeb513f3715396e166ffc2d9b036"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.31.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.31.3.aar",
          "url": "core-0.31.3.aar",
          "size": 325596,
          "sha512": "55bc7309d26f7f9ba4eeb25b6411a5efa98e11af4c04c940cf43863466afc370aeb0c887e38c058c9b515681e7b6204a57e9bd7694d86a3259b9357ae20e5029",
          "sha256": "976be2a5009c3b86ad2a502eb4bfba711b3ac45e59db36ffbca0d9d18d4d1729",
          "sha1": "91e8ad0c8fdefbbabdb24598fa919c50dd23bcf0",
          "md5": "90ffeeb513f3715396e166ffc2d9b036"
        }
      ]
    }
  ]
}
