{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.41.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rqmxdke565ctpi3w3fcfcmd3vi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.41.0.aar",
          "url": "core-0.41.0.aar",
          "size": 375643,
          "sha512": "abc2fb51c7f2e3ead52df0f2dcb1a7ec5b5b96f89def25fb6c7226b9f3e96cb30b639708a56c098ad9d70c1eaa6b19a8f2e31e4a3405fd94d4f5350082299427",
          "sha256": "56d5f25026bdbb49184d0cbaa652c4d2cc5a3f1a8b7637e742983dcb054b09f6",
          "sha1": "736d0603745aad03c0e01b6a6210ea5933ed13c8",
          "md5": "3a75496cdd830b6a55bcacf9291980ff"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.41.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.41.0.aar",
          "url": "core-0.41.0.aar",
          "size": 375643,
          "sha512": "abc2fb51c7f2e3ead52df0f2dcb1a7ec5b5b96f89def25fb6c7226b9f3e96cb30b639708a56c098ad9d70c1eaa6b19a8f2e31e4a3405fd94d4f5350082299427",
          "sha256": "56d5f25026bdbb49184d0cbaa652c4d2cc5a3f1a8b7637e742983dcb054b09f6",
          "sha1": "736d0603745aad03c0e01b6a6210ea5933ed13c8",
          "md5": "3a75496cdd830b6a55bcacf9291980ff"
        }
      ]
    }
  ]
}
