{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-toolkit",
    "version": "0.82.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-toolkit-0.82.6.aar",
          "url": "ui-toolkit-0.82.6.aar",
          "size": 1980696,
          "sha512": "0aa494dbfc108b238fe58c4124a4d1c77853f931512762968f36ccb9bfddeaaa541f7171e68bd7cc278d49eaed01d0981feb77733d4353af023510f55f8da13b",
          "sha256": "2cca994dd2d880cbef8a1a21ae873843510ddec66a32af41f319ff9779b29f57",
          "sha1": "0c49f5aed623d91573b5a1f46bc2b083562614b8",
          "md5": "6292954143d5f49aa78191a895edb46b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "accessibility-toolbox",
          "version": {
            "requires": "0.82.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.82.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "io.github.sebaslogen",
          "module": "resaca",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-material3",
          "version": {
            "requires": "0.36.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-toolkit-0.82.6.aar",
          "url": "ui-toolkit-0.82.6.aar",
          "size": 1980696,
          "sha512": "0aa494dbfc108b238fe58c4124a4d1c77853f931512762968f36ccb9bfddeaaa541f7171e68bd7cc278d49eaed01d0981feb77733d4353af023510f55f8da13b",
          "sha256": "2cca994dd2d880cbef8a1a21ae873843510ddec66a32af41f319ff9779b29f57",
          "sha1": "0c49f5aed623d91573b5a1f46bc2b083562614b8",
          "md5": "6292954143d5f49aa78191a895edb46b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-toolkit-0.82.6-sources.jar",
          "url": "ui-toolkit-0.82.6-sources.jar",
          "size": 671232,
          "sha512": "fcb714bf40a27e5c77162c104d70a4d0332834231fc312e53cd407760a036a5fe8354ba8fe89766a8c8979df87024dc56833069aa1cdcdf775039d21d97b093c",
          "sha256": "69faeb4a878b555d8f724cd11c9f95cba00e84ebfff651135ed86d0b37479dee",
          "sha1": "e9b08ea8ced9c1576a796d335c2aecd6134c18c9",
          "md5": "bf38a9827cdd9caf05afd7d1b2b60a14"
        }
      ]
    }
  ]
}
