{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.5.aar",
          "url": "core-0.75.5.aar",
          "size": 638553,
          "sha512": "5bc53cba03cb34eb440f426152b33aa96d4b504fa5cb13ba645ccf75c73f75ea2de85e2bd58d5f36c9d04845a620ce2f29ee3fe89fcd0025da62670ef278eaa4",
          "sha256": "338aca04a6fe4323fa79234b8b737a11047988f2ddc39f1980e01b858dd22bcb",
          "sha1": "981afd0a0fa612970fe242371c102ec226de7148",
          "md5": "6f1c31e47c11cc2fa8473964c4891ded"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.5.aar",
          "url": "core-0.75.5.aar",
          "size": 638553,
          "sha512": "5bc53cba03cb34eb440f426152b33aa96d4b504fa5cb13ba645ccf75c73f75ea2de85e2bd58d5f36c9d04845a620ce2f29ee3fe89fcd0025da62670ef278eaa4",
          "sha256": "338aca04a6fe4323fa79234b8b737a11047988f2ddc39f1980e01b858dd22bcb",
          "sha1": "981afd0a0fa612970fe242371c102ec226de7148",
          "md5": "6f1c31e47c11cc2fa8473964c4891ded"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.5-sources.jar",
          "url": "core-0.75.5-sources.jar",
          "size": 343903,
          "sha512": "4642dcaf373866a6cdafcebf4ac6ee9e1889b010182ac7e5c73ad74b40870f3acb7c9f0eda2a8cebbad10534c0be16b1dc5b0177ff417decd1bac5dca620169b",
          "sha256": "4916d1457428e2671448592616f75c1e4e174addb66cb9ef4baa361d32ca5838",
          "sha1": "bbd683d5290084be7346aa3d37195427effce94d",
          "md5": "34a39b42dd552098a929f39f9cf5149a"
        }
      ]
    }
  ]
}
