{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.25.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rkljdfyjprg7dfj4iu6ixfix24"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.25.7.aar",
          "url": "utils-0.25.7.aar",
          "size": 39922,
          "sha512": "f6c234f2da580738186b1e9dae1fd4bdf0d549a6411ec6131460f776a7e40a538a75fffed749dcd4c240ee44772d59e2d084756f8efd34f370c7a774c1e6f815",
          "sha256": "bb9417e206e6da7997e4677d8c55d9f8f9ea88d109019669caaf250bd6af87b2",
          "sha1": "49ad6ab40715bee4407c46366c75fedba63a8d23",
          "md5": "d2a964ea74f2830f3c1812539611748d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.25.7.aar",
          "url": "utils-0.25.7.aar",
          "size": 39922,
          "sha512": "f6c234f2da580738186b1e9dae1fd4bdf0d549a6411ec6131460f776a7e40a538a75fffed749dcd4c240ee44772d59e2d084756f8efd34f370c7a774c1e6f815",
          "sha256": "bb9417e206e6da7997e4677d8c55d9f8f9ea88d109019669caaf250bd6af87b2",
          "sha1": "49ad6ab40715bee4407c46366c75fedba63a8d23",
          "md5": "d2a964ea74f2830f3c1812539611748d"
        }
      ]
    }
  ]
}
