{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.37.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gicizk74jvdfraga2c3626opse"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.37.12.aar",
          "url": "utils-0.37.12.aar",
          "size": 44007,
          "sha512": "db835f0af1350f1f975c17f4949af757d32cb2832f9ef258dc74c3584ec431e676ebe83fd53bcca6dd56640e869e45b56fc5e1c3cae2dbf16254596298c5f14a",
          "sha256": "7a1cf684023db4f1a75849ad0a240f43d02e1db0f168a14f19f5d6abeefd052c",
          "sha1": "87b43c97f6b88688abdabefddcce3f1a659b3e0a",
          "md5": "5a300967db57da10362780eee03bf19f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.37.12.aar",
          "url": "utils-0.37.12.aar",
          "size": 44007,
          "sha512": "db835f0af1350f1f975c17f4949af757d32cb2832f9ef258dc74c3584ec431e676ebe83fd53bcca6dd56640e869e45b56fc5e1c3cae2dbf16254596298c5f14a",
          "sha256": "7a1cf684023db4f1a75849ad0a240f43d02e1db0f168a14f19f5d6abeefd052c",
          "sha1": "87b43c97f6b88688abdabefddcce3f1a659b3e0a",
          "md5": "5a300967db57da10362780eee03bf19f"
        }
      ]
    }
  ]
}
