{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r3ppg4lgpfbpngvcbn4c6acnme"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.3.aar",
          "url": "ui-0.25.3.aar",
          "size": 827602,
          "sha512": "f33a9a62d9608df837ffed1661dba66900b0ccd71f703fa9508af1690c8ad30c575070d48e55296a01c13b66cc47c8da41fe45251a0e9921f3f3dc307cb51fe9",
          "sha256": "4c66b7a2dff8c2f4884516c3604de4db8f7dd6474847e3aafba7406d5698e6a9",
          "sha1": "371e9d61c26e7d2952479ae920822ff6fc2c577e",
          "md5": "7c1d90df5d3293636523badf72086036"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.3.aar",
          "url": "ui-0.25.3.aar",
          "size": 827602,
          "sha512": "f33a9a62d9608df837ffed1661dba66900b0ccd71f703fa9508af1690c8ad30c575070d48e55296a01c13b66cc47c8da41fe45251a0e9921f3f3dc307cb51fe9",
          "sha256": "4c66b7a2dff8c2f4884516c3604de4db8f7dd6474847e3aafba7406d5698e6a9",
          "sha1": "371e9d61c26e7d2952479ae920822ff6fc2c577e",
          "md5": "7c1d90df5d3293636523badf72086036"
        }
      ]
    }
  ]
}
