{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.38.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bqdx6kdjbzbfflbiktn3pzs4vq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.38.0.aar",
          "url": "core-0.38.0.aar",
          "size": 351357,
          "sha512": "1d9e921f6ba05c4650261e1fe289df9687555c3c58bdb124bb73028df1dceeb3052fd94e154a008c402e077a4bd4305e3b2d04b2e500a1a1925939b3ccde15b4",
          "sha256": "f85ffbea2b6a51060338a76d7fa18ffd57494d80749c07821756658ed21049b2",
          "sha1": "4d28828d9e5bdd99441d15931adbbdd41bf2f955",
          "md5": "ebfbcbba2e96a4b774dbf4fa787a0e80"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.38.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.38.0.aar",
          "url": "core-0.38.0.aar",
          "size": 351357,
          "sha512": "1d9e921f6ba05c4650261e1fe289df9687555c3c58bdb124bb73028df1dceeb3052fd94e154a008c402e077a4bd4305e3b2d04b2e500a1a1925939b3ccde15b4",
          "sha256": "f85ffbea2b6a51060338a76d7fa18ffd57494d80749c07821756658ed21049b2",
          "sha1": "4d28828d9e5bdd99441d15931adbbdd41bf2f955",
          "md5": "ebfbcbba2e96a4b774dbf4fa787a0e80"
        }
      ]
    }
  ]
}
