{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.51.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.51.0.aar",
          "url": "ui-integration-0.51.0.aar",
          "size": 100828,
          "sha512": "1f01a10b574545be88f4f582eeb293c792498b19f6edb833547804f3a48cdacf30aec022386a4fef24b11d569dd9732cf31d5a12e3cfd43b2181fae549da8c4f",
          "sha256": "d5a90ef6e7b1f386d7dcf1c240a8afab41d8d3c458a14e58a053a009a14d7fa4",
          "sha1": "eed595b9127a7b2a722ad994174074b6fcacc57b",
          "md5": "ff99ffa3416b23a673aaafcf1e42c287"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.51.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.51.0.aar",
          "url": "ui-integration-0.51.0.aar",
          "size": 100828,
          "sha512": "1f01a10b574545be88f4f582eeb293c792498b19f6edb833547804f3a48cdacf30aec022386a4fef24b11d569dd9732cf31d5a12e3cfd43b2181fae549da8c4f",
          "sha256": "d5a90ef6e7b1f386d7dcf1c240a8afab41d8d3c458a14e58a053a009a14d7fa4",
          "sha1": "eed595b9127a7b2a722ad994174074b6fcacc57b",
          "md5": "ff99ffa3416b23a673aaafcf1e42c287"
        }
      ]
    }
  ]
}
