{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.34.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7yhoyjuslngstjpslwef5pjkey"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.4-SNAPSHOT.aar",
          "url": "ui-integration-0.34.4-SNAPSHOT.aar",
          "size": 93102,
          "sha512": "dbaeaeb5ab8dc6bec4e17f25260bf26284ee5a2ea382eb4595c9e8759623450af44714aacf37d2f632bda5063e1917b9620b1e1ca5cf78cb52fe8d233f99da6e",
          "sha256": "dedfbbfd0fca65e88746d8b35ef89a45504354615a7f902a90614732ac50dd4f",
          "sha1": "ed3310774cefbe70241922e67cba645f79809ef5",
          "md5": "d9c94fc7ae040bd49088222158cf3ac3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.34.4-SNAPSHOT"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.34.4-SNAPSHOT"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.4-SNAPSHOT"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.4-SNAPSHOT.aar",
          "url": "ui-integration-0.34.4-SNAPSHOT.aar",
          "size": 93102,
          "sha512": "dbaeaeb5ab8dc6bec4e17f25260bf26284ee5a2ea382eb4595c9e8759623450af44714aacf37d2f632bda5063e1917b9620b1e1ca5cf78cb52fe8d233f99da6e",
          "sha256": "dedfbbfd0fca65e88746d8b35ef89a45504354615a7f902a90614732ac50dd4f",
          "sha1": "ed3310774cefbe70241922e67cba645f79809ef5",
          "md5": "d9c94fc7ae040bd49088222158cf3ac3"
        }
      ]
    }
  ]
}
