{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.3.0-alpha01.aar",
          "url": "core-3.3.0-alpha01.aar",
          "size": 170477,
          "sha512": "3b34bd4e9da6d75559daab7c07a584ff66e5826a0d5a86f32527fd1d7203c76db45468377a53f6cdb4dce1883d3040d91affeb5b2728e8db4b9a98bd3e30806e",
          "sha256": "0f3cba3f37be072bad0cb68273c396c92b47a9a2899e7dd8eeeb50d8b34d53da",
          "sha1": "fadd3a45c6272a9fe327c73fe368187f6c3e31b8",
          "md5": "80a67dc8e82ac84a51e90ba82a41ca86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.3.0-alpha01.aar",
          "url": "core-3.3.0-alpha01.aar",
          "size": 170477,
          "sha512": "3b34bd4e9da6d75559daab7c07a584ff66e5826a0d5a86f32527fd1d7203c76db45468377a53f6cdb4dce1883d3040d91affeb5b2728e8db4b9a98bd3e30806e",
          "sha256": "0f3cba3f37be072bad0cb68273c396c92b47a9a2899e7dd8eeeb50d8b34d53da",
          "sha1": "fadd3a45c6272a9fe327c73fe368187f6c3e31b8",
          "md5": "80a67dc8e82ac84a51e90ba82a41ca86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.3.0-alpha01-sources.jar",
          "url": "core-3.3.0-alpha01-sources.jar",
          "size": 29548,
          "sha512": "a98dc659ff38954a60402cabe5a65109b3878b60d8c7919dc5974d7e7a3fef44b8d50abac4e1e150646b53d1ad9a0cf9f2e6ca3c51220bcb0be969f8c0ec49f0",
          "sha256": "29f87accd13ac4bff8da377f6d4ed4b552c4af5d330d2124c21dffce1a3f205f",
          "sha1": "3daf09bae92e6fca0125a761cf37dabbcc9b181e",
          "md5": "c16fdcfb129d780fc8291f266981c7be"
        }
      ]
    }
  ]
}
