{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.29.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "u2shwelgpvbononkksnwr4sgra"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.2.aar",
          "url": "firebase-detector-0.29.2.aar",
          "size": 32729,
          "sha512": "a0c1ed790827f3431e89a6d40597548c3fb78795d168b7c5a0ca3bd2b8937dc646b6ba20b57716cd0af50cc31cf2494aed80d7e8ce92b23a58b8d87b41cfc182",
          "sha256": "b081b8603dd5a1ad5f5cdf78a1fe466b3b121013dd784de1599ab0d705e92ae4",
          "sha1": "b010abef4517fe5b828ab9666dc0018b0ac147cb",
          "md5": "3d4cb9ac998ceca00536d188745bbdc3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.2.aar",
          "url": "firebase-detector-0.29.2.aar",
          "size": 32729,
          "sha512": "a0c1ed790827f3431e89a6d40597548c3fb78795d168b7c5a0ca3bd2b8937dc646b6ba20b57716cd0af50cc31cf2494aed80d7e8ce92b23a58b8d87b41cfc182",
          "sha256": "b081b8603dd5a1ad5f5cdf78a1fe466b3b121013dd784de1599ab0d705e92ae4",
          "sha1": "b010abef4517fe5b828ab9666dc0018b0ac147cb",
          "md5": "3d4cb9ac998ceca00536d188745bbdc3"
        }
      ]
    }
  ]
}
