{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7vry4hwb6rc5fmlc4kftsausae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.0.aar",
          "url": "ui-integration-0.35.0.aar",
          "size": 93089,
          "sha512": "83ce7b129916911a40356c29879cbaf5411eacc5feb86efab87dab2eb3db0a7da1efc2ee00fbffd55095b04766625a737f73c3a744fdcd9f12106fd9125bdcd3",
          "sha256": "aa4ebd22506e86f6de907833abcc4052a9e993719a71f1df3d1c6c922946b247",
          "sha1": "6eff4c7fdb230fc2a91f914b70cde5ea78bfabed",
          "md5": "c849d1fe7ee0b2a2f92f924ddd5461c5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.0.aar",
          "url": "ui-integration-0.35.0.aar",
          "size": 93089,
          "sha512": "83ce7b129916911a40356c29879cbaf5411eacc5feb86efab87dab2eb3db0a7da1efc2ee00fbffd55095b04766625a737f73c3a744fdcd9f12106fd9125bdcd3",
          "sha256": "aa4ebd22506e86f6de907833abcc4052a9e993719a71f1df3d1c6c922946b247",
          "sha1": "6eff4c7fdb230fc2a91f914b70cde5ea78bfabed",
          "md5": "c849d1fe7ee0b2a2f92f924ddd5461c5"
        }
      ]
    }
  ]
}
