{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.25.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r3ppg4lgpfbpngvcbn4c6acnme"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.3.aar",
          "url": "core-0.25.3.aar",
          "size": 272246,
          "sha512": "e0e277a1389eb7de15d6ecdac6b5b1d79927724671694224566444c0db7cc7a81bd3131d97d9934c8470e449f56f5ee562ea4f204db8aa19fa2766eafd8e0bb2",
          "sha256": "4ee45f35c63a43af321e43cc74fc9fcd79d36f05b94af3d8175ed2b532a8afa6",
          "sha1": "a9560803b6dc977353e34107ecd9afdd9f0b43c7",
          "md5": "5d16627c1aa9b486a9ae7689e520b700"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.3.aar",
          "url": "core-0.25.3.aar",
          "size": 272246,
          "sha512": "e0e277a1389eb7de15d6ecdac6b5b1d79927724671694224566444c0db7cc7a81bd3131d97d9934c8470e449f56f5ee562ea4f204db8aa19fa2766eafd8e0bb2",
          "sha256": "4ee45f35c63a43af321e43cc74fc9fcd79d36f05b94af3d8175ed2b532a8afa6",
          "sha1": "a9560803b6dc977353e34107ecd9afdd9f0b43c7",
          "md5": "5d16627c1aa9b486a9ae7689e520b700"
        }
      ]
    }
  ]
}
