{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fnx5gahborfyfotg42y67ktore"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.31.0.aar",
          "url": "ui-integration-0.31.0.aar",
          "size": 74893,
          "sha512": "f4d80feac3e3c16b657e328f2fff80c43319772129856bad56d140a1fb1736e9c855051ea476596af3056eb1177a0b580cded96cd63537709b93a6804cde8d48",
          "sha256": "6d2cdfb7ed0a8653ce8d46f5c71e09c8898a14629594fadb57a4cc06fdf706b2",
          "sha1": "6f5a701ca4c1c6b83b36cbdb9424c51f424bfb1f",
          "md5": "80710c0b422b5ec56784acabc5c62b4d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.31.0.aar",
          "url": "ui-integration-0.31.0.aar",
          "size": 74893,
          "sha512": "f4d80feac3e3c16b657e328f2fff80c43319772129856bad56d140a1fb1736e9c855051ea476596af3056eb1177a0b580cded96cd63537709b93a6804cde8d48",
          "sha256": "6d2cdfb7ed0a8653ce8d46f5c71e09c8898a14629594fadb57a4cc06fdf706b2",
          "sha1": "6f5a701ca4c1c6b83b36cbdb9424c51f424bfb1f",
          "md5": "80710c0b422b5ec56784acabc5c62b4d"
        }
      ]
    }
  ]
}
