{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.72.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.3.aar",
          "url": "mlkit-scanner-engine-0.72.3.aar",
          "size": 63913,
          "sha512": "c0c44426f948da27e416315e213a6638d424d5833e7ff72453bf64e6a116134cdb5e0eed3dedc6e00fb9d0806042e6272afeca8ca06d9273241369ce39c6b1e7",
          "sha256": "944274bb2d7cd66b8c5ded4afdc150e60cd43b779be3966afeb2cf27a14239c5",
          "sha1": "f262865ca47151cf3a49114cb8d1be28b41bb768",
          "md5": "c61c767a428a4b06fb664af62a866410"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.72.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.72.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.3.aar",
          "url": "mlkit-scanner-engine-0.72.3.aar",
          "size": 63913,
          "sha512": "c0c44426f948da27e416315e213a6638d424d5833e7ff72453bf64e6a116134cdb5e0eed3dedc6e00fb9d0806042e6272afeca8ca06d9273241369ce39c6b1e7",
          "sha256": "944274bb2d7cd66b8c5ded4afdc150e60cd43b779be3966afeb2cf27a14239c5",
          "sha1": "f262865ca47151cf3a49114cb8d1be28b41bb768",
          "md5": "c61c767a428a4b06fb664af62a866410"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.3-sources.jar",
          "url": "mlkit-scanner-engine-0.72.3-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
