{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.69.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.69.1.aar",
          "url": "core-0.69.1.aar",
          "size": 545694,
          "sha512": "2f91a9f88f368e52d53621edcb1b65acff9c8dabf75993c0da1706a18498f4e091f90da2e753ca3d9cbe0b5231a6b72a261542f8e861c77ec120086786f37c54",
          "sha256": "4d66b8c59eaef95e8f378115db358e94f81dfddb7ec8564050212d469da88df3",
          "sha1": "4ffd8f2af708f71de2e06b6745a9ed7ed33d017a",
          "md5": "eb054f4e3f33354d4c699309934614bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.69.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.69.1.aar",
          "url": "core-0.69.1.aar",
          "size": 545694,
          "sha512": "2f91a9f88f368e52d53621edcb1b65acff9c8dabf75993c0da1706a18498f4e091f90da2e753ca3d9cbe0b5231a6b72a261542f8e861c77ec120086786f37c54",
          "sha256": "4d66b8c59eaef95e8f378115db358e94f81dfddb7ec8564050212d469da88df3",
          "sha1": "4ffd8f2af708f71de2e06b6745a9ed7ed33d017a",
          "md5": "eb054f4e3f33354d4c699309934614bf"
        }
      ]
    }
  ]
}
