{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.network",
    "module": "core",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "api",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha2.jar",
          "url": "core-1.0.0-alpha2.jar",
          "size": 126247,
          "sha512": "c9aef1ff39a9a3efd95ec9bae415673fb28bd51fe95e04a2c2af42ed8bc9c1dc9ce146e4752048a708cf2206ea2313feaa6fcfabff71da275aa1f55ccd52a58d",
          "sha256": "a9685763b795058909592ab86023d21586f2ce90e1656502f93d59592b7642d0",
          "sha1": "2bdfff64d4b5333ad72d237a10b8c735d0d3dae5",
          "md5": "5c3ebe2587be5fb790a8353bb0f57494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "result",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.snabble.network",
          "module": "api",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha2.jar",
          "url": "core-1.0.0-alpha2.jar",
          "size": 126247,
          "sha512": "c9aef1ff39a9a3efd95ec9bae415673fb28bd51fe95e04a2c2af42ed8bc9c1dc9ce146e4752048a708cf2206ea2313feaa6fcfabff71da275aa1f55ccd52a58d",
          "sha256": "a9685763b795058909592ab86023d21586f2ce90e1656502f93d59592b7642d0",
          "sha1": "2bdfff64d4b5333ad72d237a10b8c735d0d3dae5",
          "md5": "5c3ebe2587be5fb790a8353bb0f57494"
        }
      ]
    }
  ]
}
