{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.pay",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.snabble.pay",
          "module": "account",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "customerinfo",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "mandate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "session",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "shared",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 127760,
          "sha512": "1d711c6e9d663038a9aa9b04d28bbf647dcc2c5c0bafd6d83add2ae4f82e6f1f2fca0f9b8c4473bc9b73600b26168cbbc4be20c6b4201d9bd984547624ebe810",
          "sha256": "2abaabc3a23f7b29da28574609ee47f6e2e8cfa0e52674892a342f4a512e4c66",
          "sha1": "8e9baa1790d106953494fcde826b0ad2a096099e",
          "md5": "91a41ce0e3511955f619f000a7dad55c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.pay",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "account",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "customerinfo",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "mandate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "session",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "shared",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 127760,
          "sha512": "1d711c6e9d663038a9aa9b04d28bbf647dcc2c5c0bafd6d83add2ae4f82e6f1f2fca0f9b8c4473bc9b73600b26168cbbc4be20c6b4201d9bd984547624ebe810",
          "sha256": "2abaabc3a23f7b29da28574609ee47f6e2e8cfa0e52674892a342f4a512e4c66",
          "sha1": "8e9baa1790d106953494fcde826b0ad2a096099e",
          "md5": "91a41ce0e3511955f619f000a7dad55c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-1.0.0-sources.jar",
          "url": "sdk-1.0.0-sources.jar",
          "size": 24975,
          "sha512": "6d6496ba212ed07a7fc0d721a0ffe97a78b21ea516f08883f1909e7e60c89b2df421a4188a8e8d1ecaa9b030f4efa2c41a6b3bc33ed6430cbdcadbffa3202dad",
          "sha256": "f7de7e113baec4febfe2e1bb3f7ac2c1c3db58d890dd41031d42ee8d9ff9ff20",
          "sha1": "033a8bdb6d794f269f393196ef8e861dabf959d2",
          "md5": "10d871379c0f09ce90bf1183f5893be5"
        }
      ]
    }
  ]
}
