{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.77.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.77.0.aar",
          "url": "core-0.77.0.aar",
          "size": 641686,
          "sha512": "0ab816f9ab0efe18d5683a895708ca49a5b9fbc3f65004d4ef5a32e7e76f29599d1768052d3ded2329b8d52550952ee994ec27273ce6b42805e13233e17d5171",
          "sha256": "5a6e38fe5ba7808b8446e722d1f5e7d15a3e62da64d3bf0970e45f36fdd5a882",
          "sha1": "2d7be35790ec85640a56475a53b462e26117ea80",
          "md5": "81b5d9b42984ea3387acd71c7d9e706f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.77.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.77.0.aar",
          "url": "core-0.77.0.aar",
          "size": 641686,
          "sha512": "0ab816f9ab0efe18d5683a895708ca49a5b9fbc3f65004d4ef5a32e7e76f29599d1768052d3ded2329b8d52550952ee994ec27273ce6b42805e13233e17d5171",
          "sha256": "5a6e38fe5ba7808b8446e722d1f5e7d15a3e62da64d3bf0970e45f36fdd5a882",
          "sha1": "2d7be35790ec85640a56475a53b462e26117ea80",
          "md5": "81b5d9b42984ea3387acd71c7d9e706f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.77.0-sources.jar",
          "url": "core-0.77.0-sources.jar",
          "size": 347089,
          "sha512": "d02f70cbb831bda1fba3698d1efb5b884a8c3b49eeb4cf02e87461fca802bfa64d149c1f44c25fdfde4cb644fdc64a617ff1ec184e7282be9393b698569a821b",
          "sha256": "ce4a1ca3e73326b1c23bd6932b3be038161e62e5e6cb52983087a577c125c11e",
          "sha1": "4effbd7375ddd2c2aea385d73c08b64b325aca8b",
          "md5": "58f1b794360b3063866a981eecfd8779"
        }
      ]
    }
  ]
}
