{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.69.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.6.aar",
          "url": "utils-0.69.6.aar",
          "size": 55123,
          "sha512": "58b28eddfbfa38fa7b51a1e69656480559cbb4d00d96b239eca002a62e7feef0113799583fabf45b458b93c99be876bdacd789c5c9840f76158b94030155af1a",
          "sha256": "b08039973be0f06e7439a8dadc066df7b794fe58d3927dd6c3a4160a0db62136",
          "sha1": "1fd299cd5e3365efd80766c4974200bad3011cbe",
          "md5": "7fcba2c4bde8e1079ffc698591d5911c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.6.aar",
          "url": "utils-0.69.6.aar",
          "size": 55123,
          "sha512": "58b28eddfbfa38fa7b51a1e69656480559cbb4d00d96b239eca002a62e7feef0113799583fabf45b458b93c99be876bdacd789c5c9840f76158b94030155af1a",
          "sha256": "b08039973be0f06e7439a8dadc066df7b794fe58d3927dd6c3a4160a0db62136",
          "sha1": "1fd299cd5e3365efd80766c4974200bad3011cbe",
          "md5": "7fcba2c4bde8e1079ffc698591d5911c"
        }
      ]
    }
  ]
}
