{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.33.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tvz5bixklbd4hnyg7hdagz6fhe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.33.0-beta02.aar",
          "url": "ui-0.33.0-beta02.aar",
          "size": 899088,
          "sha512": "ef6915359ab5f731a4e419e5c0871dec534ddab645ce1a2caba8db5fe8d70edc8ee8d303dd7925feb62abd15e7b2e546de1bbfb3b2dfb51fe1a0d65a30ee24be",
          "sha256": "c4b7546d189362fff8473014f4951210bf4b8f7b53c0b5413c649e7297912824",
          "sha1": "97bc220ebd57370f99bb1936b032ef22baea6f06",
          "md5": "21367db34b6d82ec997e3d135fb791e5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0-beta02"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha21"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.0.0-alpha21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.33.0-beta02.aar",
          "url": "ui-0.33.0-beta02.aar",
          "size": 899088,
          "sha512": "ef6915359ab5f731a4e419e5c0871dec534ddab645ce1a2caba8db5fe8d70edc8ee8d303dd7925feb62abd15e7b2e546de1bbfb3b2dfb51fe1a0d65a30ee24be",
          "sha256": "c4b7546d189362fff8473014f4951210bf4b8f7b53c0b5413c649e7297912824",
          "sha1": "97bc220ebd57370f99bb1936b032ef22baea6f06",
          "md5": "21367db34b6d82ec997e3d135fb791e5"
        }
      ]
    }
  ]
}
