{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.35.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cekbw7vkgnerndfmmva5dxnj2m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.1.aar",
          "url": "core-0.35.1.aar",
          "size": 330144,
          "sha512": "1f74639afcf6a23fdb5e59ac7064b02a4924a5502b3503ddc9ec6ad9c885265708980538ee3454232b54c6787cf20dd4f94a5bf746be9a047268e6a47569c141",
          "sha256": "6ca7daf558b7b3ebe7d180b43fdab2aaa565b72753abfaacae729d4ec987da8f",
          "sha1": "5135fbaaedcdfc9f7872bb0816dd6c5139855b05",
          "md5": "fc60dea238fa483c12f2a365979f2f50"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.1.aar",
          "url": "core-0.35.1.aar",
          "size": 330144,
          "sha512": "1f74639afcf6a23fdb5e59ac7064b02a4924a5502b3503ddc9ec6ad9c885265708980538ee3454232b54c6787cf20dd4f94a5bf746be9a047268e6a47569c141",
          "sha256": "6ca7daf558b7b3ebe7d180b43fdab2aaa565b72753abfaacae729d4ec987da8f",
          "sha1": "5135fbaaedcdfc9f7872bb0816dd6c5139855b05",
          "md5": "fc60dea238fa483c12f2a365979f2f50"
        }
      ]
    }
  ]
}
