{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.74.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.74.0.aar",
          "url": "core-0.74.0.aar",
          "size": 637207,
          "sha512": "ae4ba7ae10d6653307af290de838bf70ce7017650a698899e0bda985381f04d12a2877fcb0dfb141594f4637306bfa3113354071a5174e4468fe99db171bd8f4",
          "sha256": "d32c9d629cdf04ea468ffa85b80a5c4f1c14b5e8465c88a5a285f535a5772b5e",
          "sha1": "f9c0eaf4988c3f0722ef33245952be8e9cf2bc62",
          "md5": "e389471732491260e121ba61f03e1fe0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.74.0.aar",
          "url": "core-0.74.0.aar",
          "size": 637207,
          "sha512": "ae4ba7ae10d6653307af290de838bf70ce7017650a698899e0bda985381f04d12a2877fcb0dfb141594f4637306bfa3113354071a5174e4468fe99db171bd8f4",
          "sha256": "d32c9d629cdf04ea468ffa85b80a5c4f1c14b5e8465c88a5a285f535a5772b5e",
          "sha1": "f9c0eaf4988c3f0722ef33245952be8e9cf2bc62",
          "md5": "e389471732491260e121ba61f03e1fe0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.74.0-sources.jar",
          "url": "core-0.74.0-sources.jar",
          "size": 342707,
          "sha512": "d1370d599f8d7aaf3989e942b821cbd404d306551e14ccd7481654a3f7b0b78eeb5df58a0f69822b76585b34f933b83c80013b1a6f5475d13ba74460fbe3f75a",
          "sha256": "ae435b4059d82d4988ad08ebbecc9d86157025d4be420aec1718b2e2e6cfa07e",
          "sha1": "7dd54f095d16a64eaa31382a905e6a3d843b9d94",
          "md5": "72b7e8dbcbc64000aa99d3554f19cb5d"
        }
      ]
    }
  ]
}
