{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "0.80.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.80.12.aar",
          "url": "accessibility-toolbox-0.80.12.aar",
          "size": 24571,
          "sha512": "d0d9623ca945c0e9303854d4dc4e874794c22b1273b08c9aa53ddfcb9a5a5203e157ddacc28956f2a389bbe06036802865edb4beaa20853c8237903619a0e739",
          "sha256": "a55dff91652c0569e9e17c5e59c115542f1c93890cf0ed51fefca27886b41116",
          "sha1": "377daa8d3a37f999f20e52b0f53df72714509bb7",
          "md5": "8ff0e8634ed22bf9b476808834ab385e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.12"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.80.12.aar",
          "url": "accessibility-toolbox-0.80.12.aar",
          "size": 24571,
          "sha512": "d0d9623ca945c0e9303854d4dc4e874794c22b1273b08c9aa53ddfcb9a5a5203e157ddacc28956f2a389bbe06036802865edb4beaa20853c8237903619a0e739",
          "sha256": "a55dff91652c0569e9e17c5e59c115542f1c93890cf0ed51fefca27886b41116",
          "sha1": "377daa8d3a37f999f20e52b0f53df72714509bb7",
          "md5": "8ff0e8634ed22bf9b476808834ab385e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "accessibility-toolbox-0.80.12-sources.jar",
          "url": "accessibility-toolbox-0.80.12-sources.jar",
          "size": 10295,
          "sha512": "5cd29f4679905852d3b741cab239637196dccba323905c9fe947558f3a8e62bd0b26a00d2d2bb061b568f3faff12727b6c27c32d970552f771c22982f80e67c7",
          "sha256": "26c23b54c32a953d82ff453d1871c552d9ecf3928458ebfaf3991c5f5c9692fd",
          "sha1": "e16662017954d97e50f42be15de5f88d1b3a235a",
          "md5": "f430e93992df8383536f3605cfca7c82"
        }
      ]
    }
  ]
}
