{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.35.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "p4oipcf3fjdwrpskpquedrcsbe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.8.aar",
          "url": "core-0.35.8.aar",
          "size": 333432,
          "sha512": "51c783c20d1181f6e559d63f1011a73c3507ae087cc66ecc6ac9dc5c8793b6a5d4ef9f72e0c7fdb12049f7ce5c3937a135ea4a1b2353e6f584471bd880de1871",
          "sha256": "3e9504ac178f46c8dcaedc44256b33221ba3965b02f9ddee203b3fac642b3158",
          "sha1": "a635e417acbf74e1640924b4223b23ae98d837b8",
          "md5": "11f0a62715f788a54941c58a21a92079"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.8.aar",
          "url": "core-0.35.8.aar",
          "size": 333432,
          "sha512": "51c783c20d1181f6e559d63f1011a73c3507ae087cc66ecc6ac9dc5c8793b6a5d4ef9f72e0c7fdb12049f7ce5c3937a135ea4a1b2353e6f584471bd880de1871",
          "sha256": "3e9504ac178f46c8dcaedc44256b33221ba3965b02f9ddee203b3fac642b3158",
          "sha1": "a635e417acbf74e1640924b4223b23ae98d837b8",
          "md5": "11f0a62715f788a54941c58a21a92079"
        }
      ]
    }
  ]
}
