{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.46.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.46.0.aar",
          "url": "utils-0.46.0.aar",
          "size": 43881,
          "sha512": "b232cfee82d8756170519efac5f2c8ad15070f568d8e36b2f6b2d43e042e4dd8ef5fa451d4d541a71d3bc9eb0de772aa77349d60de4cb16965e29ad88edf82fa",
          "sha256": "28de95eeac49f44b86a1b9bc4957625b782a0a136a2cdd546f9b5867e79c8890",
          "sha1": "42c5f19ebbe31c9ec01c2db43cc4678899f6b12e",
          "md5": "66f0097de968feb09eb9e4a2b6b958ae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.46.0.aar",
          "url": "utils-0.46.0.aar",
          "size": 43881,
          "sha512": "b232cfee82d8756170519efac5f2c8ad15070f568d8e36b2f6b2d43e042e4dd8ef5fa451d4d541a71d3bc9eb0de772aa77349d60de4cb16965e29ad88edf82fa",
          "sha256": "28de95eeac49f44b86a1b9bc4957625b782a0a136a2cdd546f9b5867e79c8890",
          "sha1": "42c5f19ebbe31c9ec01c2db43cc4678899f6b12e",
          "md5": "66f0097de968feb09eb9e4a2b6b958ae"
        }
      ]
    }
  ]
}
