{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.48.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.48.0.aar",
          "url": "ui-integration-0.48.0.aar",
          "size": 100591,
          "sha512": "fabaecffb3aac8b345920dfee975025d96e9e5d45b9faaaa3e660fb506ce7e45c78f13b5ed5a971a38732bd11cc5c2257c67dec78c2d4af0874c0a7d7e992fd0",
          "sha256": "5b5a642447504da87029ca73865246e335cae2b0b67148db1c2ca8eebe1d0ad6",
          "sha1": "7161986aa56cd5e21897b615f39edd2266c9547d",
          "md5": "32546cbf1281eb33926d410d4dad1ce4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.48.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.48.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.48.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.48.0.aar",
          "url": "ui-integration-0.48.0.aar",
          "size": 100591,
          "sha512": "fabaecffb3aac8b345920dfee975025d96e9e5d45b9faaaa3e660fb506ce7e45c78f13b5ed5a971a38732bd11cc5c2257c67dec78c2d4af0874c0a7d7e992fd0",
          "sha256": "5b5a642447504da87029ca73865246e335cae2b0b67148db1c2ca8eebe1d0ad6",
          "sha1": "7161986aa56cd5e21897b615f39edd2266c9547d",
          "md5": "32546cbf1281eb33926d410d4dad1ce4"
        }
      ]
    }
  ]
}
