{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "3.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.2.3.aar",
          "url": "core-3.2.3.aar",
          "size": 127055,
          "sha512": "f2cf439e8892d2005bb5e79582bc94b424f0833e310342b180d65b9986273502b14bb787b8ba047a093e019255c1aeb00fd55d8bbd2a3b3b13713fbaf466d217",
          "sha256": "e25cc89a9af15a0f3624f62a01c58d37447b25e4c04a987d4a444de0ace28636",
          "sha1": "861fe42fef327e2f540787626a9cd45c7ff4004d",
          "md5": "2e784c7174e83f05657636ea07db6dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.2.3.aar",
          "url": "core-3.2.3.aar",
          "size": 127055,
          "sha512": "f2cf439e8892d2005bb5e79582bc94b424f0833e310342b180d65b9986273502b14bb787b8ba047a093e019255c1aeb00fd55d8bbd2a3b3b13713fbaf466d217",
          "sha256": "e25cc89a9af15a0f3624f62a01c58d37447b25e4c04a987d4a444de0ace28636",
          "sha1": "861fe42fef327e2f540787626a9cd45c7ff4004d",
          "md5": "2e784c7174e83f05657636ea07db6dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.2.3-sources.jar",
          "url": "core-3.2.3-sources.jar",
          "size": 28118,
          "sha512": "2b09e4582b8b1794bddcf3124fcc1931d43afd59c36b241fc56955f0ab658344dcb1d405d5d688cc70848881b466eadc547af95f96439db88b42bcd5d1efb125",
          "sha256": "2c45e75c2109f64504a2b92ef33e7d468845fff2bbc30081fcc50e74ed1134d4",
          "sha1": "5aabb5a79a4a0176b5ab2fe52f0b2b59eddfdd21",
          "md5": "3d6b44513b74b6f4d1d2ebc298698ee8"
        }
      ]
    }
  ]
}
