{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.3.0.aar",
          "url": "core-3.3.0.aar",
          "size": 137135,
          "sha512": "8f80f12ba8b5197ba10f5fe77b9ee9e9550251cd67266ea641a48b5afced22d05a74d3c58d0188da952c243e217c5bb8fb4cfaa7aba5890599434ca9052c922f",
          "sha256": "a77eeaf626828671e18e65d3e6f4ad734f113bd13be52317bc392ea0a5401533",
          "sha1": "5c64f0f2cc26cf3767da20f9699232e65f5df35e",
          "md5": "773dc1286cc0f5d436ca65de362c1738"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.3.0.aar",
          "url": "core-3.3.0.aar",
          "size": 137135,
          "sha512": "8f80f12ba8b5197ba10f5fe77b9ee9e9550251cd67266ea641a48b5afced22d05a74d3c58d0188da952c243e217c5bb8fb4cfaa7aba5890599434ca9052c922f",
          "sha256": "a77eeaf626828671e18e65d3e6f4ad734f113bd13be52317bc392ea0a5401533",
          "sha1": "5c64f0f2cc26cf3767da20f9699232e65f5df35e",
          "md5": "773dc1286cc0f5d436ca65de362c1738"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.3.0-sources.jar",
          "url": "core-3.3.0-sources.jar",
          "size": 29548,
          "sha512": "a98dc659ff38954a60402cabe5a65109b3878b60d8c7919dc5974d7e7a3fef44b8d50abac4e1e150646b53d1ad9a0cf9f2e6ca3c51220bcb0be969f8c0ec49f0",
          "sha256": "29f87accd13ac4bff8da377f6d4ed4b552c4af5d330d2124c21dffce1a3f205f",
          "sha1": "3daf09bae92e6fca0125a761cf37dabbcc9b181e",
          "md5": "c16fdcfb129d780fc8291f266981c7be"
        }
      ]
    }
  ]
}
