{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.datatrans",
    "module": "android-sdk",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yksnk26oabeu5pt2bepi4b7p2a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-sdk-1.4.0.aar",
          "url": "android-sdk-1.4.0.aar",
          "size": 1855003,
          "sha512": "b20e12ff483d45c6c6c3fc19e149885070273faa6d050310fd56edff78bcd65ac94b2d77c7a9dd6d4b0f40cc987f0f3961e3425d7575b6f57975cefe18c6d445",
          "sha256": "9d55b95f7d88bc0df0d3c74afc8b93d3356e8205495c9cec53139a11158a16b4",
          "sha1": "4d9d188b3468550030ad53a07ecd7f8d88fabf0c",
          "md5": "9b30a385e69a99ec3bf389bc142ed188"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.twint.payment",
          "module": "twint-sdk-android",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "com.paypal.android",
          "module": "risk-component",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-rc02"
          }
        },
        {
          "group": "com.samsung.android.sdk",
          "module": "samsungpay",
          "version": {
            "requires": "2.8.00"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.card",
          "module": "android-sdk",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.4.0.aar",
          "url": "android-sdk-1.4.0.aar",
          "size": 1855003,
          "sha512": "b20e12ff483d45c6c6c3fc19e149885070273faa6d050310fd56edff78bcd65ac94b2d77c7a9dd6d4b0f40cc987f0f3961e3425d7575b6f57975cefe18c6d445",
          "sha256": "9d55b95f7d88bc0df0d3c74afc8b93d3356e8205495c9cec53139a11158a16b4",
          "sha1": "4d9d188b3468550030ad53a07ecd7f8d88fabf0c",
          "md5": "9b30a385e69a99ec3bf389bc142ed188"
        }
      ]
    }
  ]
}
