{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hqpqhi4byza2bbgzmx2cx2k6di"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.4.aar",
          "url": "utils-0.32.4.aar",
          "size": 42927,
          "sha512": "7fe0eeba9a9b774bcb632483be2a2f70125e4460f26d7604eb37a30231b966fb668e274f88396799c8a536282805a4217b1143128a6c980f3b435a12fa92b210",
          "sha256": "3568cd23852e4884cabb72975400db153513f5f1e671cc7f5f62f0b1176cefca",
          "sha1": "34151b337341a03131238037e83dce4d4805ee51",
          "md5": "037cbb9005c59f496182f708933fd617"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.4.aar",
          "url": "utils-0.32.4.aar",
          "size": 42927,
          "sha512": "7fe0eeba9a9b774bcb632483be2a2f70125e4460f26d7604eb37a30231b966fb668e274f88396799c8a536282805a4217b1143128a6c980f3b435a12fa92b210",
          "sha256": "3568cd23852e4884cabb72975400db153513f5f1e671cc7f5f62f0b1176cefca",
          "sha1": "34151b337341a03131238037e83dce4d4805ee51",
          "md5": "037cbb9005c59f496182f708933fd617"
        }
      ]
    }
  ]
}
