{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.37.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "isjfzwozkfecnno43fswrlvivm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.2.aar",
          "url": "core-0.37.2.aar",
          "size": 351956,
          "sha512": "8fef2d27e72831656483fb30dab0fd3842899f28cbc964f7ae3d63d61e861492e57eeab86dd4869be5cd05743653dfa2185cf84b485dba6bcc9ae5162b2b99e0",
          "sha256": "d72d149af21ae2d498b3311590b50f8bd39f941b4fc1491a166d4a092c962c18",
          "sha1": "0f922a557070fed22d3dc758567f4e5b9fdf117f",
          "md5": "252f1312f2a59969d5ba125b05a074e2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.2.aar",
          "url": "core-0.37.2.aar",
          "size": 351956,
          "sha512": "8fef2d27e72831656483fb30dab0fd3842899f28cbc964f7ae3d63d61e861492e57eeab86dd4869be5cd05743653dfa2185cf84b485dba6bcc9ae5162b2b99e0",
          "sha256": "d72d149af21ae2d498b3311590b50f8bd39f941b4fc1491a166d4a092c962c18",
          "sha1": "0f922a557070fed22d3dc758567f4e5b9fdf117f",
          "md5": "252f1312f2a59969d5ba125b05a074e2"
        }
      ]
    }
  ]
}
