{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.72.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.1.aar",
          "url": "mlkit-scanner-engine-0.72.1.aar",
          "size": 64290,
          "sha512": "6bc98d101538a29f4bebd00c2dbc3b8cdaec196e2952ce9f05a50672641a208752e67e30da6a0537d149854388351e059629fca1bb5d3af8706a8b27562f89af",
          "sha256": "71af5e8e96c3a53e50cb6b69863473c07beeed3a8c657c4fd78229c3ff4af73b",
          "sha1": "0ab4e3f515875a6d39d97add096bbdc85ea7277f",
          "md5": "29694e730b16b5d8b3cc16f4105d43f3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.72.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.72.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.1.aar",
          "url": "mlkit-scanner-engine-0.72.1.aar",
          "size": 64290,
          "sha512": "6bc98d101538a29f4bebd00c2dbc3b8cdaec196e2952ce9f05a50672641a208752e67e30da6a0537d149854388351e059629fca1bb5d3af8706a8b27562f89af",
          "sha256": "71af5e8e96c3a53e50cb6b69863473c07beeed3a8c657c4fd78229c3ff4af73b",
          "sha1": "0ab4e3f515875a6d39d97add096bbdc85ea7277f",
          "md5": "29694e730b16b5d8b3cc16f4105d43f3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.72.1-sources.jar",
          "url": "mlkit-scanner-engine-0.72.1-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
