{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.10.aar",
          "url": "core-0.80.10.aar",
          "size": 668646,
          "sha512": "6c61b1c4ca9e50fc7c7c1ece01c3610b8240907519a901bfa612ff42f77e638cd03115c7dbfc555bbc12b560184944f428bcbfc8c4822b9edbefaa3e10221461",
          "sha256": "61b059b555d6a1b2059fee3a998a82d79f5137eddbd939890e0cc8078f070920",
          "sha1": "3344e13bed44b6ae6b0612db4905df6dbf38391f",
          "md5": "155cf35e58f8351582b769f79f0cb617"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.10.aar",
          "url": "core-0.80.10.aar",
          "size": 668646,
          "sha512": "6c61b1c4ca9e50fc7c7c1ece01c3610b8240907519a901bfa612ff42f77e638cd03115c7dbfc555bbc12b560184944f428bcbfc8c4822b9edbefaa3e10221461",
          "sha256": "61b059b555d6a1b2059fee3a998a82d79f5137eddbd939890e0cc8078f070920",
          "sha1": "3344e13bed44b6ae6b0612db4905df6dbf38391f",
          "md5": "155cf35e58f8351582b769f79f0cb617"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.10-sources.jar",
          "url": "core-0.80.10-sources.jar",
          "size": 352215,
          "sha512": "b3f9b69251ba01709519440b97e7c56aaaf50de676c4ad436915b11637d5c46b2de4c7323e3edb027deffbe454cbe5ad36d5b6d9e01d1b65fc5b17ffd13fa6f7",
          "sha256": "4b1c3473d540e8904b394dec98d0902d4591eb7fca840b4243516c235f341b69",
          "sha1": "03ef4c491de12ebf3057390c47228e5d3a9a2b87",
          "md5": "41ea61bf35676dd549698bb06133b995"
        }
      ]
    }
  ]
}
