{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.73.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.73.0.aar",
          "url": "utils-0.73.0.aar",
          "size": 58354,
          "sha512": "c1efcba94bfde827471256a2a7340434d6a928414d810a27028c0d3fe039306747bbf014e5d2297b78cec6c124f1888dd35f384889c2114002f934248817e852",
          "sha256": "64b71c3707b6eaed0f99ac9a2e19bbe4ca7e474f734f9daf07520e01d3324bf0",
          "sha1": "87ee56d70c2b859e150c1ba6350305dadc3414cc",
          "md5": "92358d7e381793b97088a7a7058a1a56"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.73.0.aar",
          "url": "utils-0.73.0.aar",
          "size": 58354,
          "sha512": "c1efcba94bfde827471256a2a7340434d6a928414d810a27028c0d3fe039306747bbf014e5d2297b78cec6c124f1888dd35f384889c2114002f934248817e852",
          "sha256": "64b71c3707b6eaed0f99ac9a2e19bbe4ca7e474f734f9daf07520e01d3324bf0",
          "sha1": "87ee56d70c2b859e150c1ba6350305dadc3414cc",
          "md5": "92358d7e381793b97088a7a7058a1a56"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.73.0-sources.jar",
          "url": "utils-0.73.0-sources.jar",
          "size": 45527,
          "sha512": "6323429672ff5f66b6109c16210fcf4d10e84648a2a1aad592b451930d9780e769bf76842b54dd61a20ed081c426f77053677e27ba3c76a2d94f9e2f52d89492",
          "sha256": "4f8d42603fa2159b6ccafbe6782e5ffa766ed656bcac3d65cc40c354df11cc34",
          "sha1": "19e41563e77d2e27391471ade0f4d2d27dc18985",
          "md5": "bbf2a45207b95b7a785c85e06e385660"
        }
      ]
    }
  ]
}
