{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.26.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qnnc5xf27nhqdblyvtq6zbodxu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.26.4.aar",
          "url": "ui-0.26.4.aar",
          "size": 829820,
          "sha512": "71faf016bca3b4818835e12d5e71138c58ee66901900cbff2fe5a31340f993094456c8ded294b2f1b422e3b4de65350aaa378f8dabfd9313c430e1b5ec888de9",
          "sha256": "c4401a9c30239fae843a50c5877dfea229c80e678f20bc4a466801eaeba15401",
          "sha1": "22fc9bed2267456bf2b42fa25f68d0d493252176",
          "md5": "904bcc32ed3d1fcc4dcf18e7d80e4059"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.26.4.aar",
          "url": "ui-0.26.4.aar",
          "size": 829820,
          "sha512": "71faf016bca3b4818835e12d5e71138c58ee66901900cbff2fe5a31340f993094456c8ded294b2f1b422e3b4de65350aaa378f8dabfd9313c430e1b5ec888de9",
          "sha256": "c4401a9c30239fae843a50c5877dfea229c80e678f20bc4a466801eaeba15401",
          "sha1": "22fc9bed2267456bf2b42fa25f68d0d493252176",
          "md5": "904bcc32ed3d1fcc4dcf18e7d80e4059"
        }
      ]
    }
  ]
}
