{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.68.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.68.3.aar",
          "url": "utils-0.68.3.aar",
          "size": 46662,
          "sha512": "e5865742d9de084fd33c498fd1c403c96f80aa6765af63fe7fc9d4b9665baadf788cbc2b1583f493a06d7611dcdf94f9613633df7706b33773f85ea2c6f8fc1a",
          "sha256": "7d9dee51ac7da7f261f216085ccfd4041969bd0508502a21d7745af0790d8295",
          "sha1": "72486105a72265aa21e214d892eecbdea809de2d",
          "md5": "31006baa7a0e9e02e778749a00b2333e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.68.3.aar",
          "url": "utils-0.68.3.aar",
          "size": 46662,
          "sha512": "e5865742d9de084fd33c498fd1c403c96f80aa6765af63fe7fc9d4b9665baadf788cbc2b1583f493a06d7611dcdf94f9613633df7706b33773f85ea2c6f8fc1a",
          "sha256": "7d9dee51ac7da7f261f216085ccfd4041969bd0508502a21d7745af0790d8295",
          "sha1": "72486105a72265aa21e214d892eecbdea809de2d",
          "md5": "31006baa7a0e9e02e778749a00b2333e"
        }
      ]
    }
  ]
}
