{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sju4g5fjoze6pnwveeiadmeyny"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.6.aar",
          "url": "ui-0.25.6.aar",
          "size": 827922,
          "sha512": "54099f204bd778428b0cdd1c5563b5905e5c99d90e8b508609dcb9e87e2b4b8a5f105175cac5735536a16cb7d4e962003fc4a2bfea2e62a9943723dbca688b5f",
          "sha256": "a84e842c13a8ba4862a62953abb2eab6cc9d809711fff2427db2386f42ea40c5",
          "sha1": "46e87bb66ee7789892e8f3f37ff01d842f091ea6",
          "md5": "4bfa5ec0a687ac85faee5c24ec8ebff4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.6.aar",
          "url": "ui-0.25.6.aar",
          "size": 827922,
          "sha512": "54099f204bd778428b0cdd1c5563b5905e5c99d90e8b508609dcb9e87e2b4b8a5f105175cac5735536a16cb7d4e962003fc4a2bfea2e62a9943723dbca688b5f",
          "sha256": "a84e842c13a8ba4862a62953abb2eab6cc9d809711fff2427db2386f42ea40c5",
          "sha1": "46e87bb66ee7789892e8f3f37ff01d842f091ea6",
          "md5": "4bfa5ec0a687ac85faee5c24ec8ebff4"
        }
      ]
    }
  ]
}
