{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ktdau6mui5h5biffnr7ftglpqu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.3.aar",
          "url": "utils-0.33.3.aar",
          "size": 42944,
          "sha512": "badeff7791877811a89a05d002c74b0deb99f7efb6c1f8f9de723159e96c513255687cebf1b3551f0d74ff1ddbdd93c7fc17fa49fb31e579bf93fd96b1914a2c",
          "sha256": "8d88d026c4421d32457cf08562c27349c1b0f8c2d56466f9314bf16a269d2190",
          "sha1": "9ba71e4cfaf7780b0a9af4166701752c8c268ef8",
          "md5": "60245e7061efee9aca955e22c90035c1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.3.aar",
          "url": "utils-0.33.3.aar",
          "size": 42944,
          "sha512": "badeff7791877811a89a05d002c74b0deb99f7efb6c1f8f9de723159e96c513255687cebf1b3551f0d74ff1ddbdd93c7fc17fa49fb31e579bf93fd96b1914a2c",
          "sha256": "8d88d026c4421d32457cf08562c27349c1b0f8c2d56466f9314bf16a269d2190",
          "sha1": "9ba71e4cfaf7780b0a9af4166701752c8c268ef8",
          "md5": "60245e7061efee9aca955e22c90035c1"
        }
      ]
    }
  ]
}
