{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.38.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "i2hthj6spjfn5l6ya6riaggcoi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.38.1.aar",
          "url": "core-0.38.1.aar",
          "size": 351353,
          "sha512": "513304ef6f60e16f6e5cb8920b5c2045cb0f85b9f878afdcd38c6f67a089b064ca7d5bd12caa5e20885d366eb238d90d60aec5e6238fbc198e34327cfcd3d295",
          "sha256": "0c382a9de00cdbf25dda5eff85449bd149b5985b1152f58f6b1e5fc66cf22fbc",
          "sha1": "29d5da72d6e483e234505e26fb95e22bb8d03ff5",
          "md5": "588fc982b6c03f3389c87be3e483f6c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.38.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.38.1.aar",
          "url": "core-0.38.1.aar",
          "size": 351353,
          "sha512": "513304ef6f60e16f6e5cb8920b5c2045cb0f85b9f878afdcd38c6f67a089b064ca7d5bd12caa5e20885d366eb238d90d60aec5e6238fbc198e34327cfcd3d295",
          "sha256": "0c382a9de00cdbf25dda5eff85449bd149b5985b1152f58f6b1e5fc66cf22fbc",
          "sha1": "29d5da72d6e483e234505e26fb95e22bb8d03ff5",
          "md5": "588fc982b6c03f3389c87be3e483f6c0"
        }
      ]
    }
  ]
}
