{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.27.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "75b5cknexzd3zmwrrpmpmewguu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.27.3.aar",
          "url": "ui-0.27.3.aar",
          "size": 830478,
          "sha512": "f07743a8c402970fd4836c1b76b198b1e90a8b41a8e4b2e6ec29aef722fb01787a572d90b75906e81525f924199ed59420273ddd4ad331f048abc68e18bdb092",
          "sha256": "fad5d625023a0507816a6df06f7d8f2ed8eb5cc234fa2d5ebfbe762d4a913b2d",
          "sha1": "e1897991e7dd434ebb239f2698176a1d8c4cc394",
          "md5": "8e03d7d366ba1f104649b44a74f324fc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.27.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.27.3.aar",
          "url": "ui-0.27.3.aar",
          "size": 830478,
          "sha512": "f07743a8c402970fd4836c1b76b198b1e90a8b41a8e4b2e6ec29aef722fb01787a572d90b75906e81525f924199ed59420273ddd4ad331f048abc68e18bdb092",
          "sha256": "fad5d625023a0507816a6df06f7d8f2ed8eb5cc234fa2d5ebfbe762d4a913b2d",
          "sha1": "e1897991e7dd434ebb239f2698176a1d8c4cc394",
          "md5": "8e03d7d366ba1f104649b44a74f324fc"
        }
      ]
    }
  ]
}
