{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.35.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cxwollak2bhpdinsvzain3fecu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.6.aar",
          "url": "core-0.35.6.aar",
          "size": 333434,
          "sha512": "a8e63e4d985d5c12eba3588ad9e67229f5ae5739f0928c591f7b9ef2051d0bddb780f9a666049b3f56a91caa1416431e91c0b01241bc365830ada09b8bb7800b",
          "sha256": "bbd690d0432d2e2db5d8b37828b67ff64a2c4b982ef864dae52ce525c4d3f7b1",
          "sha1": "7c28d33feedeedcdb8808d234ec36101d3335d8a",
          "md5": "f727adcc3b91f5a9c2aa3b4051f6a1d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.6.aar",
          "url": "core-0.35.6.aar",
          "size": 333434,
          "sha512": "a8e63e4d985d5c12eba3588ad9e67229f5ae5739f0928c591f7b9ef2051d0bddb780f9a666049b3f56a91caa1416431e91c0b01241bc365830ada09b8bb7800b",
          "sha256": "bbd690d0432d2e2db5d8b37828b67ff64a2c4b982ef864dae52ce525c4d3f7b1",
          "sha1": "7c28d33feedeedcdb8808d234ec36101d3335d8a",
          "md5": "f727adcc3b91f5a9c2aa3b4051f6a1d0"
        }
      ]
    }
  ]
}
