{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5atmn5bfffedxi473gjj37l2hu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.28.0.aar",
          "url": "ui-0.28.0.aar",
          "size": 831804,
          "sha512": "0de00483c93d0074d6563f4eddbe7c855a1ea7a556cd9f7c7f303b5a623404349024c645c5161a5f70c6a2716eeb9d5d0350004c2fbbeb958e6b8d3635fd894a",
          "sha256": "9ecf620541b94ded9fb7917f60e40888a44d5323f6fa7cf9eb75db388f3d7880",
          "sha1": "cb03f5a4f5480229914c03defb4615c285738287",
          "md5": "75de895d2339fc15e0f2c8492f2ca0d2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.28.0.aar",
          "url": "ui-0.28.0.aar",
          "size": 831804,
          "sha512": "0de00483c93d0074d6563f4eddbe7c855a1ea7a556cd9f7c7f303b5a623404349024c645c5161a5f70c6a2716eeb9d5d0350004c2fbbeb958e6b8d3635fd894a",
          "sha256": "9ecf620541b94ded9fb7917f60e40888a44d5323f6fa7cf9eb75db388f3d7880",
          "sha1": "cb03f5a4f5480229914c03defb4615c285738287",
          "md5": "75de895d2339fc15e0f2c8492f2ca0d2"
        }
      ]
    }
  ]
}
