{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.34.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o75qremr5rhdhnsylosxqqpy7q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.4.aar",
          "url": "ui-integration-0.34.4.aar",
          "size": 92935,
          "sha512": "6a6618841f395f9c00b47c562dc7d67a47055eaf7d28f4875da0e3103b0ae5dbe6f5275c799ea13a6f34ef51edc8f81a65dd40f758b0ea6cbe8eba1d5b410174",
          "sha256": "aa79eb8bdcc5b123ac1c28e7cbbdc7e75402172ae210fde0e33d1e1db5d247c0",
          "sha1": "cf093306baf1014045db23437be9341175e6e85d",
          "md5": "04d0d4df42efb678193ca02720e99116"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.34.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.34.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.34.4.aar",
          "url": "ui-integration-0.34.4.aar",
          "size": 92935,
          "sha512": "6a6618841f395f9c00b47c562dc7d67a47055eaf7d28f4875da0e3103b0ae5dbe6f5275c799ea13a6f34ef51edc8f81a65dd40f758b0ea6cbe8eba1d5b410174",
          "sha256": "aa79eb8bdcc5b123ac1c28e7cbbdc7e75402172ae210fde0e33d1e1db5d247c0",
          "sha1": "cf093306baf1014045db23437be9341175e6e85d",
          "md5": "04d0d4df42efb678193ca02720e99116"
        }
      ]
    }
  ]
}
