{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.74.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.74.0.aar",
          "url": "mlkit-scanner-engine-0.74.0.aar",
          "size": 63889,
          "sha512": "142776cbbf649bec22a40324a77b951bb20af21fbd424d400aeddccacf0a89d6fd1ea34e4738941e48905f6271fe6b387e2c241b89957164decb736acec4480d",
          "sha256": "c27fc334ceab31359ad06c47b2c747df52b12b3ca2521111e50c8ce123ff2db5",
          "sha1": "1a5f2136e699784215f81beb6432770e87908d37",
          "md5": "8ca74bfefd774d1f7040e9d6501675cf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.74.0.aar",
          "url": "mlkit-scanner-engine-0.74.0.aar",
          "size": 63889,
          "sha512": "142776cbbf649bec22a40324a77b951bb20af21fbd424d400aeddccacf0a89d6fd1ea34e4738941e48905f6271fe6b387e2c241b89957164decb736acec4480d",
          "sha256": "c27fc334ceab31359ad06c47b2c747df52b12b3ca2521111e50c8ce123ff2db5",
          "sha1": "1a5f2136e699784215f81beb6432770e87908d37",
          "md5": "8ca74bfefd774d1f7040e9d6501675cf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.74.0-sources.jar",
          "url": "mlkit-scanner-engine-0.74.0-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
