{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.40.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o2uhyrhelndchlnzrg4luvhuvu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.40.1.aar",
          "url": "ui-integration-0.40.1.aar",
          "size": 100764,
          "sha512": "8017ad171cab8fb32f871e3696b273b0b262453e8582d781928bc0b78805ae84673b4eafccd84cfed690eac386eb6545ad51475bd894e6691576fc0d8a53212c",
          "sha256": "0cc69abc1367ecf443d1babb468de1b9355955355a097e3d880df702eb29911e",
          "sha1": "07625b00b9fbac6dd8d459bf2860436b653d4dd0",
          "md5": "21ed4c6b09202b16eb3a8017026a2a80"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.40.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.40.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.40.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.40.1.aar",
          "url": "ui-integration-0.40.1.aar",
          "size": 100764,
          "sha512": "8017ad171cab8fb32f871e3696b273b0b262453e8582d781928bc0b78805ae84673b4eafccd84cfed690eac386eb6545ad51475bd894e6691576fc0d8a53212c",
          "sha256": "0cc69abc1367ecf443d1babb468de1b9355955355a097e3d880df702eb29911e",
          "sha1": "07625b00b9fbac6dd8d459bf2860436b653d4dd0",
          "md5": "21ed4c6b09202b16eb3a8017026a2a80"
        }
      ]
    }
  ]
}
