{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.82.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.7.aar",
          "url": "mlkit-scanner-engine-0.82.7.aar",
          "size": 68919,
          "sha512": "4172beda1b7a7df6a2e01a8f12a54e3392b95f0ad1b84697b4bc01fb5ea7195c4d4b83b295f82166345fc3a8fac4f8b6d08662e8e227342c48860dd251b6933b",
          "sha256": "3cae6797b045dadd33ab2fc811ddf4b27d4b3b4a46eb42e19317e75ecbdda74e",
          "sha1": "2604d1f5ea6dc793af8fca64e5db99bd52c765a6",
          "md5": "4cd345fafd4282ef15562211dc9ec40d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.82.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.82.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.7"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.7.aar",
          "url": "mlkit-scanner-engine-0.82.7.aar",
          "size": 68919,
          "sha512": "4172beda1b7a7df6a2e01a8f12a54e3392b95f0ad1b84697b4bc01fb5ea7195c4d4b83b295f82166345fc3a8fac4f8b6d08662e8e227342c48860dd251b6933b",
          "sha256": "3cae6797b045dadd33ab2fc811ddf4b27d4b3b4a46eb42e19317e75ecbdda74e",
          "sha1": "2604d1f5ea6dc793af8fca64e5db99bd52c765a6",
          "md5": "4cd345fafd4282ef15562211dc9ec40d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.7-sources.jar",
          "url": "mlkit-scanner-engine-0.82.7-sources.jar",
          "size": 7461,
          "sha512": "221159708b9b3989fce5be7004949d5bc0fd9004ca06e5e7133c8463ef545036a99acfbbff07d8a5f7c45086a01c1027bb7ab5ed21ab5a39c3a946d89a0d1642",
          "sha256": "4c1778dc04c1bff7ab6efb7aef8d27e937239e5676c3213b6d304cf1b24234f8",
          "sha1": "2568d2be894590900c461738ce35d7ec6f448558",
          "md5": "652b419bbfc5db29899d2c1abb8fc63c"
        }
      ]
    }
  ]
}
