{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.40.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7mfnvapylnan7j3rqc6eziut7y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.40.0.aar",
          "url": "ui-integration-0.40.0.aar",
          "size": 100734,
          "sha512": "d51b7ef9685c6d6d47d840a5cf32bacb66a85fd0151768f02b7c3d8b22c1906fd792636ebfae89b63e8cd9b44da8ca57a64c4814dee86bef0677579a0cc933be",
          "sha256": "737996af0f777663294d33a120ed212e0c1719595a610a73c4f43ff1e18913a2",
          "sha1": "3aa2d7f91e70a3a6bb6488f3577a232e97e59f90",
          "md5": "46346215dff76afb2398dcb9a2a4e110"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.40.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.40.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.40.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.40.0.aar",
          "url": "ui-integration-0.40.0.aar",
          "size": 100734,
          "sha512": "d51b7ef9685c6d6d47d840a5cf32bacb66a85fd0151768f02b7c3d8b22c1906fd792636ebfae89b63e8cd9b44da8ca57a64c4814dee86bef0677579a0cc933be",
          "sha256": "737996af0f777663294d33a120ed212e0c1719595a610a73c4f43ff1e18913a2",
          "sha1": "3aa2d7f91e70a3a6bb6488f3577a232e97e59f90",
          "md5": "46346215dff76afb2398dcb9a2a4e110"
        }
      ]
    }
  ]
}
