{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.82.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.82.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "accessibility-toolbox",
          "version": {
            "requires": "0.82.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.82.1.aar",
          "url": "ui-0.82.1.aar",
          "size": 2296178,
          "sha512": "6d655cb40bb40f35f0fc5289399791da7d3de4c6d5c494a00c49fb0f1441ed0c3e5291257851d854be5b593f8ed19672c79004515ed8ce1a4400f5c7af0551fa",
          "sha256": "080312f5ecb389142b5db5c3aa6f79a75c973822bd4f5eb05596821a12e181d9",
          "sha1": "fd84fbd1d429a9652e89ab961913f541940df48a",
          "md5": "40e60c3d2a55eb70eb6a8eee83fd260f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "ch.datatrans",
          "module": "android-sdk",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "compose",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.snabble.phoneauth",
          "module": "countryCodePicker",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-material3",
          "version": {
            "requires": "0.36.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.82.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "accessibility-toolbox",
          "version": {
            "requires": "0.82.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.82.1.aar",
          "url": "ui-0.82.1.aar",
          "size": 2296178,
          "sha512": "6d655cb40bb40f35f0fc5289399791da7d3de4c6d5c494a00c49fb0f1441ed0c3e5291257851d854be5b593f8ed19672c79004515ed8ce1a4400f5c7af0551fa",
          "sha256": "080312f5ecb389142b5db5c3aa6f79a75c973822bd4f5eb05596821a12e181d9",
          "sha1": "fd84fbd1d429a9652e89ab961913f541940df48a",
          "md5": "40e60c3d2a55eb70eb6a8eee83fd260f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-0.82.1-sources.jar",
          "url": "ui-0.82.1-sources.jar",
          "size": 675445,
          "sha512": "b3ea7b94fcd4d441e71ca526eedf974d33431c1c479eec3ed1bbd5784b6cc6748bf7ebf275a2bd2ae8e5e2c334bccd6dedbab14f52084e3cc7be0046983555f5",
          "sha256": "7fa0315d4e5ffd296a4fece7652c3bc68e419abb8d4d6de02b4eaf571eaef243",
          "sha1": "35730c90f85d0ef0ddd563f37a7fd8eaa4d72a81",
          "md5": "5a696142752bfa09500a1d89352077df"
        }
      ]
    }
  ]
}
