{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.0.aar",
          "url": "core-0.75.0.aar",
          "size": 637322,
          "sha512": "3c74c698951af364882ccf20c3bd9bc7bfce067ef617e472d1441cbf30a631949962a5b425abf7576dcb4c6152014d4cb2f39d9a0e164055be5882f5538f8b9f",
          "sha256": "a995cfeb7e44b610fc0c43d98676305a4db2976d3c1720c4842069732e1edd5e",
          "sha1": "004b9a9527546bfffb361e30973a75deeda733a0",
          "md5": "4610c95029acf6144965813f0e4e904f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.0.aar",
          "url": "core-0.75.0.aar",
          "size": 637322,
          "sha512": "3c74c698951af364882ccf20c3bd9bc7bfce067ef617e472d1441cbf30a631949962a5b425abf7576dcb4c6152014d4cb2f39d9a0e164055be5882f5538f8b9f",
          "sha256": "a995cfeb7e44b610fc0c43d98676305a4db2976d3c1720c4842069732e1edd5e",
          "sha1": "004b9a9527546bfffb361e30973a75deeda733a0",
          "md5": "4610c95029acf6144965813f0e4e904f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.0-sources.jar",
          "url": "core-0.75.0-sources.jar",
          "size": 342779,
          "sha512": "3d672fcfd8cf28356d4643ffcc5dd5c2556b7a721887ee72c38c44d6b876bbd41d33ddd34dff63da47f965f3f26e9710f4caf544090e047be3a53d44aeffbaaa",
          "sha256": "21f4efc633a7b311b3d2f464ce8a6622f2d2a0b6ca43cbb246cf49d2f6cc104f",
          "sha1": "e2728628b95128c253b8f2ddd67da17bcf86c5af",
          "md5": "556806ffc4aa0e2971e65b5d4d36214a"
        }
      ]
    }
  ]
}
