{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rki2fzqsmbd5neolp47hawt4ou"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.30.0.aar",
          "url": "core-0.30.0.aar",
          "size": 322435,
          "sha512": "046989bfb681bb2bc19f0342d9709c8bad13fac10b8556c9b3eb3886c95fd0cd161562c201334fa9ed8f8d49852d5fc93bc5077fccd0fd7ebc774fdd34cbcc56",
          "sha256": "0cc09fa16a8261901034ec1156c6a7d9acd3e809c5e6a4ccd47f03cb01f0f219",
          "sha1": "3e716c109978a3f5a1d48e16c115a77da38c1aa3",
          "md5": "e898fbf03f9d56eb96f259f99ceac86c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.30.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.30.0.aar",
          "url": "core-0.30.0.aar",
          "size": 322435,
          "sha512": "046989bfb681bb2bc19f0342d9709c8bad13fac10b8556c9b3eb3886c95fd0cd161562c201334fa9ed8f8d49852d5fc93bc5077fccd0fd7ebc774fdd34cbcc56",
          "sha256": "0cc09fa16a8261901034ec1156c6a7d9acd3e809c5e6a4ccd47f03cb01f0f219",
          "sha1": "3e716c109978a3f5a1d48e16c115a77da38c1aa3",
          "md5": "e898fbf03f9d56eb96f259f99ceac86c"
        }
      ]
    }
  ]
}
