{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.33.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tean77tudrg43fh3xguyqzorom"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.33.10.aar",
          "url": "ui-integration-0.33.10.aar",
          "size": 92805,
          "sha512": "52044cf91ca8becbd8843fa9ca42724c511799e73b59038108074620d4c4d6b9001799f04e3e240b4f100a865c6ebb42f940db25c707d502d09219c82a5b48a1",
          "sha256": "5a3403317ebf2e32e9e5ca4e2b3b96145bacb5a18d66d9feb9ac8acb12c1d126",
          "sha1": "0dceb1482fbc848bca0718c37783b0b313b9ced6",
          "md5": "2634a32783b2f2fc06dd4c581c83dc0c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.10"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.33.10.aar",
          "url": "ui-integration-0.33.10.aar",
          "size": 92805,
          "sha512": "52044cf91ca8becbd8843fa9ca42724c511799e73b59038108074620d4c4d6b9001799f04e3e240b4f100a865c6ebb42f940db25c707d502d09219c82a5b48a1",
          "sha256": "5a3403317ebf2e32e9e5ca4e2b3b96145bacb5a18d66d9feb9ac8acb12c1d126",
          "sha1": "0dceb1482fbc848bca0718c37783b0b313b9ced6",
          "md5": "2634a32783b2f2fc06dd4c581c83dc0c"
        }
      ]
    }
  ]
}
