{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.69.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.0.aar",
          "url": "utils-0.69.0.aar",
          "size": 54303,
          "sha512": "d7ec3d1a9ee5cf27ce494abd3c51fc4c242cf2947779b5619f3658bf8880e897e20e55de7ae69371efa308fa550878884ed9a7d9597dd35ccff12e175a4a1f7a",
          "sha256": "0745b9d620e70bb5cb8a6a916f897f35e41e04ee7cae39656c714254b096f682",
          "sha1": "8e25a8131367882793d9a93f5feaff56b82c58a0",
          "md5": "a34ab14aa9911131c2c3c24d9ccc8f3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.0.aar",
          "url": "utils-0.69.0.aar",
          "size": 54303,
          "sha512": "d7ec3d1a9ee5cf27ce494abd3c51fc4c242cf2947779b5619f3658bf8880e897e20e55de7ae69371efa308fa550878884ed9a7d9597dd35ccff12e175a4a1f7a",
          "sha256": "0745b9d620e70bb5cb8a6a916f897f35e41e04ee7cae39656c714254b096f682",
          "sha1": "8e25a8131367882793d9a93f5feaff56b82c58a0",
          "md5": "a34ab14aa9911131c2c3c24d9ccc8f3c"
        }
      ]
    }
  ]
}
