{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5ji7qh4ifbbd5j65vbqdkdc2ye"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.8.aar",
          "url": "utils-0.33.8.aar",
          "size": 42945,
          "sha512": "566793e85a545d2226867090487be45a5b8c7dda7add68031e948d307b4520fc219f06dd1b53671f1ae0fd3f056edc262c06f99927dd342dcefcc919b63f1c02",
          "sha256": "cbd52225046c919e6641a15374214d0caaf5286801d1fcd63cf3734725f412e7",
          "sha1": "cdcd7dd04addc1bc9dc03504fedcb8969f09c4a1",
          "md5": "34f31bc3bbfb2d73d237e497a60745a5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.8.aar",
          "url": "utils-0.33.8.aar",
          "size": 42945,
          "sha512": "566793e85a545d2226867090487be45a5b8c7dda7add68031e948d307b4520fc219f06dd1b53671f1ae0fd3f056edc262c06f99927dd342dcefcc919b63f1c02",
          "sha256": "cbd52225046c919e6641a15374214d0caaf5286801d1fcd63cf3734725f412e7",
          "sha1": "cdcd7dd04addc1bc9dc03504fedcb8969f09c4a1",
          "md5": "34f31bc3bbfb2d73d237e497a60745a5"
        }
      ]
    }
  ]
}
