{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rmyzmgye55cwlm3vypxkrmndji"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.0.aar",
          "url": "ui-0.25.0.aar",
          "size": 827059,
          "sha512": "e293037ba4353465784ed30a6450547fb6968602ebfaee2b4bcf3df426bd62c85964e5a0de560be38f86bf6eb49975e743a0903e15b879842e7cfc5a8f75f559",
          "sha256": "5e9e34965a2e927bdb9a98e275412e2c86f6346cdb0b23fa56907d3e5f630464",
          "sha1": "c5ea5f45fa59bd5a95d0144eca4202aa7bbf5852",
          "md5": "77073a74a385717afbcc7bab9c57ccde"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.0.aar",
          "url": "ui-0.25.0.aar",
          "size": 827059,
          "sha512": "e293037ba4353465784ed30a6450547fb6968602ebfaee2b4bcf3df426bd62c85964e5a0de560be38f86bf6eb49975e743a0903e15b879842e7cfc5a8f75f559",
          "sha256": "5e9e34965a2e927bdb9a98e275412e2c86f6346cdb0b23fa56907d3e5f630464",
          "sha1": "c5ea5f45fa59bd5a95d0144eca4202aa7bbf5852",
          "md5": "77073a74a385717afbcc7bab9c57ccde"
        }
      ]
    }
  ]
}
