{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7ztuy3oz2zfk7obahnomimwcyq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.4.aar",
          "url": "core-0.33.4.aar",
          "size": 327881,
          "sha512": "3039dfd9e8d2a1269d3da0598af3f1404e9a498b330e11eb5841328bc859d3295abcd588c9c57e30d9283479afa2c33e6dc476f3f75c0b59e37b05a1d709d4f8",
          "sha256": "2da9c35bd9fcfa4c3b740be06d4b41fee03f1e3a27c1a7a7999fc0b18fc00d37",
          "sha1": "cbd7e8612e2fbcde15b948fe880666f876685e79",
          "md5": "6ebc063f9311025bea16d462fc798928"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.4.aar",
          "url": "core-0.33.4.aar",
          "size": 327881,
          "sha512": "3039dfd9e8d2a1269d3da0598af3f1404e9a498b330e11eb5841328bc859d3295abcd588c9c57e30d9283479afa2c33e6dc476f3f75c0b59e37b05a1d709d4f8",
          "sha256": "2da9c35bd9fcfa4c3b740be06d4b41fee03f1e3a27c1a7a7999fc0b18fc00d37",
          "sha1": "cbd7e8612e2fbcde15b948fe880666f876685e79",
          "md5": "6ebc063f9311025bea16d462fc798928"
        }
      ]
    }
  ]
}
