{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.29.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "u2shwelgpvbononkksnwr4sgra"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.2.aar",
          "url": "utils-0.29.2.aar",
          "size": 40158,
          "sha512": "0f4d34fbe8edeb0aa9d0353d5aab53cf688b61187d1e4d3c2fd16cedb9ef42813fbfcdaad89db3043af031e17aa588975e8797663387e4cffe8caffd69822b7b",
          "sha256": "d4714f29f627649e73409f4080a5acc606ed2004dc09d22ac2167427e11f8b75",
          "sha1": "5c2c61e44288b2d15832fecb51a473ed529be701",
          "md5": "f6594b62b9c63019e22230f863d83c73"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.2.aar",
          "url": "utils-0.29.2.aar",
          "size": 40158,
          "sha512": "0f4d34fbe8edeb0aa9d0353d5aab53cf688b61187d1e4d3c2fd16cedb9ef42813fbfcdaad89db3043af031e17aa588975e8797663387e4cffe8caffd69822b7b",
          "sha256": "d4714f29f627649e73409f4080a5acc606ed2004dc09d22ac2167427e11f8b75",
          "sha1": "5c2c61e44288b2d15832fecb51a473ed529be701",
          "md5": "f6594b62b9c63019e22230f863d83c73"
        }
      ]
    }
  ]
}
