{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rqes3m2sgvhgnc4lffhcdvyhsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.1.aar",
          "url": "ui-0.25.1.aar",
          "size": 827495,
          "sha512": "07176dcbbab7e9e3117424bd0213bf5eb68c8c1d8509609f732a63ebd5de1841d25dcee61711a990d0540a8e4cd145a74b50df2e4cd06bc8e6e7493e5c6e4841",
          "sha256": "a5488af3129f4d775e34b6efb657159a4c637edac0401a34fa3db89ae84fe781",
          "sha1": "2885ef96e924d02d2c27caa447050d18d5f6992c",
          "md5": "993f1d38751907c198459aff5ca2dad3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.1.aar",
          "url": "ui-0.25.1.aar",
          "size": 827495,
          "sha512": "07176dcbbab7e9e3117424bd0213bf5eb68c8c1d8509609f732a63ebd5de1841d25dcee61711a990d0540a8e4cd145a74b50df2e4cd06bc8e6e7493e5c6e4841",
          "sha256": "a5488af3129f4d775e34b6efb657159a4c637edac0401a34fa3db89ae84fe781",
          "sha1": "2885ef96e924d02d2c27caa447050d18d5f6992c",
          "md5": "993f1d38751907c198459aff5ca2dad3"
        }
      ]
    }
  ]
}
