{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7lbcxmreu5efzjhypj7uifm4pa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.31.1.aar",
          "url": "core-0.31.1.aar",
          "size": 324539,
          "sha512": "9fec610b8aed94c1464f39f6633929cc5f3ababedbbfabd307b23fd504ef9fd6a4e0142e2effa53d1881e5e27df6c8392028c31524384fca0d3d31d8fc4e4a94",
          "sha256": "9cd0bfe5dcda672310915abe405eab7edf8cde68a4274c59ab4fef9e3b468839",
          "sha1": "868ccd35508bff1772019e75d60d5af43d8d6ab6",
          "md5": "274fabae5409a8d47192a7ab843e3678"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.31.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.31.1.aar",
          "url": "core-0.31.1.aar",
          "size": 324539,
          "sha512": "9fec610b8aed94c1464f39f6633929cc5f3ababedbbfabd307b23fd504ef9fd6a4e0142e2effa53d1881e5e27df6c8392028c31524384fca0d3d31d8fc4e4a94",
          "sha256": "9cd0bfe5dcda672310915abe405eab7edf8cde68a4274c59ab4fef9e3b468839",
          "sha1": "868ccd35508bff1772019e75d60d5af43d8d6ab6",
          "md5": "274fabae5409a8d47192a7ab843e3678"
        }
      ]
    }
  ]
}
