{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.72.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.4.aar",
          "url": "core-0.72.4.aar",
          "size": 597293,
          "sha512": "c983a3b51a5b48d2b5b54c00b524e9e559c3b2b2fdf12e6d9c6581ae71c50c5332cd01eba87d5f3d20e75d89d626d91b64f45897c55fb9b8311761502c7f80f5",
          "sha256": "281e6c39f7a822d138107fba92c9e77f2957bccc81149f5de0ad783a50690ff5",
          "sha1": "d25aa049b469c744b1d06f9bc566cbf859023dfb",
          "md5": "73adf0e186a6f493f6b0d4d128e7ce7b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.4.aar",
          "url": "core-0.72.4.aar",
          "size": 597293,
          "sha512": "c983a3b51a5b48d2b5b54c00b524e9e559c3b2b2fdf12e6d9c6581ae71c50c5332cd01eba87d5f3d20e75d89d626d91b64f45897c55fb9b8311761502c7f80f5",
          "sha256": "281e6c39f7a822d138107fba92c9e77f2957bccc81149f5de0ad783a50690ff5",
          "sha1": "d25aa049b469c744b1d06f9bc566cbf859023dfb",
          "md5": "73adf0e186a6f493f6b0d4d128e7ce7b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.72.4-sources.jar",
          "url": "core-0.72.4-sources.jar",
          "size": 330589,
          "sha512": "05b7531d6f59f473a45eece287dc1ace2a2fb102bcc8ed0c95b0bdd2e5e46ffccf52fee7d18fc661786d46124d3e26a198ed7001b8bdfd348e0f99cefecf7477",
          "sha256": "63c18fcd94facd3fa0ec5e1f1c127c95e856e1d51dcf28c1f915648a7abdb540",
          "sha1": "a203df303c418992f99e743a2ae311a0918ef1a8",
          "md5": "0104b9475c398a5d8b5a450aced232a9"
        }
      ]
    }
  ]
}
