{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.33.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5ji7qh4ifbbd5j65vbqdkdc2ye"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.33.8.aar",
          "url": "ui-integration-0.33.8.aar",
          "size": 85095,
          "sha512": "9da6c047cf2fff09aa609c06db50318d34fbd05a470686bd5396d5dc7a93486a1c504e65b5ce30ed90c168e09fb3b4c3a769b6a8190595f6f15d012b8a730880",
          "sha256": "71594a89c6b0ce4053efe2ad0aea05ca108bc35644b5a43dc91a24be383fdc0b",
          "sha1": "54ef0a16b0900345e73a1afda9691a622d3f692d",
          "md5": "97d0fc8346975f12be947a8ad873eb3d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.33.8.aar",
          "url": "ui-integration-0.33.8.aar",
          "size": 85095,
          "sha512": "9da6c047cf2fff09aa609c06db50318d34fbd05a470686bd5396d5dc7a93486a1c504e65b5ce30ed90c168e09fb3b4c3a769b6a8190595f6f15d012b8a730880",
          "sha256": "71594a89c6b0ce4053efe2ad0aea05ca108bc35644b5a43dc91a24be383fdc0b",
          "sha1": "54ef0a16b0900345e73a1afda9691a622d3f692d",
          "md5": "97d0fc8346975f12be947a8ad873eb3d"
        }
      ]
    }
  ]
}
