{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "s65vb35x7bfmzam3aqmhkebzlm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0.aar",
          "url": "core-0.33.0.aar",
          "size": 327880,
          "sha512": "9caf7ab5941800cfb1d447d093f19c5d0c5bcd67d429e79c9f64ce2a237670b990b26bb4c827c88ed98cbcaa83719455d9e0c4ff0255a5628efd84ad5ec7e406",
          "sha256": "9bf43fa29aed9d3846bd8ff053c94788366c93972d2b7c20f17787f5674d4c48",
          "sha1": "459327dc76a2040b66ddb2c66bd68dd7741d2557",
          "md5": "10791fa58b63a1d6df78d7c55efc74b0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0.aar",
          "url": "core-0.33.0.aar",
          "size": 327880,
          "sha512": "9caf7ab5941800cfb1d447d093f19c5d0c5bcd67d429e79c9f64ce2a237670b990b26bb4c827c88ed98cbcaa83719455d9e0c4ff0255a5628efd84ad5ec7e406",
          "sha256": "9bf43fa29aed9d3846bd8ff053c94788366c93972d2b7c20f17787f5674d4c48",
          "sha1": "459327dc76a2040b66ddb2c66bd68dd7741d2557",
          "md5": "10791fa58b63a1d6df78d7c55efc74b0"
        }
      ]
    }
  ]
}
