{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4hiutxtlnjboni5ho6s4oitmpm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.1.aar",
          "url": "core-0.29.1.aar",
          "size": 286868,
          "sha512": "d5f66a2ee06f4a99d67ef1f910a0cb2caff4b6aad80635d9ef300a5e64a0a1dbc769439af5e5f6b164312f32c25b8e98772030a1f610d21cb234cefdd7b24029",
          "sha256": "81134329227abacf00dfcc9159b9e108c0552ab0441e59384c8bdd9d2f10251f",
          "sha1": "7cd4bfddea6edaefac285f089d1bcdf8a6aebedc",
          "md5": "549f89f593e3d77fa4c0c25b1e37383b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.1.aar",
          "url": "core-0.29.1.aar",
          "size": 286868,
          "sha512": "d5f66a2ee06f4a99d67ef1f910a0cb2caff4b6aad80635d9ef300a5e64a0a1dbc769439af5e5f6b164312f32c25b8e98772030a1f610d21cb234cefdd7b24029",
          "sha256": "81134329227abacf00dfcc9159b9e108c0552ab0441e59384c8bdd9d2f10251f",
          "sha1": "7cd4bfddea6edaefac285f089d1bcdf8a6aebedc",
          "md5": "549f89f593e3d77fa4c0c25b1e37383b"
        }
      ]
    }
  ]
}
