{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.31.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jzpu23fbyrgxji2shb5gg6dx6m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.31.3.aar",
          "url": "firebase-detector-0.31.3.aar",
          "size": 32737,
          "sha512": "9d8aa64d242336a907c23dc1b98234be970bb81fb97c2a0c07ab857a0c81f2bc60532acb532614a487525e7e5e5e568cb4ef3e853c21e034702b6569e1719f66",
          "sha256": "b8f026d667a9befc56e6ddee6bbb272dbb83880dfb12ce1f48103b877fbd0972",
          "sha1": "3e3366485844d77b175bce3b8e40690a064bdaca",
          "md5": "f7bee4cce401bd5ac5d8c9864be85c40"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.31.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.31.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.31.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.31.3.aar",
          "url": "firebase-detector-0.31.3.aar",
          "size": 32737,
          "sha512": "9d8aa64d242336a907c23dc1b98234be970bb81fb97c2a0c07ab857a0c81f2bc60532acb532614a487525e7e5e5e568cb4ef3e853c21e034702b6569e1719f66",
          "sha256": "b8f026d667a9befc56e6ddee6bbb272dbb83880dfb12ce1f48103b877fbd0972",
          "sha1": "3e3366485844d77b175bce3b8e40690a064bdaca",
          "md5": "f7bee4cce401bd5ac5d8c9864be85c40"
        }
      ]
    }
  ]
}
