{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.30.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "iznr6wigofczhg5nhsz32yhe34"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.30.1.aar",
          "url": "ui-integration-0.30.1.aar",
          "size": 74897,
          "sha512": "f7511eda01d9124ce8a496049fe2a030aabeafe2ed3a88c1a31995b850de32a3425e282cc0397bed5fc7987111c4b7cdb4893b6207fefa99de4f13ea324514a2",
          "sha256": "8c707227bb7380bc4b92c333397cbc2f6e14b2be78f01b39e144231e4f444026",
          "sha1": "37cb67c570cb9b20e70ca115df8bee59ed3aed7f",
          "md5": "7e5051c5e551e40fd03ac4cdcbf4f3bc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.30.1.aar",
          "url": "ui-integration-0.30.1.aar",
          "size": 74897,
          "sha512": "f7511eda01d9124ce8a496049fe2a030aabeafe2ed3a88c1a31995b850de32a3425e282cc0397bed5fc7987111c4b7cdb4893b6207fefa99de4f13ea324514a2",
          "sha256": "8c707227bb7380bc4b92c333397cbc2f6e14b2be78f01b39e144231e4f444026",
          "sha1": "37cb67c570cb9b20e70ca115df8bee59ed3aed7f",
          "md5": "7e5051c5e551e40fd03ac4cdcbf4f3bc"
        }
      ]
    }
  ]
}
