{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aydwdnwrmvadtl4tg6ddrru2ru"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta01.aar",
          "url": "core-0.33.0-beta01.aar",
          "size": 327611,
          "sha512": "f80bae6f6c9a2a6c3904fe178d0fab295ee150e6b12e114001ad1289fd672aa8188dca8fa44a79159d23f80e0e43580a5703cddff225f62fbb4fa62542c5c63c",
          "sha256": "afecc4997d85ce157d36eb0b188d006ce523d92e448378d5f68724850bd942de",
          "sha1": "74717c4dd8e660f621faea8bb78bfc1dfe199f60",
          "md5": "7816b0f7ba78b64f1c0381251b664737"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0-beta01"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta01.aar",
          "url": "core-0.33.0-beta01.aar",
          "size": 327611,
          "sha512": "f80bae6f6c9a2a6c3904fe178d0fab295ee150e6b12e114001ad1289fd672aa8188dca8fa44a79159d23f80e0e43580a5703cddff225f62fbb4fa62542c5c63c",
          "sha256": "afecc4997d85ce157d36eb0b188d006ce523d92e448378d5f68724850bd942de",
          "sha1": "74717c4dd8e660f621faea8bb78bfc1dfe199f60",
          "md5": "7816b0f7ba78b64f1c0381251b664737"
        }
      ]
    }
  ]
}
