{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.32.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qeqbi3g545eufpvlpatg4x7knu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.32.10.aar",
          "url": "ui-0.32.10.aar",
          "size": 856606,
          "sha512": "af3835825207e224c84b4b01bf2ee265bee575186d7b5c99cdb7847388deff9a6223a96fbf9b78ee8f038658713efca5ee2bec3ad219cb487f49b2c826836608",
          "sha256": "30dda916e0eb4b7f5c2a6e193b6c9916561142ffd9466734014b9a6c0c0e3097",
          "sha1": "05d2efa44dcd3069a8ca0e95181d9b9824ecf8ac",
          "md5": "563c688e2191d6a56f3b464ac594e09b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.32.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.32.10.aar",
          "url": "ui-0.32.10.aar",
          "size": 856606,
          "sha512": "af3835825207e224c84b4b01bf2ee265bee575186d7b5c99cdb7847388deff9a6223a96fbf9b78ee8f038658713efca5ee2bec3ad219cb487f49b2c826836608",
          "sha256": "30dda916e0eb4b7f5c2a6e193b6c9916561142ffd9466734014b9a6c0c0e3097",
          "sha1": "05d2efa44dcd3069a8ca0e95181d9b9824ecf8ac",
          "md5": "563c688e2191d6a56f3b464ac594e09b"
        }
      ]
    }
  ]
}
