{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.29.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7xnk7aj5prhfvhghio4a2dcuqq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.5.aar",
          "url": "firebase-detector-0.29.5.aar",
          "size": 32730,
          "sha512": "bfdda7ecfb10d8b8b971f1b2df0849193d1c936fdc70f9519114bde0946d7d13878f9d1cd776d62346b008d8fac9f57401150122a5d87a14dd96a9d8d4e95217",
          "sha256": "6067cf3b98034c1832e8ef279a902888c9fe9296b622fe32b3cba759f974481d",
          "sha1": "22dab38e7e4e41e47d840d1b7cd4b15738df2b57",
          "md5": "dfa49315b39db823be230809b3a00097"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.5"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.29.5.aar",
          "url": "firebase-detector-0.29.5.aar",
          "size": 32730,
          "sha512": "bfdda7ecfb10d8b8b971f1b2df0849193d1c936fdc70f9519114bde0946d7d13878f9d1cd776d62346b008d8fac9f57401150122a5d87a14dd96a9d8d4e95217",
          "sha256": "6067cf3b98034c1832e8ef279a902888c9fe9296b622fe32b3cba759f974481d",
          "sha1": "22dab38e7e4e41e47d840d1b7cd4b15738df2b57",
          "md5": "dfa49315b39db823be230809b3a00097"
        }
      ]
    }
  ]
}
