{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rfqf4voamrakla574yho3mucwu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.11.aar",
          "url": "utils-0.32.11.aar",
          "size": 42927,
          "sha512": "18fcf1c0537f29077348ba2cc7241d48a5de5969f9d82e70444ee80d55a0497e37a313ef37ab03db2afc029dfac2bc92828265c5f0c488a69a12622d4cee25c0",
          "sha256": "5a8f6904206f5995a88a6e70282639539e5e874e361050c27fd3924449123c83",
          "sha1": "36e77465a380134b28b9549008bd36224c2d7bc7",
          "md5": "92b277c470790f6b8912dc9ff30f30db"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.11.aar",
          "url": "utils-0.32.11.aar",
          "size": 42927,
          "sha512": "18fcf1c0537f29077348ba2cc7241d48a5de5969f9d82e70444ee80d55a0497e37a313ef37ab03db2afc029dfac2bc92828265c5f0c488a69a12622d4cee25c0",
          "sha256": "5a8f6904206f5995a88a6e70282639539e5e874e361050c27fd3924449123c83",
          "sha1": "36e77465a380134b28b9549008bd36224c2d7bc7",
          "md5": "92b277c470790f6b8912dc9ff30f30db"
        }
      ]
    }
  ]
}
