{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.71.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.5.aar",
          "url": "core-0.71.5.aar",
          "size": 591507,
          "sha512": "063404df0df807c212444468ef8e198fc7af796b0b897bf04408333c14017c73da15ce8fcd18cedc4d3557a57e08cb342d68574fc5fd5308cd23686e1400cc5b",
          "sha256": "c9cff4a828ec28f14da30b73ae34d2960748861ca85dd3ef44682c5657ccd9b2",
          "sha1": "7cd142e7b2511cefd71be63be281760ec3ab446a",
          "md5": "2d3494bd238784c97074b65cafe6016d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.5.aar",
          "url": "core-0.71.5.aar",
          "size": 591507,
          "sha512": "063404df0df807c212444468ef8e198fc7af796b0b897bf04408333c14017c73da15ce8fcd18cedc4d3557a57e08cb342d68574fc5fd5308cd23686e1400cc5b",
          "sha256": "c9cff4a828ec28f14da30b73ae34d2960748861ca85dd3ef44682c5657ccd9b2",
          "sha1": "7cd142e7b2511cefd71be63be281760ec3ab446a",
          "md5": "2d3494bd238784c97074b65cafe6016d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.71.5-sources.jar",
          "url": "core-0.71.5-sources.jar",
          "size": 327567,
          "sha512": "8bc5f0d6d9caf59e355b36ab56eb15d12a321582345c76bab757e5ec803648486776f9efdf896d1abd9645a913af030bcc992277205a3b93a3a1e493b0e48ed8",
          "sha256": "9aae260d412d7a5305bd8525f95aaa363709e76781eae6b3c0c42d429047e1fa",
          "sha1": "91c59eda370fa26ab374fcf2e46c1fd26928ac2c",
          "md5": "4a656e1038f2d93f8a1bd7eeefe57cef"
        }
      ]
    }
  ]
}
