{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.25.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rkljdfyjprg7dfj4iu6ixfix24"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-detector-0.25.7.aar",
          "url": "firebase-detector-0.25.7.aar",
          "size": 31218,
          "sha512": "ebfb55d409cf3ab95b213a494a6f17a2c762ca91fb4d59398346fbe2f44841aa02bea697d56772bba73b2df71d3744fb88610824fb0fba925ae3a2e9b8877883",
          "sha256": "d879350332cdfbfe16d607d127a74fd9863aee4b0e5693988bc2787841993d2f",
          "sha1": "fe7beb952bfa0aff24eb2e8d8546019eca4639f9",
          "md5": "a089b042f425093b7eca15c12322be10"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.25.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.25.7.aar",
          "url": "firebase-detector-0.25.7.aar",
          "size": 31218,
          "sha512": "ebfb55d409cf3ab95b213a494a6f17a2c762ca91fb4d59398346fbe2f44841aa02bea697d56772bba73b2df71d3744fb88610824fb0fba925ae3a2e9b8877883",
          "sha256": "d879350332cdfbfe16d607d127a74fd9863aee4b0e5693988bc2787841993d2f",
          "sha1": "fe7beb952bfa0aff24eb2e8d8546019eca4639f9",
          "md5": "a089b042f425093b7eca15c12322be10"
        }
      ]
    }
  ]
}
