{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.37.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "j73tkzcztbhkvlczx3y37vmb5a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.1.aar",
          "url": "core-0.37.1.aar",
          "size": 351956,
          "sha512": "30da1c1f00df54bb9c54dee45f51c87151cac61ffdda2c386bc2421b619251497bbf9381f19e7452f29c62b14469fe2895c92105b42e4547dddc1558d9e32100",
          "sha256": "2f85ef66aa6222de233d51fe291fcd5a41a029768496c8904664c7130d41849e",
          "sha1": "d420221704f3979de98a3d27a7abd0db94b2a3de",
          "md5": "3139d61a7a14b868348ff0b149d5c14b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.1.aar",
          "url": "core-0.37.1.aar",
          "size": 351956,
          "sha512": "30da1c1f00df54bb9c54dee45f51c87151cac61ffdda2c386bc2421b619251497bbf9381f19e7452f29c62b14469fe2895c92105b42e4547dddc1558d9e32100",
          "sha256": "2f85ef66aa6222de233d51fe291fcd5a41a029768496c8904664c7130d41849e",
          "sha1": "d420221704f3979de98a3d27a7abd0db94b2a3de",
          "md5": "3139d61a7a14b868348ff0b149d5c14b"
        }
      ]
    }
  ]
}
