{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.47.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.47.2.aar",
          "url": "ui-integration-0.47.2.aar",
          "size": 100587,
          "sha512": "1eb3bea1d301377011fe1883ebf272d0a6e6e485c3de2febb3c662a049738d58dab0c57871020a9ae0429ac96dfef77671af51e321d43209b5dd459be91028b1",
          "sha256": "5f106562b7cc9fc9fc55b9ee8f662a5708dc99558ccdff6056e355c731adbbbe",
          "sha1": "36a9d5d2cc54dc12c27e215c460b860bf06182e8",
          "md5": "c9b065a7e051c992a1a467cc8411a115"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.47.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.47.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.47.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.47.2.aar",
          "url": "ui-integration-0.47.2.aar",
          "size": 100587,
          "sha512": "1eb3bea1d301377011fe1883ebf272d0a6e6e485c3de2febb3c662a049738d58dab0c57871020a9ae0429ac96dfef77671af51e321d43209b5dd459be91028b1",
          "sha256": "5f106562b7cc9fc9fc55b9ee8f662a5708dc99558ccdff6056e355c731adbbbe",
          "sha1": "36a9d5d2cc54dc12c27e215c460b860bf06182e8",
          "md5": "c9b065a7e051c992a1a467cc8411a115"
        }
      ]
    }
  ]
}
