{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.45.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.45.0.aar",
          "url": "core-0.45.0.aar",
          "size": 390017,
          "sha512": "762501937e29278a3236af73e7a381d7aaef69ff8baae0b06c83aa0b07f2d450f10b3a51e6faa4b831ee397773675344dc7f1acea323142d47116232ab14abd3",
          "sha256": "d2e1460ba99967470163f9e8b52a1c6907743cfe74e3db670ab26bedde01b486",
          "sha1": "28e8916f25fdbfa0bab4c7545be8159d607126eb",
          "md5": "2029217b0047cdf674060f33d06e5296"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.45.0.aar",
          "url": "core-0.45.0.aar",
          "size": 390017,
          "sha512": "762501937e29278a3236af73e7a381d7aaef69ff8baae0b06c83aa0b07f2d450f10b3a51e6faa4b831ee397773675344dc7f1acea323142d47116232ab14abd3",
          "sha256": "d2e1460ba99967470163f9e8b52a1c6907743cfe74e3db670ab26bedde01b486",
          "sha1": "28e8916f25fdbfa0bab4c7545be8159d607126eb",
          "md5": "2029217b0047cdf674060f33d06e5296"
        }
      ]
    }
  ]
}
