{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dax35mg2nreplfqoglg2jm2bzu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.2.aar",
          "url": "utils-0.33.2.aar",
          "size": 42945,
          "sha512": "007d3ab17b4210fd98c9bef72302b51712ce853d5ab43515449d5dab97af247bde3584f32550df533f06a64323c19db3ecc1edb4e9bd9dd4f98681f9c4bb15dc",
          "sha256": "0f78e8f79d8f0528dd1b72641d18fae19410dec0646080a2f3b387959762696d",
          "sha1": "6917bbd8252cea12ad6ae93241471ad9daaa49ce",
          "md5": "1e9f7c996b57efe4a56ac016775708e3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.2.aar",
          "url": "utils-0.33.2.aar",
          "size": 42945,
          "sha512": "007d3ab17b4210fd98c9bef72302b51712ce853d5ab43515449d5dab97af247bde3584f32550df533f06a64323c19db3ecc1edb4e9bd9dd4f98681f9c4bb15dc",
          "sha256": "0f78e8f79d8f0528dd1b72641d18fae19410dec0646080a2f3b387959762696d",
          "sha1": "6917bbd8252cea12ad6ae93241471ad9daaa49ce",
          "md5": "1e9f7c996b57efe4a56ac016775708e3"
        }
      ]
    }
  ]
}
