{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.35.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kazzgux75bbcrkp2m3hgsyf7xa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.5.aar",
          "url": "firebase-detector-0.35.5.aar",
          "size": 41009,
          "sha512": "d788a1c8fd6bf37b92bc649827cec9a72f2ed59f5599c956643f9e5e30aaa6ff8c59d8bc1321ab2a0e49d19c1cfec2cbc4ac98f09cf33ec98c67911cca2a2b17",
          "sha256": "90439cd826c3de93b0d609ef177b7debe2105d1da1072918316ba24418774010",
          "sha1": "8ea4ce150fdaa4f7ddf3a6cdb560654bb3805695",
          "md5": "1521af6b653675ff87453b065660e438"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.5.aar",
          "url": "firebase-detector-0.35.5.aar",
          "size": 41009,
          "sha512": "d788a1c8fd6bf37b92bc649827cec9a72f2ed59f5599c956643f9e5e30aaa6ff8c59d8bc1321ab2a0e49d19c1cfec2cbc4ac98f09cf33ec98c67911cca2a2b17",
          "sha256": "90439cd826c3de93b0d609ef177b7debe2105d1da1072918316ba24418774010",
          "sha1": "8ea4ce150fdaa4f7ddf3a6cdb560654bb3805695",
          "md5": "1521af6b653675ff87453b065660e438"
        }
      ]
    }
  ]
}
