{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rfqf4voamrakla574yho3mucwu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.11.aar",
          "url": "core-0.32.11.aar",
          "size": 326355,
          "sha512": "722d619cda028e0ba44d868a09993da20908d098e8a1d128fbb6cd91521da6959b7e087e4c76803f4fef4de7cdbce4bf82d3d46f9d83fd6f99353fb40e219afb",
          "sha256": "421f2757a00c3cc107387a0f241fb6a8942819e15a6cdcf37cdbc5386f6ef3db",
          "sha1": "4f4bc940497c3a7f0e1bfd7eba6db9498a62c8eb",
          "md5": "c69d87b021ae6ceaa2c6a450c62fab85"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.11"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.11.aar",
          "url": "core-0.32.11.aar",
          "size": 326355,
          "sha512": "722d619cda028e0ba44d868a09993da20908d098e8a1d128fbb6cd91521da6959b7e087e4c76803f4fef4de7cdbce4bf82d3d46f9d83fd6f99353fb40e219afb",
          "sha256": "421f2757a00c3cc107387a0f241fb6a8942819e15a6cdcf37cdbc5386f6ef3db",
          "sha1": "4f4bc940497c3a7f0e1bfd7eba6db9498a62c8eb",
          "md5": "c69d87b021ae6ceaa2c6a450c62fab85"
        }
      ]
    }
  ]
}
