{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "acxx2gn7n5fr7nevplpysjnl3m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.8.aar",
          "url": "core-0.32.8.aar",
          "size": 326044,
          "sha512": "45ae351ffcc8626cb169c891a885c857ab8667bfa66b7eeee5d67497d199dd1f17c9fb311d2d56bc059c3de966d3654a2835d3a71c7432d2a0abd22c383d0f3a",
          "sha256": "c7b6157cbf54cec16b3eef8c4ffba23ec2a6f9d5835bc10c175d4e78000d06f7",
          "sha1": "8a4448e32d1a00b14fa6a1eba367ed27a2e29234",
          "md5": "193e54d492dadb190b1ce00acb2b0893"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.8.aar",
          "url": "core-0.32.8.aar",
          "size": 326044,
          "sha512": "45ae351ffcc8626cb169c891a885c857ab8667bfa66b7eeee5d67497d199dd1f17c9fb311d2d56bc059c3de966d3654a2835d3a71c7432d2a0abd22c383d0f3a",
          "sha256": "c7b6157cbf54cec16b3eef8c4ffba23ec2a6f9d5835bc10c175d4e78000d06f7",
          "sha1": "8a4448e32d1a00b14fa6a1eba367ed27a2e29234",
          "md5": "193e54d492dadb190b1ce00acb2b0893"
        }
      ]
    }
  ]
}
