{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r5jlfxzouzffviprjrzm3wrs74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta03.aar",
          "url": "core-0.33.0-beta03.aar",
          "size": 327612,
          "sha512": "f5c05419635ed8768fabb344886516cc988fae5dfc29b40f3dbdbb09eff457339e765bee026784b82400dca712453c7a8f5496eef3ad2263f73c63afb3f8b68e",
          "sha256": "4d101286e2a8a6d9b0f98e8808fa522483843057cf9ef634ad26045ab9962f54",
          "sha1": "5b9e3bbe2e2793d8675ded4a72fd177dffb00fea",
          "md5": "c29a20b9a9a25e163784f26f1cc5b151"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0-beta03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta03.aar",
          "url": "core-0.33.0-beta03.aar",
          "size": 327612,
          "sha512": "f5c05419635ed8768fabb344886516cc988fae5dfc29b40f3dbdbb09eff457339e765bee026784b82400dca712453c7a8f5496eef3ad2263f73c63afb3f8b68e",
          "sha256": "4d101286e2a8a6d9b0f98e8808fa522483843057cf9ef634ad26045ab9962f54",
          "sha1": "5b9e3bbe2e2793d8675ded4a72fd177dffb00fea",
          "md5": "c29a20b9a9a25e163784f26f1cc5b151"
        }
      ]
    }
  ]
}
