{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2mmy334x4nhtlkd2frlsxm2xjy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.7.aar",
          "url": "utils-0.33.7.aar",
          "size": 42946,
          "sha512": "d96e0752c018b9f521df12b99ae93e5cd568a610d22e92d100743007abafc9908f11e62b79ed87273a506db724a7d62239e45f9a52ad64239bd3d63151b58616",
          "sha256": "319b7ddc69658fc1f5b1952e04b01fda038675a1da84c0190b4f2dd32e622b85",
          "sha1": "b793cd6f24df297f92a18ef2ff6e444db3b03cce",
          "md5": "aefa94ca84018ebb75e187255919af68"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.7.aar",
          "url": "utils-0.33.7.aar",
          "size": 42946,
          "sha512": "d96e0752c018b9f521df12b99ae93e5cd568a610d22e92d100743007abafc9908f11e62b79ed87273a506db724a7d62239e45f9a52ad64239bd3d63151b58616",
          "sha256": "319b7ddc69658fc1f5b1952e04b01fda038675a1da84c0190b4f2dd32e622b85",
          "sha1": "b793cd6f24df297f92a18ef2ff6e444db3b03cce",
          "md5": "aefa94ca84018ebb75e187255919af68"
        }
      ]
    }
  ]
}
