{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "0.73.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.73.0.aar",
          "url": "accessibility-toolbox-0.73.0.aar",
          "size": 25330,
          "sha512": "b0fd7681c529c30ae9496cc2eae20c5e42e1a134606afc163bee7d9a39ad14aa350d429780406bb23fbe2ac5c58862b3a996b9fcdebf2b13db9c671cd29e99f8",
          "sha256": "ecd7d195bf81d8099975b6bd923a1e218034dcf97fa455c0ce8752f6a4fb4909",
          "sha1": "c19e6c42e5224d5a2af9c9302c10a7a31ce8d669",
          "md5": "bdb58678b501ce7ec3ea824c625d0893"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.73.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.73.0.aar",
          "url": "accessibility-toolbox-0.73.0.aar",
          "size": 25330,
          "sha512": "b0fd7681c529c30ae9496cc2eae20c5e42e1a134606afc163bee7d9a39ad14aa350d429780406bb23fbe2ac5c58862b3a996b9fcdebf2b13db9c671cd29e99f8",
          "sha256": "ecd7d195bf81d8099975b6bd923a1e218034dcf97fa455c0ce8752f6a4fb4909",
          "sha1": "c19e6c42e5224d5a2af9c9302c10a7a31ce8d669",
          "md5": "bdb58678b501ce7ec3ea824c625d0893"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "accessibility-toolbox-0.73.0-sources.jar",
          "url": "accessibility-toolbox-0.73.0-sources.jar",
          "size": 10295,
          "sha512": "5cd29f4679905852d3b741cab239637196dccba323905c9fe947558f3a8e62bd0b26a00d2d2bb061b568f3faff12727b6c27c32d970552f771c22982f80e67c7",
          "sha256": "26c23b54c32a953d82ff453d1871c552d9ecf3928458ebfaf3991c5f5c9692fd",
          "sha1": "e16662017954d97e50f42be15de5f88d1b3a235a",
          "md5": "f430e93992df8383536f3605cfca7c82"
        }
      ]
    }
  ]
}
