{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.79.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.79.0.aar",
          "url": "mlkit-scanner-engine-0.79.0.aar",
          "size": 63880,
          "sha512": "d13ae92d4816bd941cbff3648e5273106f0c6589bc8fd8c3b72cc83fb04dd38bd02d262d374dab3bfb4c4ad8e7826bd0119871ceeea837998f814303d2c903b2",
          "sha256": "8bb50eb9c3a411096af0d86b96814455dd0f5a2f7073cabee8f92df0c8bf3194",
          "sha1": "79b86a9917205163695183c8132c021df2100fe9",
          "md5": "d707fdb9cbe1f93ef7731d4d5b60b3ca"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.79.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.79.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.79.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.79.0.aar",
          "url": "mlkit-scanner-engine-0.79.0.aar",
          "size": 63880,
          "sha512": "d13ae92d4816bd941cbff3648e5273106f0c6589bc8fd8c3b72cc83fb04dd38bd02d262d374dab3bfb4c4ad8e7826bd0119871ceeea837998f814303d2c903b2",
          "sha256": "8bb50eb9c3a411096af0d86b96814455dd0f5a2f7073cabee8f92df0c8bf3194",
          "sha1": "79b86a9917205163695183c8132c021df2100fe9",
          "md5": "d707fdb9cbe1f93ef7731d4d5b60b3ca"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.79.0-sources.jar",
          "url": "mlkit-scanner-engine-0.79.0-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
