{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "u2shwelgpvbononkksnwr4sgra"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.2.aar",
          "url": "ui-integration-0.29.2.aar",
          "size": 74889,
          "sha512": "207911f9b33f22e692f2cda480d72d4dd5f47c21dc7fd612796ffe97d2de7bbb6219542a4a1a63aff2fc7be93ad2d95c09f78b543ab14fcf1da9091c45eb82f5",
          "sha256": "4b2f85e03cafbb04b45539f28eaeedbc28a9d4192db8eb81f6ef3a477fd55842",
          "sha1": "e59b0e4b95679d94fdb72e92a66aac5f3fbfa863",
          "md5": "f74ddf95f9aab0e2d2dcd8491bd576b4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.2.aar",
          "url": "ui-integration-0.29.2.aar",
          "size": 74889,
          "sha512": "207911f9b33f22e692f2cda480d72d4dd5f47c21dc7fd612796ffe97d2de7bbb6219542a4a1a63aff2fc7be93ad2d95c09f78b543ab14fcf1da9091c45eb82f5",
          "sha256": "4b2f85e03cafbb04b45539f28eaeedbc28a9d4192db8eb81f6ef3a477fd55842",
          "sha1": "e59b0e4b95679d94fdb72e92a66aac5f3fbfa863",
          "md5": "f74ddf95f9aab0e2d2dcd8491bd576b4"
        }
      ]
    }
  ]
}
