{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.24.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yt4eqxsagbcyhhutfgbe25fnsm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.24.7.aar",
          "url": "ui-0.24.7.aar",
          "size": 804512,
          "sha512": "5b128bc8eee3de69cf0bbe3d3450928c5eac0fa635e409565b0fd8e886e23d26a224f94f01ef2b015f29212ecbb38cd8e153447b56c531967a252958af3fa3cb",
          "sha256": "6c0a233dab4e5e9c74a3f60b7b438d3a168c9f22da113719121f00b6c9b8c14d",
          "sha1": "d629f60e7812dbfc3a7380c55f3483e2340d755d",
          "md5": "781960b558f4740db1ffaa1b7340e56b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.24.7"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.24.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.24.7.aar",
          "url": "ui-0.24.7.aar",
          "size": 804512,
          "sha512": "5b128bc8eee3de69cf0bbe3d3450928c5eac0fa635e409565b0fd8e886e23d26a224f94f01ef2b015f29212ecbb38cd8e153447b56c531967a252958af3fa3cb",
          "sha256": "6c0a233dab4e5e9c74a3f60b7b438d3a168c9f22da113719121f00b6c9b8c14d",
          "sha1": "d629f60e7812dbfc3a7380c55f3483e2340d755d",
          "md5": "781960b558f4740db1ffaa1b7340e56b"
        }
      ]
    }
  ]
}
