{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.25.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jdjaink725hpjcqmmejphu4w7m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.5.aar",
          "url": "core-0.25.5.aar",
          "size": 272385,
          "sha512": "f96e5247527aa42806f8ddd371e2754e21aa90135e2756e1bd529481d9ed1e27c1048fc08438ba6e15916589603fd23eb51876f83809f75704012bf5c1be62d7",
          "sha256": "f581fb27a2e18f5967e55649fc771a872f1c83d56c9b2cf2a180aef0ac22375e",
          "sha1": "f301ff6d9d7a5eade9910daa79e86c3c614f4308",
          "md5": "ef82674a01bd19ea98cccaf0425fc615"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.5.aar",
          "url": "core-0.25.5.aar",
          "size": 272385,
          "sha512": "f96e5247527aa42806f8ddd371e2754e21aa90135e2756e1bd529481d9ed1e27c1048fc08438ba6e15916589603fd23eb51876f83809f75704012bf5c1be62d7",
          "sha256": "f581fb27a2e18f5967e55649fc771a872f1c83d56c9b2cf2a180aef0ac22375e",
          "sha1": "f301ff6d9d7a5eade9910daa79e86c3c614f4308",
          "md5": "ef82674a01bd19ea98cccaf0425fc615"
        }
      ]
    }
  ]
}
