{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i5laplrhrfahll6lxbe7a4qkqm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.0.aar",
          "url": "utils-0.32.0.aar",
          "size": 42927,
          "sha512": "89e12420a85c5f05bf17727c5ff79462abfab2fef60b491c2ea025eef59aba982e0a36a40913ca08e6446faa3854725bd00dac695198889dfe7ed74eb0e5a29a",
          "sha256": "2ed1f49a06e9ad0b453861792eb566095aa8e2897c76f45a8bf551fc8faaf999",
          "sha1": "2d5095cba6cda22351c1a8f95ce02265e1fb8782",
          "md5": "a295d2cb126abd4177a5dc1093ab13a3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.0.aar",
          "url": "utils-0.32.0.aar",
          "size": 42927,
          "sha512": "89e12420a85c5f05bf17727c5ff79462abfab2fef60b491c2ea025eef59aba982e0a36a40913ca08e6446faa3854725bd00dac695198889dfe7ed74eb0e5a29a",
          "sha256": "2ed1f49a06e9ad0b453861792eb566095aa8e2897c76f45a8bf551fc8faaf999",
          "sha1": "2d5095cba6cda22351c1a8f95ce02265e1fb8782",
          "md5": "a295d2cb126abd4177a5dc1093ab13a3"
        }
      ]
    }
  ]
}
