{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.43.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.43.1.aar",
          "url": "firebase-detector-0.43.1.aar",
          "size": 44874,
          "sha512": "45217effc3c148060674f707c1a89379212feb8492611a1f090779fad541c95932e97d4f333558b4b5a5ad83cef0fa6c2cc0ea04fe55d220d9cd3899f0af4e6b",
          "sha256": "b7f4d3fb1a9067b770e6d686528dd07b0b994bd3ffd623c100d5e05803590862",
          "sha1": "f044ac064ccef06834aa6db6f282f9eb6d45471e",
          "md5": "6d879530daed7515bbc61d34534f4651"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.43.1.aar",
          "url": "firebase-detector-0.43.1.aar",
          "size": 44874,
          "sha512": "45217effc3c148060674f707c1a89379212feb8492611a1f090779fad541c95932e97d4f333558b4b5a5ad83cef0fa6c2cc0ea04fe55d220d9cd3899f0af4e6b",
          "sha256": "b7f4d3fb1a9067b770e6d686528dd07b0b994bd3ffd623c100d5e05803590862",
          "sha1": "f044ac064ccef06834aa6db6f282f9eb6d45471e",
          "md5": "6d879530daed7515bbc61d34534f4651"
        }
      ]
    }
  ]
}
