{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dyzxkmtlm5g6dgcrd6zzdd3d4i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.1.aar",
          "url": "core-0.33.1.aar",
          "size": 327884,
          "sha512": "655ff2f6897ca7d684cf2ee599206abb9564e2a28cd986be6ac63c4e0951d6a1d22cfd2c31a85eb91f7d28aaebc8e8aa1f89cf6dc0af2609fb5958664285425f",
          "sha256": "fa904d069e087ba96cc71d60443dede553d2e71a8c11bb13424d5959c4da0ded",
          "sha1": "f5de227cb6b171991d99234e616f4518b77c8b1f",
          "md5": "89c5f4bc0fab8cf9b137609b9c083381"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.1.aar",
          "url": "core-0.33.1.aar",
          "size": 327884,
          "sha512": "655ff2f6897ca7d684cf2ee599206abb9564e2a28cd986be6ac63c4e0951d6a1d22cfd2c31a85eb91f7d28aaebc8e8aa1f89cf6dc0af2609fb5958664285425f",
          "sha256": "fa904d069e087ba96cc71d60443dede553d2e71a8c11bb13424d5959c4da0ded",
          "sha1": "f5de227cb6b171991d99234e616f4518b77c8b1f",
          "md5": "89c5f4bc0fab8cf9b137609b9c083381"
        }
      ]
    }
  ]
}
