{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.34.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lvmr4jriefdfvavosqfoft2d74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.34.1.aar",
          "url": "firebase-detector-0.34.1.aar",
          "size": 40781,
          "sha512": "2c860feb53214806e7cb46cc80134c10074f9060b293273ae8de92bcdddd1f6f9ab45ab28047f181f3f97289342c220d0913c76de3d947b8c1846527eaf7c826",
          "sha256": "4fd021c84948d6148cb2a80d6cbfac7aac9dab29c9c8c05d2b22c1632a789a47",
          "sha1": "5f38d22bbfd6558ad07555d4b15bf03a8584a319",
          "md5": "dc4851cd3636c04954528d29885fc4c9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.34.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.34.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.34.1.aar",
          "url": "firebase-detector-0.34.1.aar",
          "size": 40781,
          "sha512": "2c860feb53214806e7cb46cc80134c10074f9060b293273ae8de92bcdddd1f6f9ab45ab28047f181f3f97289342c220d0913c76de3d947b8c1846527eaf7c826",
          "sha256": "4fd021c84948d6148cb2a80d6cbfac7aac9dab29c9c8c05d2b22c1632a789a47",
          "sha1": "5f38d22bbfd6558ad07555d4b15bf03a8584a319",
          "md5": "dc4851cd3636c04954528d29885fc4c9"
        }
      ]
    }
  ]
}
