{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "s65vb35x7bfmzam3aqmhkebzlm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.0.aar",
          "url": "utils-0.33.0.aar",
          "size": 42944,
          "sha512": "c09b40e8e683f2315228d88554fcd28e0cf1b88ed0ae4e5a48fc839d66e00089109a0d8156889a8f7c64ad3bc3934bbb3f255ec3556a8909af6b894bd596c0b3",
          "sha256": "134085d20d9ac700ec2a1eb6e4fd76893706393566737765db2ed2013cc21c12",
          "sha1": "f62cc000a48efb34a9c10f720b0293539e276971",
          "md5": "43e68cfe548e523753d9bf6c09169b73"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.0.aar",
          "url": "utils-0.33.0.aar",
          "size": 42944,
          "sha512": "c09b40e8e683f2315228d88554fcd28e0cf1b88ed0ae4e5a48fc839d66e00089109a0d8156889a8f7c64ad3bc3934bbb3f255ec3556a8909af6b894bd596c0b3",
          "sha256": "134085d20d9ac700ec2a1eb6e4fd76893706393566737765db2ed2013cc21c12",
          "sha1": "f62cc000a48efb34a9c10f720b0293539e276971",
          "md5": "43e68cfe548e523753d9bf6c09169b73"
        }
      ]
    }
  ]
}
