{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.2.2.aar",
          "url": "core-3.2.2.aar",
          "size": 155071,
          "sha512": "11bd11aa44c878b73f3f5d4505caa358de7ac3c671f45b8394f692dd6b0f6f4322cac0261279d4241faadd6513991cb7329a03712aa798eb9fa69577824584f4",
          "sha256": "b57885fb9cc3ba6fc6ee0bde400407277f59a3cff61518a61bae4ec1064fd5e8",
          "sha1": "6c8a67a1b77ea762c6aabe9cfd43b38835fb68a0",
          "md5": "40a2d26d3d6ae97e1bd38e84a81c66ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.2.2.aar",
          "url": "core-3.2.2.aar",
          "size": 155071,
          "sha512": "11bd11aa44c878b73f3f5d4505caa358de7ac3c671f45b8394f692dd6b0f6f4322cac0261279d4241faadd6513991cb7329a03712aa798eb9fa69577824584f4",
          "sha256": "b57885fb9cc3ba6fc6ee0bde400407277f59a3cff61518a61bae4ec1064fd5e8",
          "sha1": "6c8a67a1b77ea762c6aabe9cfd43b38835fb68a0",
          "md5": "40a2d26d3d6ae97e1bd38e84a81c66ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.2.2-sources.jar",
          "url": "core-3.2.2-sources.jar",
          "size": 28118,
          "sha512": "2b09e4582b8b1794bddcf3124fcc1931d43afd59c36b241fc56955f0ab658344dcb1d405d5d688cc70848881b466eadc547af95f96439db88b42bcd5d1efb125",
          "sha256": "2c45e75c2109f64504a2b92ef33e7d468845fff2bbc30081fcc50e74ed1134d4",
          "sha1": "5aabb5a79a4a0176b5ab2fe52f0b2b59eddfdd21",
          "md5": "3d6b44513b74b6f4d1d2ebc298698ee8"
        }
      ]
    }
  ]
}
