{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "acxx2gn7n5fr7nevplpysjnl3m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.8.aar",
          "url": "utils-0.32.8.aar",
          "size": 42927,
          "sha512": "a7575e8dc4d72ba38b52b2969fd32627a4d7a4e01315e1063e14eb896ba41af99cafeb36e06b937e60c7a24c412c966904ff179f0ba0ec28418834dfacf7d9c2",
          "sha256": "8ed40250c3700969171c1f31a48b3b926bc99e452c42ad130de813f8485c3f9a",
          "sha1": "4b3583de258d8532788d921a9a62929e3ca82bee",
          "md5": "16541089aa861946fe6b7a8393b6b5b9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.8.aar",
          "url": "utils-0.32.8.aar",
          "size": 42927,
          "sha512": "a7575e8dc4d72ba38b52b2969fd32627a4d7a4e01315e1063e14eb896ba41af99cafeb36e06b937e60c7a24c412c966904ff179f0ba0ec28418834dfacf7d9c2",
          "sha256": "8ed40250c3700969171c1f31a48b3b926bc99e452c42ad130de813f8485c3f9a",
          "sha1": "4b3583de258d8532788d921a9a62929e3ca82bee",
          "md5": "16541089aa861946fe6b7a8393b6b5b9"
        }
      ]
    }
  ]
}
