{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.29.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7xnk7aj5prhfvhghio4a2dcuqq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.5.aar",
          "url": "utils-0.29.5.aar",
          "size": 40159,
          "sha512": "37dafc3d94ecae29486d51d97fce141277c964d9dd5795e8fa24e556d585877d96978534684b329ec259282997b13b75689777bd7bf4b69b7df58a75c28347bc",
          "sha256": "b3f76ed98d95ad7cf8d71847ffc2fb060fa9194450c1fa8d2c0335fc32d8976c",
          "sha1": "da0c1c0960d15d4ea1ff9c0eca7d8b15ac5962b3",
          "md5": "25eb576099fb030bd53a3f898f2a7183"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.5.aar",
          "url": "utils-0.29.5.aar",
          "size": 40159,
          "sha512": "37dafc3d94ecae29486d51d97fce141277c964d9dd5795e8fa24e556d585877d96978534684b329ec259282997b13b75689777bd7bf4b69b7df58a75c28347bc",
          "sha256": "b3f76ed98d95ad7cf8d71847ffc2fb060fa9194450c1fa8d2c0335fc32d8976c",
          "sha1": "da0c1c0960d15d4ea1ff9c0eca7d8b15ac5962b3",
          "md5": "25eb576099fb030bd53a3f898f2a7183"
        }
      ]
    }
  ]
}
