{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3iscphedlvbedghedlphnrax7y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.26.1.aar",
          "url": "ui-0.26.1.aar",
          "size": 829053,
          "sha512": "fd8027f7f47b2c7c92f3c03ac0d93ae4b196f3f35414cc008c276afae043c821a69f046bf0041ba424b139d432086bdcadeb3221bd3ba983936ffc0e78de4ef0",
          "sha256": "b5e1cd56133cc0b55ba5d05416e66df23d0de1ea5e0f8309778c367f24de15e2",
          "sha1": "ee5a45b2024b58c08d0329a64a9decdeec942e8f",
          "md5": "4d5604fcaaa0f1a54072ce643188899a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.26.1.aar",
          "url": "ui-0.26.1.aar",
          "size": 829053,
          "sha512": "fd8027f7f47b2c7c92f3c03ac0d93ae4b196f3f35414cc008c276afae043c821a69f046bf0041ba424b139d432086bdcadeb3221bd3ba983936ffc0e78de4ef0",
          "sha256": "b5e1cd56133cc0b55ba5d05416e66df23d0de1ea5e0f8309778c367f24de15e2",
          "sha1": "ee5a45b2024b58c08d0329a64a9decdeec942e8f",
          "md5": "4d5604fcaaa0f1a54072ce643188899a"
        }
      ]
    }
  ]
}
