{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.33.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca6tr454abh4xjq6cbul5nylei"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.6.aar",
          "url": "firebase-detector-0.33.6.aar",
          "size": 33058,
          "sha512": "95e2e250097c1020d335a4974cd753f224ee490134d231ab8594496088ba06aa5c437dbaac25892427899637c45b077088b4860bbafeb5446074a331270e8baa",
          "sha256": "07269a01e1575febe20fa4723f2e47bc42dc082bd0c3d18db4c4d1ceaffd2992",
          "sha1": "c6add07ac08a941e8d36f9cf2dae83fbda505d75",
          "md5": "2702ce3c41bdf5d101898a88011ca6be"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.6"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.6"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.6.aar",
          "url": "firebase-detector-0.33.6.aar",
          "size": 33058,
          "sha512": "95e2e250097c1020d335a4974cd753f224ee490134d231ab8594496088ba06aa5c437dbaac25892427899637c45b077088b4860bbafeb5446074a331270e8baa",
          "sha256": "07269a01e1575febe20fa4723f2e47bc42dc082bd0c3d18db4c4d1ceaffd2992",
          "sha1": "c6add07ac08a941e8d36f9cf2dae83fbda505d75",
          "md5": "2702ce3c41bdf5d101898a88011ca6be"
        }
      ]
    }
  ]
}
