{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.48.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.48.1.aar",
          "url": "ui-integration-0.48.1.aar",
          "size": 100591,
          "sha512": "01e93d132c54e27118740dca36c06387947a89d575c7d9ed29cf618f02965bac7f8b78aae4327cc3a5766856b581e1ddc2fa7c9a380d3e52f2d59efc5648cf3b",
          "sha256": "61021b6e61481e755073a2e5dfc3affe927225945e34ff72908d30e9df662011",
          "sha1": "61ba798c18d78edcbcfe0c1b119d63ebfa4c53d0",
          "md5": "b6f01d587bc1befcacd4f6406b6e8893"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.48.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.48.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.48.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.48.1.aar",
          "url": "ui-integration-0.48.1.aar",
          "size": 100591,
          "sha512": "01e93d132c54e27118740dca36c06387947a89d575c7d9ed29cf618f02965bac7f8b78aae4327cc3a5766856b581e1ddc2fa7c9a380d3e52f2d59efc5648cf3b",
          "sha256": "61021b6e61481e755073a2e5dfc3affe927225945e34ff72908d30e9df662011",
          "sha1": "61ba798c18d78edcbcfe0c1b119d63ebfa4c53d0",
          "md5": "b6f01d587bc1befcacd4f6406b6e8893"
        }
      ]
    }
  ]
}
