{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kazzgux75bbcrkp2m3hgsyf7xa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.5.aar",
          "url": "ui-integration-0.35.5.aar",
          "size": 93291,
          "sha512": "2089063b06c356cdfc17c78f9fe6fe05222da4fd7ea299dddee1dd0d00965d7c57fbea9e3aaf72dca123cd0747ee8541dd95b5007cabcf3bd28349c937e975bc",
          "sha256": "aef561460fc9440349e25ce07cc55966787ac68f8fbfd0a68d983a5edcb64091",
          "sha1": "800535d0dfde5dd537ee2a722928193ac338aa26",
          "md5": "c0a44134ad2a969f617b6434ee850041"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.5"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.5.aar",
          "url": "ui-integration-0.35.5.aar",
          "size": 93291,
          "sha512": "2089063b06c356cdfc17c78f9fe6fe05222da4fd7ea299dddee1dd0d00965d7c57fbea9e3aaf72dca123cd0747ee8541dd95b5007cabcf3bd28349c937e975bc",
          "sha256": "aef561460fc9440349e25ce07cc55966787ac68f8fbfd0a68d983a5edcb64091",
          "sha1": "800535d0dfde5dd537ee2a722928193ac338aa26",
          "md5": "c0a44134ad2a969f617b6434ee850041"
        }
      ]
    }
  ]
}
