{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.35.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qlv47m7pbrf6dezneuybjbi45y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.3.aar",
          "url": "core-0.35.3.aar",
          "size": 333470,
          "sha512": "b3caa49d0dcf02bebe5fdf3d650df9cb39d55eaf99160a2161d429c7a573703855a730c42c1645b7307b2865a15b89c5bf114efc8425b58610347274a2ee38cf",
          "sha256": "6aa5e576f6f88c088fbf5161016999dfac9a164dac7c2416136eb41f3bb2b2de",
          "sha1": "43a9f30356cce0a7a76ad264aef7923683a9a7cc",
          "md5": "d60831cfc9d7bee8bf22832500a3b846"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.35.3.aar",
          "url": "core-0.35.3.aar",
          "size": 333470,
          "sha512": "b3caa49d0dcf02bebe5fdf3d650df9cb39d55eaf99160a2161d429c7a573703855a730c42c1645b7307b2865a15b89c5bf114efc8425b58610347274a2ee38cf",
          "sha256": "6aa5e576f6f88c088fbf5161016999dfac9a164dac7c2416136eb41f3bb2b2de",
          "sha1": "43a9f30356cce0a7a76ad264aef7923683a9a7cc",
          "md5": "d60831cfc9d7bee8bf22832500a3b846"
        }
      ]
    }
  ]
}
