{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.83.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.83.4.aar",
          "url": "utils-0.83.4.aar",
          "size": 46544,
          "sha512": "4c5f880143fcf1597a2ff7b6833ba2f03482acf8e9901744d78b68d6201fc7b1af1e54c2ed5eb23d3f989644f23ef101fd606728b948422c4dc02e637152f564",
          "sha256": "1a7675402c816c938a791e9bcd53fc3495aead40865309990714b43d8927c806",
          "sha1": "c051ac9a97713d1a8440d1fde841612a7f77844f",
          "md5": "99b385d72103451a4f679ccabf6545da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.83.4.aar",
          "url": "utils-0.83.4.aar",
          "size": 46544,
          "sha512": "4c5f880143fcf1597a2ff7b6833ba2f03482acf8e9901744d78b68d6201fc7b1af1e54c2ed5eb23d3f989644f23ef101fd606728b948422c4dc02e637152f564",
          "sha256": "1a7675402c816c938a791e9bcd53fc3495aead40865309990714b43d8927c806",
          "sha1": "c051ac9a97713d1a8440d1fde841612a7f77844f",
          "md5": "99b385d72103451a4f679ccabf6545da"
        }
      ]
    }
  ]
}
