{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.69.1-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.1-beta04.aar",
          "url": "utils-0.69.1-beta04.aar",
          "size": 55131,
          "sha512": "4f73750a0ac2ba60b176e4b92642d2fe5b8b4895dcebd4adaafbfefe4f9d5c9fb97c4a8f520c856fac9e2ab519c8588fa67c4d337efd7dadbb7ca37ddfaeb137",
          "sha256": "5cfc1594f16859a39686891eaf720acd66994966a591680cec2f4e60180c0f3b",
          "sha1": "dd906448a81b1f11a7745e33da79c4748ab6b2c4",
          "md5": "83363155a7344e4e39a29ead6afc9020"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.69.1-beta04.aar",
          "url": "utils-0.69.1-beta04.aar",
          "size": 55131,
          "sha512": "4f73750a0ac2ba60b176e4b92642d2fe5b8b4895dcebd4adaafbfefe4f9d5c9fb97c4a8f520c856fac9e2ab519c8588fa67c4d337efd7dadbb7ca37ddfaeb137",
          "sha256": "5cfc1594f16859a39686891eaf720acd66994966a591680cec2f4e60180c0f3b",
          "sha1": "dd906448a81b1f11a7745e33da79c4748ab6b2c4",
          "md5": "83363155a7344e4e39a29ead6afc9020"
        }
      ]
    }
  ]
}
