{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tr62le6bqbbu7nl6rqzzl2wnha"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.7.aar",
          "url": "core-0.32.7.aar",
          "size": 326042,
          "sha512": "b2bc679999f2f82367dc3c7312992c959bbb0165e1ba7f1a941070e61a1bba254a991434e9394311229cd14ada5bb4b349f31629f803d7b2666ffe5fde879fed",
          "sha256": "e42a88f1098f5ae26bc99a00788abf14b0d5a5ffb67c5ba0bf8e5ff8175f2049",
          "sha1": "ad9dc1dc3773515e7bb886be5568ee2040101526",
          "md5": "b4f72b1b9bc65441795d1d95ccadc289"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.7.aar",
          "url": "core-0.32.7.aar",
          "size": 326042,
          "sha512": "b2bc679999f2f82367dc3c7312992c959bbb0165e1ba7f1a941070e61a1bba254a991434e9394311229cd14ada5bb4b349f31629f803d7b2666ffe5fde879fed",
          "sha256": "e42a88f1098f5ae26bc99a00788abf14b0d5a5ffb67c5ba0bf8e5ff8175f2049",
          "sha1": "ad9dc1dc3773515e7bb886be5568ee2040101526",
          "md5": "b4f72b1b9bc65441795d1d95ccadc289"
        }
      ]
    }
  ]
}
