{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.33.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dyzxkmtlm5g6dgcrd6zzdd3d4i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.1.aar",
          "url": "utils-0.33.1.aar",
          "size": 42944,
          "sha512": "73bd7b5caaea1976f8c338abdcbb01efc03342f9feed58876744f11d1a70f30156ee886625ab8368fc83517652b3e7c0f0fbda69d634aa34a5af07b9a7728269",
          "sha256": "d865362aeb787b8558648c3b0afa5ce109540b7ffce7688c1f1429ed77977eda",
          "sha1": "06400b4cb72d387fe6d22d583638ffc694e8f8be",
          "md5": "3fe2982888b21027e72476d77d056044"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.33.1.aar",
          "url": "utils-0.33.1.aar",
          "size": 42944,
          "sha512": "73bd7b5caaea1976f8c338abdcbb01efc03342f9feed58876744f11d1a70f30156ee886625ab8368fc83517652b3e7c0f0fbda69d634aa34a5af07b9a7728269",
          "sha256": "d865362aeb787b8558648c3b0afa5ce109540b7ffce7688c1f1429ed77977eda",
          "sha1": "06400b4cb72d387fe6d22d583638ffc694e8f8be",
          "md5": "3fe2982888b21027e72476d77d056044"
        }
      ]
    }
  ]
}
