{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.6.aar",
          "url": "core-0.75.6.aar",
          "size": 638558,
          "sha512": "1ab1216472e106a6cca4b2990dd7fb8cf1c79e4b53766ea681af388f961be88f10b06f65a63d77bf7e60dffe411ac1b4cdbd78abb110c86a4a87bacb50438e46",
          "sha256": "c84e0493cdae4a5707701c7d9e7d5a2529b4fd4552c04e98157fee639ab17f5a",
          "sha1": "b8acaf5514bd869e647ab86f35306ea4de3d314b",
          "md5": "23b3c9098ddd949e4cc6b5bf612f3a7f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.6.aar",
          "url": "core-0.75.6.aar",
          "size": 638558,
          "sha512": "1ab1216472e106a6cca4b2990dd7fb8cf1c79e4b53766ea681af388f961be88f10b06f65a63d77bf7e60dffe411ac1b4cdbd78abb110c86a4a87bacb50438e46",
          "sha256": "c84e0493cdae4a5707701c7d9e7d5a2529b4fd4552c04e98157fee639ab17f5a",
          "sha1": "b8acaf5514bd869e647ab86f35306ea4de3d314b",
          "md5": "23b3c9098ddd949e4cc6b5bf612f3a7f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.6-sources.jar",
          "url": "core-0.75.6-sources.jar",
          "size": 343931,
          "sha512": "e344db955ae0ec503c534d2f143e0a5c022ba2a06f16ba80d8a78fe94d7202f8f6f960513e425547f6c5dbbbe5abe0459bd28e66ea358054d3f71d2ce5f283a4",
          "sha256": "37a7eb9846300708a3013c327788392defb40e250265f2eb82e533608e871d35",
          "sha1": "49fd939e3e290ab07ec963bc160180aad42289a1",
          "md5": "99507a49f9bc37bda7fa21fe65265a10"
        }
      ]
    }
  ]
}
