{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3nyxzpnzzvg4zbdubvx56dggea"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.27.0.aar",
          "url": "core-0.27.0.aar",
          "size": 273362,
          "sha512": "4f2f91e278e75337ac7a51659858bbff7a24fb612c01b9fb50f685a1733b8b65677d06fb478786b9cddd3194d6181c84c36ebe11641262c2ff85b0e721bea8e1",
          "sha256": "de5d631a9ffe7bb61b440f590941623b7f5a224497375be65f8f559cd7783587",
          "sha1": "d079b97fc86274e735c5dcb37619d59342d4f2d0",
          "md5": "bf3b5480abee6cd13eedab2d317ad1e5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.27.0.aar",
          "url": "core-0.27.0.aar",
          "size": 273362,
          "sha512": "4f2f91e278e75337ac7a51659858bbff7a24fb612c01b9fb50f685a1733b8b65677d06fb478786b9cddd3194d6181c84c36ebe11641262c2ff85b0e721bea8e1",
          "sha256": "de5d631a9ffe7bb61b440f590941623b7f5a224497375be65f8f559cd7783587",
          "sha1": "d079b97fc86274e735c5dcb37619d59342d4f2d0",
          "md5": "bf3b5480abee6cd13eedab2d317ad1e5"
        }
      ]
    }
  ]
}
