{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.62.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.62.3.aar",
          "url": "firebase-detector-0.62.3.aar",
          "size": 51820,
          "sha512": "1e8e8e4c8b769768a6c12c3b4cf46453a487299d654af69f25e083f5b627d16f126b2115a0c320102b7f37b61bd3adc7787a74432f38580f17c2ab51b9af182d",
          "sha256": "ab387da89be692ffce71b4fe844fbcd23008c7ae30ce54e379fedbaac15209f0",
          "sha1": "9ef94324c7bb0271afa8f4de318de06598305eba",
          "md5": "773d2eadc3e325577402efc253588135"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.62.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.62.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.62.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.62.3.aar",
          "url": "firebase-detector-0.62.3.aar",
          "size": 51820,
          "sha512": "1e8e8e4c8b769768a6c12c3b4cf46453a487299d654af69f25e083f5b627d16f126b2115a0c320102b7f37b61bd3adc7787a74432f38580f17c2ab51b9af182d",
          "sha256": "ab387da89be692ffce71b4fe844fbcd23008c7ae30ce54e379fedbaac15209f0",
          "sha1": "9ef94324c7bb0271afa8f4de318de06598305eba",
          "md5": "773d2eadc3e325577402efc253588135"
        }
      ]
    }
  ]
}
