{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vobsuvm2ibhufag2skl6lg2ria"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.13.aar",
          "url": "core-0.39.13.aar",
          "size": 368790,
          "sha512": "e6e6d425ceb52e2e610b8aa5ee93bdb2cec378f6f0cb00e1fc3e802f28ab0cd1dbc647e239663ddd2c64e2df7cc44fd6762b45ff260db3501dc6327c89afa959",
          "sha256": "cc0c80ed528c865cef9b2de46efc223c9c9c5be973c313f6183acf5fe8d9e762",
          "sha1": "0787f4c5cc811bbf09599022b8b174a5b0a3d35c",
          "md5": "a25b588b5b86d50483e8b03f5697cd29"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.13"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.13.aar",
          "url": "core-0.39.13.aar",
          "size": 368790,
          "sha512": "e6e6d425ceb52e2e610b8aa5ee93bdb2cec378f6f0cb00e1fc3e802f28ab0cd1dbc647e239663ddd2c64e2df7cc44fd6762b45ff260db3501dc6327c89afa959",
          "sha256": "cc0c80ed528c865cef9b2de46efc223c9c9c5be973c313f6183acf5fe8d9e762",
          "sha1": "0787f4c5cc811bbf09599022b8b174a5b0a3d35c",
          "md5": "a25b588b5b86d50483e8b03f5697cd29"
        }
      ]
    }
  ]
}
