{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.32.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4fidkbhpcfc5ncwzvfc7lt4zwy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.2.aar",
          "url": "utils-0.32.2.aar",
          "size": 42927,
          "sha512": "78f488d21bcb85084578b737f50361456517c90f021562db13c15688061ac600c9c453fa18c57b4173657008b6c4fd2aa48a4faf0e656229fc902a2eccbca2cb",
          "sha256": "a9152f9d8220d9ed53410021e327a419b536e4525af2de0d6d773ed4d3aa98ae",
          "sha1": "f29c4badfe3abc1bd379908e2b99b5e24930ff24",
          "md5": "3ddf0b7bbe858c3a3163e6c2c58190ae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.32.2.aar",
          "url": "utils-0.32.2.aar",
          "size": 42927,
          "sha512": "78f488d21bcb85084578b737f50361456517c90f021562db13c15688061ac600c9c453fa18c57b4173657008b6c4fd2aa48a4faf0e656229fc902a2eccbca2cb",
          "sha256": "a9152f9d8220d9ed53410021e327a419b536e4525af2de0d6d773ed4d3aa98ae",
          "sha1": "f29c4badfe3abc1bd379908e2b99b5e24930ff24",
          "md5": "3ddf0b7bbe858c3a3163e6c2c58190ae"
        }
      ]
    }
  ]
}
