{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2iqt364jrfa67og6wb4xwnqb5q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.9.aar",
          "url": "core-0.29.9.aar",
          "size": 287801,
          "sha512": "9de48c23a7cb4301517cc5ba4e775b6b15b7fd3d783c49cfb2d564dbd7970c9ff7f2f717e712a1c9c412bffce451f82b2d15b6cf3c7c4d64127b57c2ce29fb4d",
          "sha256": "a0a7a0325e0079ea24d1f3c6a207bdba8c9a0aebfbdbae7f60bed10256025f30",
          "sha1": "2451cec24e4b0e9432cbd43218e01e3497fd418b",
          "md5": "b367cca1e55a226fd756bc417d7557f4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.9.aar",
          "url": "core-0.29.9.aar",
          "size": 287801,
          "sha512": "9de48c23a7cb4301517cc5ba4e775b6b15b7fd3d783c49cfb2d564dbd7970c9ff7f2f717e712a1c9c412bffce451f82b2d15b6cf3c7c4d64127b57c2ce29fb4d",
          "sha256": "a0a7a0325e0079ea24d1f3c6a207bdba8c9a0aebfbdbae7f60bed10256025f30",
          "sha1": "2451cec24e4b0e9432cbd43218e01e3497fd418b",
          "md5": "b367cca1e55a226fd756bc417d7557f4"
        }
      ]
    }
  ]
}
