{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.pay",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 47865,
          "sha512": "022c1c1a5e9020472d445e7201f979d5e28b8f410d4bc7497192f0d93b617aa9a9686bad4d59b2e152b1fb0c4469186ed5bae2d0edb8aa8ace3fca118effbfa3",
          "sha256": "95d3bd8695e41165375c8d991cf6044b3ce7947cf9e0637291639a4566e92c3c",
          "sha1": "721f973051dc98ba0fd1bf4576b5c21db7a49dc4",
          "md5": "4cad4e8f8691fe3222cc9a9e288936b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.pay",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.snabble.pay",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 47865,
          "sha512": "022c1c1a5e9020472d445e7201f979d5e28b8f410d4bc7497192f0d93b617aa9a9686bad4d59b2e152b1fb0c4469186ed5bae2d0edb8aa8ace3fca118effbfa3",
          "sha256": "95d3bd8695e41165375c8d991cf6044b3ce7947cf9e0637291639a4566e92c3c",
          "sha1": "721f973051dc98ba0fd1bf4576b5c21db7a49dc4",
          "md5": "4cad4e8f8691fe3222cc9a9e288936b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.0-sources.jar",
          "url": "api-1.0.0-sources.jar",
          "size": 7971,
          "sha512": "6ce0e09f307afb78bc7a637ab03b7eb59bf5e1f816eec5ce0be9b1a75cd7aa658dc2a7349c44a96e6142fc9bb2d3dfe04dbe348d994e9346ef70a04533f1ffd8",
          "sha256": "2acf144ae5c96d42510127fdbc08af222181ae8c9870f534be6314938925ff66",
          "sha1": "d7d3330004d4f56a68b28864e6fc30cbb3f62213",
          "md5": "73fc7da914ea04ab812c9f3936926a5d"
        }
      ]
    }
  ]
}
