{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.7.aar",
          "url": "core-0.80.7.aar",
          "size": 668608,
          "sha512": "ede5099c3124ec07c85ec218bce70ab9c3abb76cc64227d74ea5bb885aa9cc701842724e1edbf38ce1e8e6d875ea004abac07391b31801e568ce71234f28e076",
          "sha256": "250e274735111dcb066293e8e02068961c852d3449b7885e2a8a793919bf8756",
          "sha1": "e18fc15d0a997569419bd56fdcef7b3eea4a3de1",
          "md5": "be28b0e8a06e7e2e845cde3c7341d3f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.7.aar",
          "url": "core-0.80.7.aar",
          "size": 668608,
          "sha512": "ede5099c3124ec07c85ec218bce70ab9c3abb76cc64227d74ea5bb885aa9cc701842724e1edbf38ce1e8e6d875ea004abac07391b31801e568ce71234f28e076",
          "sha256": "250e274735111dcb066293e8e02068961c852d3449b7885e2a8a793919bf8756",
          "sha1": "e18fc15d0a997569419bd56fdcef7b3eea4a3de1",
          "md5": "be28b0e8a06e7e2e845cde3c7341d3f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.7-sources.jar",
          "url": "core-0.80.7-sources.jar",
          "size": 352179,
          "sha512": "988f841cec47c06b7aa9b4986f8f51bc979498cdb126dffba695f1e104d630e6794b87dd9a4e0154c121f28e1640b6db9dc2aa7a9338dbb32d74c2ad38d03c25",
          "sha256": "eb0db4241e592439bbc2254a166fc988f12af22272695f3f169aa31d63a7c4b9",
          "sha1": "0f60ae5c44085ccdc8ac5ec0cc3c8960265508c4",
          "md5": "cf70370bfe9b3b21469525d6f984a3c9"
        }
      ]
    }
  ]
}
