{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fnx5gahborfyfotg42y67ktore"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.31.0.aar",
          "url": "ui-0.31.0.aar",
          "size": 836568,
          "sha512": "fb7fe71829846c5e1c83569c29506a7933886cc1e6b78fac3cb6cd03c5de675e501dff53f9d7a4ec9fa45e7729363faf1dd234a0722c488db85ada3989645b56",
          "sha256": "562cc9ed6787a6764365100286fee31399acdba5493ed76bc3cae8eead6821ac",
          "sha1": "75491ae664bbaaa3252c642c253c5c2a4fd14fc4",
          "md5": "dcd19c4f675afa076eb85c4b5aa1cfd3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.31.0.aar",
          "url": "ui-0.31.0.aar",
          "size": 836568,
          "sha512": "fb7fe71829846c5e1c83569c29506a7933886cc1e6b78fac3cb6cd03c5de675e501dff53f9d7a4ec9fa45e7729363faf1dd234a0722c488db85ada3989645b56",
          "sha256": "562cc9ed6787a6764365100286fee31399acdba5493ed76bc3cae8eead6821ac",
          "sha1": "75491ae664bbaaa3252c642c253c5c2a4fd14fc4",
          "md5": "dcd19c4f675afa076eb85c4b5aa1cfd3"
        }
      ]
    }
  ]
}
