{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.25.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jdjaink725hpjcqmmejphu4w7m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.25.5.aar",
          "url": "ui-0.25.5.aar",
          "size": 827792,
          "sha512": "34907249ed52eb22fadb409dc3c0b06f4dcb9519ecb1bc8cd2071be6fb60b697b869f3588c5432ab4a7908d27ef19aceaea99712836ff76c8f63a2d1db26a2ee",
          "sha256": "a393d600236f4e85196c0e3e21e071dd62d4bc079682d2aa2087749ad08d3be6",
          "sha1": "dc1a8a6d201e093c94d2dcaa8b79b62125419f8c",
          "md5": "9020b97837f8d0ed426d0184535133c9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.25.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.25.5.aar",
          "url": "ui-0.25.5.aar",
          "size": 827792,
          "sha512": "34907249ed52eb22fadb409dc3c0b06f4dcb9519ecb1bc8cd2071be6fb60b697b869f3588c5432ab4a7908d27ef19aceaea99712836ff76c8f63a2d1db26a2ee",
          "sha256": "a393d600236f4e85196c0e3e21e071dd62d4bc079682d2aa2087749ad08d3be6",
          "sha1": "dc1a8a6d201e093c94d2dcaa8b79b62125419f8c",
          "md5": "9020b97837f8d0ed426d0184535133c9"
        }
      ]
    }
  ]
}
