{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.29.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sd2z24tmlrbn7ha3pfd52gmetm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.4.aar",
          "url": "utils-0.29.4.aar",
          "size": 40159,
          "sha512": "4349b931c0712348a47869f66825f6ae3e6d7cc8a6029e8fd0841331230eee6ba2bcdd8772fda9ddd66978a55f35463146a8d54429cb7df7e244e4fe11b41e4c",
          "sha256": "a0b58fc10c245c86ee6b1db8bb2fc09992580702179d101f4af33eef475fa319",
          "sha1": "d337566afbeb5806c317e7c6871ba605a12495e4",
          "md5": "f76b8d000a9e37da322cf41fc4044832"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.4.aar",
          "url": "utils-0.29.4.aar",
          "size": 40159,
          "sha512": "4349b931c0712348a47869f66825f6ae3e6d7cc8a6029e8fd0841331230eee6ba2bcdd8772fda9ddd66978a55f35463146a8d54429cb7df7e244e4fe11b41e4c",
          "sha256": "a0b58fc10c245c86ee6b1db8bb2fc09992580702179d101f4af33eef475fa319",
          "sha1": "d337566afbeb5806c317e7c6871ba605a12495e4",
          "md5": "f76b8d000a9e37da322cf41fc4044832"
        }
      ]
    }
  ]
}
