{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.33.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5ji7qh4ifbbd5j65vbqdkdc2ye"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.8.aar",
          "url": "firebase-detector-0.33.8.aar",
          "size": 33062,
          "sha512": "2f72883d7486c507463c15e00cc18515222e09e571af7d0555d1c6eec139f5b4157bb01d60af4199493a0802cc50c98f7399b8411c49e33b8dfd4de647cb2226",
          "sha256": "4a6ef8446944f4ef9adf15122dcf6deb926cc3daffa8431fbac02b74b2f1fb68",
          "sha1": "9270e2e9196ec4f39a1a88030e7f6cd8283b295f",
          "md5": "4653d9753f75a9d3e24ebc7307c6abf5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.8.aar",
          "url": "firebase-detector-0.33.8.aar",
          "size": 33062,
          "sha512": "2f72883d7486c507463c15e00cc18515222e09e571af7d0555d1c6eec139f5b4157bb01d60af4199493a0802cc50c98f7399b8411c49e33b8dfd4de647cb2226",
          "sha256": "4a6ef8446944f4ef9adf15122dcf6deb926cc3daffa8431fbac02b74b2f1fb68",
          "sha1": "9270e2e9196ec4f39a1a88030e7f6cd8283b295f",
          "md5": "4653d9753f75a9d3e24ebc7307c6abf5"
        }
      ]
    }
  ]
}
