{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qvpcucnmzrb4lhoa6wtow3rtda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.2.aar",
          "url": "core-0.25.2.aar",
          "size": 272238,
          "sha512": "61ccedbfe57efec7381e62d35a055776c29852a0a9b11281bcb0383e550804b615702e652c94df55c26244bd7d90fed0bf5637e82502f3c6db30a7e4d7e9536b",
          "sha256": "e63021e0a47a5b671641e33170421ad3a462b70d4341e72875861e1d49673a93",
          "sha1": "5b471352e68a3bf79b227304b496b728d8dd6318",
          "md5": "a8e02db124ec4a3599e53ec9ea7fa238"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.2.aar",
          "url": "core-0.25.2.aar",
          "size": 272238,
          "sha512": "61ccedbfe57efec7381e62d35a055776c29852a0a9b11281bcb0383e550804b615702e652c94df55c26244bd7d90fed0bf5637e82502f3c6db30a7e4d7e9536b",
          "sha256": "e63021e0a47a5b671641e33170421ad3a462b70d4341e72875861e1d49673a93",
          "sha1": "5b471352e68a3bf79b227304b496b728d8dd6318",
          "md5": "a8e02db124ec4a3599e53ec9ea7fa238"
        }
      ]
    }
  ]
}
