{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rqes3m2sgvhgnc4lffhcdvyhsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.1.aar",
          "url": "core-0.25.1.aar",
          "size": 272240,
          "sha512": "95c473a9e472f7d8ad77716d5ef7191f758c47641eb9b94d22e0209e1197ca35f06ce29d2d8bbcc862d5921a18266bdb11f66494d73fbd2a7e553666e264742e",
          "sha256": "9a7fc1b439f7f5186f6e819ada66c77c8d5096d6259a7e88ea2fd3123ab2e855",
          "sha1": "765100ed7b2d965e1e9ba2c52c6c2257ad18c0f3",
          "md5": "c9514ff7d5dedcbc3ea61d7349894e8c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.25.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.25.1.aar",
          "url": "core-0.25.1.aar",
          "size": 272240,
          "sha512": "95c473a9e472f7d8ad77716d5ef7191f758c47641eb9b94d22e0209e1197ca35f06ce29d2d8bbcc862d5921a18266bdb11f66494d73fbd2a7e553666e264742e",
          "sha256": "9a7fc1b439f7f5186f6e819ada66c77c8d5096d6259a7e88ea2fd3123ab2e855",
          "sha1": "765100ed7b2d965e1e9ba2c52c6c2257ad18c0f3",
          "md5": "c9514ff7d5dedcbc3ea61d7349894e8c"
        }
      ]
    }
  ]
}
