{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5ji7qh4ifbbd5j65vbqdkdc2ye"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.8.aar",
          "url": "core-0.33.8.aar",
          "size": 327887,
          "sha512": "fc3e0e940851b7c548ef82ed5be9e02e6230d233a08b7a28fefd0abadcbd66a5eb9fac3f274bb6e49c0b73a23d48f6eb06f1bb9173a8d24b2dbdfec5a51f6b96",
          "sha256": "09b7e29c9ff86fe2782ae7a8e3fa05c7dfbc63e6d8da0ee43e464899e3268310",
          "sha1": "807ea055688a43e8e450faa8540d3ebf013d35ff",
          "md5": "5a5b1e49178da864602884477d995e0f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.8.aar",
          "url": "core-0.33.8.aar",
          "size": 327887,
          "sha512": "fc3e0e940851b7c548ef82ed5be9e02e6230d233a08b7a28fefd0abadcbd66a5eb9fac3f274bb6e49c0b73a23d48f6eb06f1bb9173a8d24b2dbdfec5a51f6b96",
          "sha256": "09b7e29c9ff86fe2782ae7a8e3fa05c7dfbc63e6d8da0ee43e464899e3268310",
          "sha1": "807ea055688a43e8e450faa8540d3ebf013d35ff",
          "md5": "5a5b1e49178da864602884477d995e0f"
        }
      ]
    }
  ]
}
