{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.77.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.77.1.aar",
          "url": "utils-0.77.1.aar",
          "size": 58507,
          "sha512": "b064d83e127b1a48cfd29e299b190ac95d1382e1a3644b83506a290e05d4171bd032a686ba1d306fa63d0c936380b20b0b4ff6ea44c5fd7dbc13cfb096c182ef",
          "sha256": "3a92d53d850d127a5d284a552cd7c44c0438fc77c5d1f4e385bd6ca11f1b6971",
          "sha1": "b451fb665fd428446bd0774506c22b23a9a3a354",
          "md5": "06f8fee6b5c8e888141e67dd9607c7f9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.77.1.aar",
          "url": "utils-0.77.1.aar",
          "size": 58507,
          "sha512": "b064d83e127b1a48cfd29e299b190ac95d1382e1a3644b83506a290e05d4171bd032a686ba1d306fa63d0c936380b20b0b4ff6ea44c5fd7dbc13cfb096c182ef",
          "sha256": "3a92d53d850d127a5d284a552cd7c44c0438fc77c5d1f4e385bd6ca11f1b6971",
          "sha1": "b451fb665fd428446bd0774506c22b23a9a3a354",
          "md5": "06f8fee6b5c8e888141e67dd9607c7f9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.77.1-sources.jar",
          "url": "utils-0.77.1-sources.jar",
          "size": 45527,
          "sha512": "6323429672ff5f66b6109c16210fcf4d10e84648a2a1aad592b451930d9780e769bf76842b54dd61a20ed081c426f77053677e27ba3c76a2d94f9e2f52d89492",
          "sha256": "4f8d42603fa2159b6ccafbe6782e5ffa766ed656bcac3d65cc40c354df11cc34",
          "sha1": "19e41563e77d2e27391471ade0f4d2d27dc18985",
          "md5": "bbf2a45207b95b7a785c85e06e385660"
        }
      ]
    }
  ]
}
