{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.7.aar",
          "url": "core-0.75.7.aar",
          "size": 644159,
          "sha512": "896d2cf097e0338dd45a38c971d4d1ede1332305c36d636abd47106009d5cbb8de0cbfdec05305cc952961334a9421a46a5fe440711770fa81af356c20cc0573",
          "sha256": "cbdd0c33f1e354d4416e392b13352e12a766fd173c9db9058b5eefb4d81ffba3",
          "sha1": "3c2d359c6b441f3934dfb9f4b1caf269a34b9ad4",
          "md5": "ecfb6b5a36509486ed9007fb7d75d799"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.7.aar",
          "url": "core-0.75.7.aar",
          "size": 644159,
          "sha512": "896d2cf097e0338dd45a38c971d4d1ede1332305c36d636abd47106009d5cbb8de0cbfdec05305cc952961334a9421a46a5fe440711770fa81af356c20cc0573",
          "sha256": "cbdd0c33f1e354d4416e392b13352e12a766fd173c9db9058b5eefb4d81ffba3",
          "sha1": "3c2d359c6b441f3934dfb9f4b1caf269a34b9ad4",
          "md5": "ecfb6b5a36509486ed9007fb7d75d799"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.7-sources.jar",
          "url": "core-0.75.7-sources.jar",
          "size": 345367,
          "sha512": "3fc19796d77ceda6826f16178f8ac5a6f01b2e71a640fe7cc0e94dbab5c645aad459ea8fa7c77bedf3d4496fef6eef9cb80fac24ce4d6415f2df56e0cc559d8a",
          "sha256": "7bb183834140825b43648b94cf82da22014b65587ae0692dad758dca13cc7dd9",
          "sha1": "0ff30a6ad3706aee13ec0dd274d0360f6105011d",
          "md5": "22e3ad2746a3f4e6f25c7f7979bd5517"
        }
      ]
    }
  ]
}
