{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.60.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.60.1.aar",
          "url": "utils-0.60.1.aar",
          "size": 44242,
          "sha512": "40a9055def891d4acfbafda18d9b45d275a09a152545f88494bdd05e1c5f5bf57d5ca52dbf73f81c086cab37017a6c9a08b46e5603f7bdbe8ff53fa1b5c72a3d",
          "sha256": "1070ebad5786e922a8d66eb4415ecffaacc9299b4d227a7a78ecb42ba707d281",
          "sha1": "11bdc2838bcfea9b366ac5025c66227ecfd534bd",
          "md5": "1777c28413df1e89079154c0d0dfa59f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.60.1.aar",
          "url": "utils-0.60.1.aar",
          "size": 44242,
          "sha512": "40a9055def891d4acfbafda18d9b45d275a09a152545f88494bdd05e1c5f5bf57d5ca52dbf73f81c086cab37017a6c9a08b46e5603f7bdbe8ff53fa1b5c72a3d",
          "sha256": "1070ebad5786e922a8d66eb4415ecffaacc9299b4d227a7a78ecb42ba707d281",
          "sha1": "11bdc2838bcfea9b366ac5025c66227ecfd534bd",
          "md5": "1777c28413df1e89079154c0d0dfa59f"
        }
      ]
    }
  ]
}
