{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.29.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6yyo6zayljgyvb43z64zn45arm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.8.aar",
          "url": "ui-integration-0.29.8.aar",
          "size": 74889,
          "sha512": "829927955be67348033015782574237831d81bda08387aaf144b4e6f5869e4667148acc67ec20d04dfdf9578aa82d7bf9da49dc0d082a5c6a35fd3507cdce4bc",
          "sha256": "46879b936fa37dea1a0d87fcbd99c56f89f852329247d762bfec17da06ea8473",
          "sha1": "c8f19e218887645b1145e5a06853279174c17f61",
          "md5": "f62eace6bb2717f5a4523f0d526f31d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.29.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.29.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.8"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.29.8.aar",
          "url": "ui-integration-0.29.8.aar",
          "size": 74889,
          "sha512": "829927955be67348033015782574237831d81bda08387aaf144b4e6f5869e4667148acc67ec20d04dfdf9578aa82d7bf9da49dc0d082a5c6a35fd3507cdce4bc",
          "sha256": "46879b936fa37dea1a0d87fcbd99c56f89f852329247d762bfec17da06ea8473",
          "sha1": "c8f19e218887645b1145e5a06853279174c17f61",
          "md5": "f62eace6bb2717f5a4523f0d526f31d0"
        }
      ]
    }
  ]
}
