{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.82.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.82.8.aar",
          "url": "core-0.82.8.aar",
          "size": 780956,
          "sha512": "d1476d0d8ff6bf07cbe4ca54ba9e23bc2a275f9a1c7672dbe13124d607ca43c95fb870dfce4cd33f591bbe5cbb7c80abac4db7356c1c83695442b81e10085b2a",
          "sha256": "a83a50a397e90219fadf73ad79ea570f8a1e43ba7d20ad2936712c3ee6deb3a2",
          "sha1": "a23bf5510f1fc50e79f2913b94c4a5a0d2cfdb27",
          "md5": "d95df26343777069ec76ebdeeb4409b4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.20.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.21.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.82.8.aar",
          "url": "core-0.82.8.aar",
          "size": 780956,
          "sha512": "d1476d0d8ff6bf07cbe4ca54ba9e23bc2a275f9a1c7672dbe13124d607ca43c95fb870dfce4cd33f591bbe5cbb7c80abac4db7356c1c83695442b81e10085b2a",
          "sha256": "a83a50a397e90219fadf73ad79ea570f8a1e43ba7d20ad2936712c3ee6deb3a2",
          "sha1": "a23bf5510f1fc50e79f2913b94c4a5a0d2cfdb27",
          "md5": "d95df26343777069ec76ebdeeb4409b4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.82.8-sources.jar",
          "url": "core-0.82.8-sources.jar",
          "size": 569209,
          "sha512": "b88eab877b66363dd7bd4beea93acfa2f009d2b6c138fc13743aa3ef10646e3c8743cf99b51e32ae49a0d6c138c5969a78c5456cb770818147313b4818f06dbc",
          "sha256": "0edcebea606250456dc5eb88bfd5207eea9f3906228ef255d9023ffb139e3ce1",
          "sha1": "3907e8db0fdd45d1406522e7c56d66c24458d77f",
          "md5": "ad9471299e8c94ccadfc114a52363cd1"
        }
      ]
    }
  ]
}
