{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rocqcy25kveb7jpfvunubpc47u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.12.aar",
          "url": "core-0.39.12.aar",
          "size": 368792,
          "sha512": "7156c3d1c962819ed4df466f1a88e55270ef262f5acf6fe6f765646b3c622117af8a6893f6a337633fe89565c7623f112d118f78425f9e791839c3848eb392a5",
          "sha256": "83243f8df2c075eb2d4dff7bcf08faab0d1acd1d22db2b2aa5db48d5b5181a5f",
          "sha1": "1dfe97a0d1a2f5471edb3c70fdc7ff7f6ddadb1a",
          "md5": "06a10207b90b8bcd486c52364a071b9a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.12"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.12.aar",
          "url": "core-0.39.12.aar",
          "size": 368792,
          "sha512": "7156c3d1c962819ed4df466f1a88e55270ef262f5acf6fe6f765646b3c622117af8a6893f6a337633fe89565c7623f112d118f78425f9e791839c3848eb392a5",
          "sha256": "83243f8df2c075eb2d4dff7bcf08faab0d1acd1d22db2b2aa5db48d5b5181a5f",
          "sha1": "1dfe97a0d1a2f5471edb3c70fdc7ff7f6ddadb1a",
          "md5": "06a10207b90b8bcd486c52364a071b9a"
        }
      ]
    }
  ]
}
