{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui",
    "version": "0.27.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "e7j45vwqpfdjdculia3jsmcsmm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-0.27.1.aar",
          "url": "ui-0.27.1.aar",
          "size": 830716,
          "sha512": "0befbcdb8f68095b91f31e42e435cfced9f19c56c10488f7cd71eef797a47d8fddbc2ee3ff273555a55a43a0abf3f1b213ef1dcaf4d91a9859278682826a2ad0",
          "sha256": "c260fa993887b1a9227e1de3d4080b8e2c707927a118ab53b7268e580646ec31",
          "sha1": "5acababe6f938f24ad3d8d61be8b8f5a0af3775b",
          "md5": "ca5febbdc9546528207d40eef88674f3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.27.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.27.1.aar",
          "url": "ui-0.27.1.aar",
          "size": 830716,
          "sha512": "0befbcdb8f68095b91f31e42e435cfced9f19c56c10488f7cd71eef797a47d8fddbc2ee3ff273555a55a43a0abf3f1b213ef1dcaf4d91a9859278682826a2ad0",
          "sha256": "c260fa993887b1a9227e1de3d4080b8e2c707927a118ab53b7268e580646ec31",
          "sha1": "5acababe6f938f24ad3d8d61be8b8f5a0af3775b",
          "md5": "ca5febbdc9546528207d40eef88674f3"
        }
      ]
    }
  ]
}
