{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.50.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.50.3.aar",
          "url": "ui-integration-0.50.3.aar",
          "size": 100879,
          "sha512": "82775ffdae03f8474ab3b144fc7634035c4e5a4e038ff5b64f83cbb6570b442011958634290d008f9799043e32ff74633f644eaff9e6a225864034746ca753d9",
          "sha256": "8f43a0c0379dab297206e63217393502790f50cf3936300312348819d736eb5d",
          "sha1": "64550bc74b738da12352302e4f5ae6d547002d74",
          "md5": "8542362f0881258b54a8d57994cbb381"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.50.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.50.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.50.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.50.3.aar",
          "url": "ui-integration-0.50.3.aar",
          "size": 100879,
          "sha512": "82775ffdae03f8474ab3b144fc7634035c4e5a4e038ff5b64f83cbb6570b442011958634290d008f9799043e32ff74633f644eaff9e6a225864034746ca753d9",
          "sha256": "8f43a0c0379dab297206e63217393502790f50cf3936300312348819d736eb5d",
          "sha1": "64550bc74b738da12352302e4f5ae6d547002d74",
          "md5": "8542362f0881258b54a8d57994cbb381"
        }
      ]
    }
  ]
}
