{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.8.aar",
          "url": "core-0.80.8.aar",
          "size": 668614,
          "sha512": "4a4076ceee6508d617fd93d7d108a757233f77576afdffe9e9881379c3b2d5501255dbfe98e75e67db96b32cdd465254d0842b918a4af3560d6a594cded8c3c0",
          "sha256": "6a5847b86b4f625d25c3d2b745f49969a77af3f128192075ef10b354d024086e",
          "sha1": "783fca169cf8ce4106828638970a45746abf8305",
          "md5": "f66d47ca0e238d1339eafe07182f50d2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.8.aar",
          "url": "core-0.80.8.aar",
          "size": 668614,
          "sha512": "4a4076ceee6508d617fd93d7d108a757233f77576afdffe9e9881379c3b2d5501255dbfe98e75e67db96b32cdd465254d0842b918a4af3560d6a594cded8c3c0",
          "sha256": "6a5847b86b4f625d25c3d2b745f49969a77af3f128192075ef10b354d024086e",
          "sha1": "783fca169cf8ce4106828638970a45746abf8305",
          "md5": "f66d47ca0e238d1339eafe07182f50d2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.8-sources.jar",
          "url": "core-0.80.8-sources.jar",
          "size": 352179,
          "sha512": "988f841cec47c06b7aa9b4986f8f51bc979498cdb126dffba695f1e104d630e6794b87dd9a4e0154c121f28e1640b6db9dc2aa7a9338dbb32d74c2ad38d03c25",
          "sha256": "eb0db4241e592439bbc2254a166fc988f12af22272695f3f169aa31d63a7c4b9",
          "sha1": "0f60ae5c44085ccdc8ac5ec0cc3c8960265508c4",
          "md5": "cf70370bfe9b3b21469525d6f984a3c9"
        }
      ]
    }
  ]
}
