{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.34.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o75qremr5rhdhnsylosxqqpy7q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.34.4.aar",
          "url": "utils-0.34.4.aar",
          "size": 42946,
          "sha512": "0c0e4f0c496cf563e59db0776b617b2a9782967523b321c800fc9c3da11017a71bc8fce9b30755e7134e5960584ce7b3d0d1310cb18991f053a626dcac8e0d47",
          "sha256": "955fdad21c7f2c38e90063a21058d2bd389e3c0a8543fdfb9e9b3a1661c5b6a4",
          "sha1": "fec3a304b24ae4181095975781a62c749f37f68d",
          "md5": "6a78e0d07986dfcbb0f058153bb7b88d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.34.4.aar",
          "url": "utils-0.34.4.aar",
          "size": 42946,
          "sha512": "0c0e4f0c496cf563e59db0776b617b2a9782967523b321c800fc9c3da11017a71bc8fce9b30755e7134e5960584ce7b3d0d1310cb18991f053a626dcac8e0d47",
          "sha256": "955fdad21c7f2c38e90063a21058d2bd389e3c0a8543fdfb9e9b3a1661c5b6a4",
          "sha1": "fec3a304b24ae4181095975781a62c749f37f68d",
          "md5": "6a78e0d07986dfcbb0f058153bb7b88d"
        }
      ]
    }
  ]
}
