{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qvpcucnmzrb4lhoa6wtow3rtda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.25.2.aar",
          "url": "utils-0.25.2.aar",
          "size": 39923,
          "sha512": "00bbc9c0b3725ce4f90456492b7f18f047e05945874f4698c62b013410f1559e53c8e51b23520a1d1b3ee8cc5bf2279d810c5213df3f550f580e5c95754303bd",
          "sha256": "39e58cf3c14cd728f7b0651b77ef160d2c973f707eb3a6a3bcf0965fcb717a85",
          "sha1": "e402e297150f547769804a9698a3f3accc4c9cbf",
          "md5": "489a717964e30d8f70ec52116a3a4e82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.25.2.aar",
          "url": "utils-0.25.2.aar",
          "size": 39923,
          "sha512": "00bbc9c0b3725ce4f90456492b7f18f047e05945874f4698c62b013410f1559e53c8e51b23520a1d1b3ee8cc5bf2279d810c5213df3f550f580e5c95754303bd",
          "sha256": "39e58cf3c14cd728f7b0651b77ef160d2c973f707eb3a6a3bcf0965fcb717a85",
          "sha1": "e402e297150f547769804a9698a3f3accc4c9cbf",
          "md5": "489a717964e30d8f70ec52116a3a4e82"
        }
      ]
    }
  ]
}
