{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.datatrans",
    "module": "android-sdk",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ug5caxupvvepdhllp5g3qdcf4a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-sdk-1.4.2.aar",
          "url": "android-sdk-1.4.2.aar",
          "size": 1593700,
          "sha512": "080ea8e70972e75c3ce101d989cd9afd7c85c71ed0024143268c46c71e86aeb95c772ef317ab0d41c5c066e11a89d3058a8b3ef61fc369979d21ea117cf64b61",
          "sha256": "fb36b93cb16e6174d645aec872d722acfc9574c72c1258cff557990c3dcf6dbb",
          "sha1": "b778175886d0d999f32f31800b9100b9672480af",
          "md5": "41694b48bb3f60d698c8ab24d0ae9570"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.twint.payment",
          "module": "twint-sdk-android",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "com.paypal.android",
          "module": "risk-component",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-rc02"
          }
        },
        {
          "group": "com.samsung.android.sdk",
          "module": "samsungpay",
          "version": {
            "requires": "2.8.00"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.card",
          "module": "android-sdk",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.4.2.aar",
          "url": "android-sdk-1.4.2.aar",
          "size": 1593700,
          "sha512": "080ea8e70972e75c3ce101d989cd9afd7c85c71ed0024143268c46c71e86aeb95c772ef317ab0d41c5c066e11a89d3058a8b3ef61fc369979d21ea117cf64b61",
          "sha256": "fb36b93cb16e6174d645aec872d722acfc9574c72c1258cff557990c3dcf6dbb",
          "sha1": "b778175886d0d999f32f31800b9100b9672480af",
          "md5": "41694b48bb3f60d698c8ab24d0ae9570"
        }
      ]
    }
  ]
}
