{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.34.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o75qremr5rhdhnsylosxqqpy7q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.4.aar",
          "url": "core-0.34.4.aar",
          "size": 330017,
          "sha512": "7de4ec44bedeed1e4e228e2b7a58f0ffbf0ad0efbdfdb1f0a76b109537831a95168787b3eaca79533dc5ff1947330bdce276f6f9643ac767aef0bf2ca115967e",
          "sha256": "a0c2994394481a6ac05727b2b839b5ee27c49ee1b2035afc7c47188fefb02667",
          "sha1": "7b312ddc9b985ec4ee0381b2ae8a6d58a8c22c17",
          "md5": "38b2d059cb29ccb869e8e7ae02b3c783"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.34.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.34.4.aar",
          "url": "core-0.34.4.aar",
          "size": 330017,
          "sha512": "7de4ec44bedeed1e4e228e2b7a58f0ffbf0ad0efbdfdb1f0a76b109537831a95168787b3eaca79533dc5ff1947330bdce276f6f9643ac767aef0bf2ca115967e",
          "sha256": "a0c2994394481a6ac05727b2b839b5ee27c49ee1b2035afc7c47188fefb02667",
          "sha1": "7b312ddc9b985ec4ee0381b2ae8a6d58a8c22c17",
          "md5": "38b2d059cb29ccb869e8e7ae02b3c783"
        }
      ]
    }
  ]
}
