{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.37.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gicizk74jvdfraga2c3626opse"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.12.aar",
          "url": "core-0.37.12.aar",
          "size": 352392,
          "sha512": "59887403c834d0e6d236a97e2d435199b4eff1781b80b1df5c949211c1783296766addf1526f79dd9a91bb92f8b01b3c44396a78e6a40e3fcdf98fb778f343e4",
          "sha256": "23f89f2bb7d2e6f9eeaf6e6407fc6b0c439ab8ac89bb8b24d308665a9a99d3db",
          "sha1": "8b8b3832023fe59d6e9f5feac7df5537c068be9d",
          "md5": "3b61b61d52c1f111661223c60afd3932"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.12"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.12.aar",
          "url": "core-0.37.12.aar",
          "size": 352392,
          "sha512": "59887403c834d0e6d236a97e2d435199b4eff1781b80b1df5c949211c1783296766addf1526f79dd9a91bb92f8b01b3c44396a78e6a40e3fcdf98fb778f343e4",
          "sha256": "23f89f2bb7d2e6f9eeaf6e6407fc6b0c439ab8ac89bb8b24d308665a9a99d3db",
          "sha1": "8b8b3832023fe59d6e9f5feac7df5537c068be9d",
          "md5": "3b61b61d52c1f111661223c60afd3932"
        }
      ]
    }
  ]
}
