{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.32.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hqpqhi4byza2bbgzmx2cx2k6di"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.4.aar",
          "url": "ui-integration-0.32.4.aar",
          "size": 75110,
          "sha512": "552e8b8e4982458c5d7c6a62ce171a3c31575ff5fef8a4610a614888cfac685c948ac2604c5574790c9e90139e8f30f8a05cb4028218d11bb2f9c59be061b932",
          "sha256": "9cfd6870849ea26592420dece0f2e2644fc92bd6cbcd07d2588dcf3eac567dec",
          "sha1": "72cd5e40ad9dd0dad722bb18ffb27d659c6ace39",
          "md5": "64d1707de1ddd8ecf746a06261955d53"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.32.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.32.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.32.4.aar",
          "url": "ui-integration-0.32.4.aar",
          "size": 75110,
          "sha512": "552e8b8e4982458c5d7c6a62ce171a3c31575ff5fef8a4610a614888cfac685c948ac2604c5574790c9e90139e8f30f8a05cb4028218d11bb2f9c59be061b932",
          "sha256": "9cfd6870849ea26592420dece0f2e2644fc92bd6cbcd07d2588dcf3eac567dec",
          "sha1": "72cd5e40ad9dd0dad722bb18ffb27d659c6ace39",
          "md5": "64d1707de1ddd8ecf746a06261955d53"
        }
      ]
    }
  ]
}
