{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.network",
    "module": "network",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "result",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.0-alpha2.jar",
          "url": "network-1.0.0-alpha2.jar",
          "size": 39128,
          "sha512": "e835bf6bd0cd7211e85801b34f8a2c70638fa5d611e3408ce0db7376842f91beb9a7663dc1e66554b2b45df76dc8f86beccdc9c45be51033f11399f3218b7837",
          "sha256": "4ddd7e7c87e18260572d73f2caced39df68f72c33ee6fcd3c2375310141507c3",
          "sha1": "f64c0a495f2a6af248ff270a9f1af2510a6d776b",
          "md5": "b354840b930bef9576bb796603337841"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.snabble.network",
          "module": "result",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.0-alpha2.jar",
          "url": "network-1.0.0-alpha2.jar",
          "size": 39128,
          "sha512": "e835bf6bd0cd7211e85801b34f8a2c70638fa5d611e3408ce0db7376842f91beb9a7663dc1e66554b2b45df76dc8f86beccdc9c45be51033f11399f3218b7837",
          "sha256": "4ddd7e7c87e18260572d73f2caced39df68f72c33ee6fcd3c2375310141507c3",
          "sha1": "f64c0a495f2a6af248ff270a9f1af2510a6d776b",
          "md5": "b354840b930bef9576bb796603337841"
        }
      ]
    }
  ]
}
