{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.33.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tvz5bixklbd4hnyg7hdagz6fhe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.0-beta02.aar",
          "url": "firebase-detector-0.33.0-beta02.aar",
          "size": 33050,
          "sha512": "3cb12b51017758ddd9749c6c07310ac9f3e2a2345450436625ba135bae79e5590c6709f77f2637a00e833425cf266e16cb128e01727b63b21d608763dcdc2310",
          "sha256": "475f1fc499982baf37e811892cb3a328f861252b6f8626c67fa53194f49156d0",
          "sha1": "7c031885eeb8adde48e738b70a5e95a85d624c33",
          "md5": "68437e48e32317a9bf0fa4b8660e860b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.33.0-beta02"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.33.0-beta02"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0-beta02"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.33.0-beta02.aar",
          "url": "firebase-detector-0.33.0-beta02.aar",
          "size": 33050,
          "sha512": "3cb12b51017758ddd9749c6c07310ac9f3e2a2345450436625ba135bae79e5590c6709f77f2637a00e833425cf266e16cb128e01727b63b21d608763dcdc2310",
          "sha256": "475f1fc499982baf37e811892cb3a328f861252b6f8626c67fa53194f49156d0",
          "sha1": "7c031885eeb8adde48e738b70a5e95a85d624c33",
          "md5": "68437e48e32317a9bf0fa4b8660e860b"
        }
      ]
    }
  ]
}
