{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.37.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "aasrpjvkivbijjgzgpeuo4x5gy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.5.aar",
          "url": "ui-integration-0.37.5.aar",
          "size": 99928,
          "sha512": "2beb5164dfcf11f2e50acbfe7888a902909c2250cd2517050c656d99109678cf88ecd2d639deb82e7a165b2a250e995bd899222b9a4783577abcff94c22ba35c",
          "sha256": "a921ddd4643e76a5ebee94846be3aabbc8ee2167ead23f7952efbb0e16560c04",
          "sha1": "92eda5a3639aa1b646c40cebf58820e37abfc4b3",
          "md5": "668258e3b2fcfe8a150cccc2731d9ccd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.37.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.37.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.5"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.5.aar",
          "url": "ui-integration-0.37.5.aar",
          "size": 99928,
          "sha512": "2beb5164dfcf11f2e50acbfe7888a902909c2250cd2517050c656d99109678cf88ecd2d639deb82e7a165b2a250e995bd899222b9a4783577abcff94c22ba35c",
          "sha256": "a921ddd4643e76a5ebee94846be3aabbc8ee2167ead23f7952efbb0e16560c04",
          "sha1": "92eda5a3639aa1b646c40cebf58820e37abfc4b3",
          "md5": "668258e3b2fcfe8a150cccc2731d9ccd"
        }
      ]
    }
  ]
}
