{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.network",
    "module": "api",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0-alpha1.jar",
          "url": "api-1.0.0-alpha1.jar",
          "size": 65901,
          "sha512": "580877ab8ee200c58b73b99925e9ed07f614f552b21e2f1639f74ab5aaa3f707d97018b3912432eadf24805bf191b8fdc525dea50d08f982103a9ef5fc007cf1",
          "sha256": "e35c6913366f31f096ab09c30803780246973aa701b1cceb93ed15550b11c6ab",
          "sha1": "c14a7cca9c90f02bcaa82aa9b69eeb569ce0bd12",
          "md5": "87c89a7696abfd63deb3b725d75f4971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "result",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0-alpha1.jar",
          "url": "api-1.0.0-alpha1.jar",
          "size": 65901,
          "sha512": "580877ab8ee200c58b73b99925e9ed07f614f552b21e2f1639f74ab5aaa3f707d97018b3912432eadf24805bf191b8fdc525dea50d08f982103a9ef5fc007cf1",
          "sha256": "e35c6913366f31f096ab09c30803780246973aa701b1cceb93ed15550b11c6ab",
          "sha1": "c14a7cca9c90f02bcaa82aa9b69eeb569ce0bd12",
          "md5": "87c89a7696abfd63deb3b725d75f4971"
        }
      ]
    }
  ]
}
