{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.52.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.52.0-beta02.aar",
          "url": "ui-integration-0.52.0-beta02.aar",
          "size": 103463,
          "sha512": "7296887e8bb0c2ad9af2c81f5de35e68ec5ea6c00cde88e79034ccdaf2f0a14ce4ec46199bfe7c39549d946b74103942b091c1036b3ea252ff51bc3dd52cc864",
          "sha256": "330333478e2bb34853e4e93d88ccbbcb6e4540aa9d9d0629f1ee39e7830ed319",
          "sha1": "e3f4f752c5197bafe48fa562095d7fad66b95547",
          "md5": "05f0fa07d9a40b8096063f2beeb7e0eb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.52.0-beta02"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.52.0-beta02"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.52.0-beta02"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.52.0-beta02.aar",
          "url": "ui-integration-0.52.0-beta02.aar",
          "size": 103463,
          "sha512": "7296887e8bb0c2ad9af2c81f5de35e68ec5ea6c00cde88e79034ccdaf2f0a14ce4ec46199bfe7c39549d946b74103942b091c1036b3ea252ff51bc3dd52cc864",
          "sha256": "330333478e2bb34853e4e93d88ccbbcb6e4540aa9d9d0629f1ee39e7830ed319",
          "sha1": "e3f4f752c5197bafe48fa562095d7fad66b95547",
          "md5": "05f0fa07d9a40b8096063f2beeb7e0eb"
        }
      ]
    }
  ]
}
