{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.35.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "r35ykfg6ajcobowcbmzibvcpfm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.4.aar",
          "url": "ui-integration-0.35.4.aar",
          "size": 93300,
          "sha512": "dac317ce6d69ed8aff726c170c3c6bac238f8d9f74db4654855c5205d7f05de78961e7b61eed3bb42683cde5cfaf81b94b31ad3b4a5864d1610d43f9b3631adc",
          "sha256": "c678fe82c834ef9f87f8877b2e694985c4408c0b6995a3a8cd53d31f67362a3f",
          "sha1": "35c1b2c23581a804bfd7b9dec2d2cd9da46b4057",
          "md5": "b4d30edf44d0508bcc488284279399e0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.35.4.aar",
          "url": "ui-integration-0.35.4.aar",
          "size": 93300,
          "sha512": "dac317ce6d69ed8aff726c170c3c6bac238f8d9f74db4654855c5205d7f05de78961e7b61eed3bb42683cde5cfaf81b94b31ad3b4a5864d1610d43f9b3631adc",
          "sha256": "c678fe82c834ef9f87f8877b2e694985c4408c0b6995a3a8cd53d31f67362a3f",
          "sha1": "35c1b2c23581a804bfd7b9dec2d2cd9da46b4057",
          "md5": "b4d30edf44d0508bcc488284279399e0"
        }
      ]
    }
  ]
}
