{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.53.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.53.0.aar",
          "url": "ui-integration-0.53.0.aar",
          "size": 107832,
          "sha512": "391ce2ea3027be4576779d23a6fa28062b50d1e4e23a59419a0896958732715b8d5e2db2f44e260403664d41f4dfff94666acafc012effd6f199d742b901e39f",
          "sha256": "cb5a289cb17ce2af25eae7c3bab3079323b7604339d305ac4079cad9c9f5f8c6",
          "sha1": "6bd4a087b01273f06fab00358d7c38d26559f533",
          "md5": "a20ffb0acdf9d8df7efd89f74023b258"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.53.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.53.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.53.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.53.0.aar",
          "url": "ui-integration-0.53.0.aar",
          "size": 107832,
          "sha512": "391ce2ea3027be4576779d23a6fa28062b50d1e4e23a59419a0896958732715b8d5e2db2f44e260403664d41f4dfff94666acafc012effd6f199d742b901e39f",
          "sha256": "cb5a289cb17ce2af25eae7c3bab3079323b7604339d305ac4079cad9c9f5f8c6",
          "sha1": "6bd4a087b01273f06fab00358d7c38d26559f533",
          "md5": "a20ffb0acdf9d8df7efd89f74023b258"
        }
      ]
    }
  ]
}
