{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.80.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.0.aar",
          "url": "core-0.80.0.aar",
          "size": 644834,
          "sha512": "714617c04076441fbb0abd8fb061b945179ed52170d91195203e6fada3df1bbd90288c7111c9a9ee10fb84471b1ec88df369aabb18054baadf16ff45f1ab9d77",
          "sha256": "30fb377b8bc1cf27efa5214cc3b1e1a57a1e1d5f49bff9e128790e5ad4cbc20e",
          "sha1": "b8642faed49d3073eb192e8638749b6e1496d9fd",
          "md5": "2782629344ef12a2d4c58fcd6151b5cc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.10-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.80.0.aar",
          "url": "core-0.80.0.aar",
          "size": 644834,
          "sha512": "714617c04076441fbb0abd8fb061b945179ed52170d91195203e6fada3df1bbd90288c7111c9a9ee10fb84471b1ec88df369aabb18054baadf16ff45f1ab9d77",
          "sha256": "30fb377b8bc1cf27efa5214cc3b1e1a57a1e1d5f49bff9e128790e5ad4cbc20e",
          "sha1": "b8642faed49d3073eb192e8638749b6e1496d9fd",
          "md5": "2782629344ef12a2d4c58fcd6151b5cc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.80.0-sources.jar",
          "url": "core-0.80.0-sources.jar",
          "size": 346449,
          "sha512": "c27a8aeeb2123601a441229d9496efceb4c28a0b698aabc31f239951b3aa34abf5b1445c06b0cfa2a33a0335170ffb943064bb6d5f39765e39e6ba79e1610b1c",
          "sha256": "a3616c522fd800140dc16c5a2cde9a39dff296a392c99a25c21a6f178c23fee3",
          "sha1": "72ff9e036ac49ff8c5390ee3d4d617c00585ce5b",
          "md5": "9ee994e34703ab36bae05894ef0bc330"
        }
      ]
    }
  ]
}
