{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "0.82.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.82.6.aar",
          "url": "accessibility-toolbox-0.82.6.aar",
          "size": 24621,
          "sha512": "9c4c78973defae57069478e1b71fd52b460037febe7f9c01e0fbdee59de26be9bd089396bf61fe89272c66413c17e6e44bac7ce0cb2ab1f93152f0fc17bcef3a",
          "sha256": "d6c354babe7b548fdfb43fff9bfe6e802157ecb93c559bef96b73b83ca98dd3d",
          "sha1": "06d7a517a58961225368dff2ba609756ef29b53f",
          "md5": "2329fbe7b0cd518ad94aac5504a09bdc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.82.6.aar",
          "url": "accessibility-toolbox-0.82.6.aar",
          "size": 24621,
          "sha512": "9c4c78973defae57069478e1b71fd52b460037febe7f9c01e0fbdee59de26be9bd089396bf61fe89272c66413c17e6e44bac7ce0cb2ab1f93152f0fc17bcef3a",
          "sha256": "d6c354babe7b548fdfb43fff9bfe6e802157ecb93c559bef96b73b83ca98dd3d",
          "sha1": "06d7a517a58961225368dff2ba609756ef29b53f",
          "md5": "2329fbe7b0cd518ad94aac5504a09bdc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "accessibility-toolbox-0.82.6-sources.jar",
          "url": "accessibility-toolbox-0.82.6-sources.jar",
          "size": 12626,
          "sha512": "3f9f1585c239ae14a313f5dbb39fd0740cabfdcc246f25446e9a35fbb02fc3130bf900290b16da4fd10cad62bffc1808a7c9ccf4c0daa6e4dc2cec96f29b79a4",
          "sha256": "e308d2ec23f593561dfe3673da36dedf37758c2fabba00219c0103ee805e6323",
          "sha1": "140aa188dff002bc42265fcd111b2dd72e44ad5b",
          "md5": "7e8a5b0da1c0f32e0cc9ccd7ece33d94"
        }
      ]
    }
  ]
}
