{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hqpqhi4byza2bbgzmx2cx2k6di"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.4.aar",
          "url": "core-0.32.4.aar",
          "size": 326039,
          "sha512": "a3f00e10350cff82db6a8235a3e82c3ef51af7536f9f697b4be6936982ed2a2663c39c4efe6db0da91694a67cbb4c261cd20b62a399470e5d950f46ed9c58294",
          "sha256": "483fbf30ed97b836ca837404ffbc108d3decd3bf9cc744896832abd2217f65fd",
          "sha1": "8b346e88d06097c52a2e03de2bc6a0b76eb7a5bb",
          "md5": "02abad96b03dfc899708a7c3ae1ab692"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.4.aar",
          "url": "core-0.32.4.aar",
          "size": 326039,
          "sha512": "a3f00e10350cff82db6a8235a3e82c3ef51af7536f9f697b4be6936982ed2a2663c39c4efe6db0da91694a67cbb4c261cd20b62a399470e5d950f46ed9c58294",
          "sha256": "483fbf30ed97b836ca837404ffbc108d3decd3bf9cc744896832abd2217f65fd",
          "sha1": "8b346e88d06097c52a2e03de2bc6a0b76eb7a5bb",
          "md5": "02abad96b03dfc899708a7c3ae1ab692"
        }
      ]
    }
  ]
}
