{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.48.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.48.2.aar",
          "url": "utils-0.48.2.aar",
          "size": 43748,
          "sha512": "1d76dea17fc4b3e1214bf2d37f375e31799311428ec6ccf6585b54d8af1d2b604e67e51310d44e512b9ab1187ee24e2875b8347b198309d40fb22a6a2513738d",
          "sha256": "55f0cb92f0a06377eca6a026560db49bf7633ed125d7b199c6fa7d735aab9f88",
          "sha1": "49665d8a1348e442019430d163883f787878ef13",
          "md5": "bdfe70961c461243f169cc16891c2a76"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.48.2.aar",
          "url": "utils-0.48.2.aar",
          "size": 43748,
          "sha512": "1d76dea17fc4b3e1214bf2d37f375e31799311428ec6ccf6585b54d8af1d2b604e67e51310d44e512b9ab1187ee24e2875b8347b198309d40fb22a6a2513738d",
          "sha256": "55f0cb92f0a06377eca6a026560db49bf7633ed125d7b199c6fa7d735aab9f88",
          "sha1": "49665d8a1348e442019430d163883f787878ef13",
          "md5": "bdfe70961c461243f169cc16891c2a76"
        }
      ]
    }
  ]
}
