{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "firebase-detector",
    "version": "0.35.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cekbw7vkgnerndfmmva5dxnj2m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.1.aar",
          "url": "firebase-detector-0.35.1.aar",
          "size": 40814,
          "sha512": "f67c1f9acdffd906a1deb8aa7daf03c1d9a427902f4b699ab1d33a6f4882faa56f2decc173606c02a66735c4509ce515437be59c020e55675ed858f60778373b",
          "sha256": "2cb2c3c847e60523ebad4a671baa92d075b913ce3b07254c1bb90df479e5d4e0",
          "sha1": "5ea2daadac6a6cda74d100c846cba144167d331a",
          "md5": "241e7d0d30da1ac68efa4b2e2967b5de"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.35.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ml-vision",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-detector-0.35.1.aar",
          "url": "firebase-detector-0.35.1.aar",
          "size": 40814,
          "sha512": "f67c1f9acdffd906a1deb8aa7daf03c1d9a427902f4b699ab1d33a6f4882faa56f2decc173606c02a66735c4509ce515437be59c020e55675ed858f60778373b",
          "sha256": "2cb2c3c847e60523ebad4a671baa92d075b913ce3b07254c1bb90df479e5d4e0",
          "sha1": "5ea2daadac6a6cda74d100c846cba144167d331a",
          "md5": "241e7d0d30da1ac68efa4b2e2967b5de"
        }
      ]
    }
  ]
}
