{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.42.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.42.1.aar",
          "url": "core-0.42.1.aar",
          "size": 377551,
          "sha512": "2b2a60b21064ab24c5817d8ddb87cc5ab0eb7639b999ae2fd9a260dd3b27b9e7c1419d58a924602829c3ef4b3ac84aa268fbfd3e7d6174f088dba2ee0927f9f3",
          "sha256": "66bdb0aafb1a1f33587f8c4bea3a3030cf8121e8c1a72a1fe8a4d61f8be67635",
          "sha1": "05afcbc7f499be96770dcb951c26f5daa464f7f0",
          "md5": "775d384881cefeb7d430c991287af83a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.42.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.42.1.aar",
          "url": "core-0.42.1.aar",
          "size": 377551,
          "sha512": "2b2a60b21064ab24c5817d8ddb87cc5ab0eb7639b999ae2fd9a260dd3b27b9e7c1419d58a924602829c3ef4b3ac84aa268fbfd3e7d6174f088dba2ee0927f9f3",
          "sha256": "66bdb0aafb1a1f33587f8c4bea3a3030cf8121e8c1a72a1fe8a4d61f8be67635",
          "sha1": "05afcbc7f499be96770dcb951c26f5daa464f7f0",
          "md5": "775d384881cefeb7d430c991287af83a"
        }
      ]
    }
  ]
}
