{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.network",
    "module": "core",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "api",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha1.jar",
          "url": "core-1.0.0-alpha1.jar",
          "size": 122032,
          "sha512": "0ebad5d40e4a9d0ee1112a1ee7471d0a96282262b48f0aabe78f39092031de7e1bda3b8506f69869c2ac813739271142fc57f13bd797f974a7f9ceff94760f8b",
          "sha256": "79c9eefe787f2f365dc4af3037964ae88120831c221533a5aa20bbb7db4df5a5",
          "sha1": "c79eb521f9bcaa1996fd0db840090f37ac05e38f",
          "md5": "08212f00bc920dbe2f1a595bdfbb7c19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.network",
          "module": "result",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.snabble.network",
          "module": "api",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-alpha1.jar",
          "url": "core-1.0.0-alpha1.jar",
          "size": 122032,
          "sha512": "0ebad5d40e4a9d0ee1112a1ee7471d0a96282262b48f0aabe78f39092031de7e1bda3b8506f69869c2ac813739271142fc57f13bd797f974a7f9ceff94760f8b",
          "sha256": "79c9eefe787f2f365dc4af3037964ae88120831c221533a5aa20bbb7db4df5a5",
          "sha1": "c79eb521f9bcaa1996fd0db840090f37ac05e38f",
          "md5": "08212f00bc920dbe2f1a595bdfbb7c19"
        }
      ]
    }
  ]
}
