{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lu5zwczqn5bzhkzih5ir6fb76i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.0.aar",
          "url": "core-0.26.0.aar",
          "size": 272900,
          "sha512": "fc0c2249b5fb48beb2064c40c58955dc26ee1a7d7893f06481ec6693cd014fd92a316d563401c2246cd5f637b6b3ed052c96f9a47d1e66ff66d1a567a62f9f86",
          "sha256": "2c9c029f25d8e287288876e8faaf4462ff8d2bb5c5251e62e39ed77245a2fb1d",
          "sha1": "afc6928fbf220c0da64a068414ef2ba7d722164d",
          "md5": "12f68f225ca61ecb429fb81f01778c88"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.0.aar",
          "url": "core-0.26.0.aar",
          "size": 272900,
          "sha512": "fc0c2249b5fb48beb2064c40c58955dc26ee1a7d7893f06481ec6693cd014fd92a316d563401c2246cd5f637b6b3ed052c96f9a47d1e66ff66d1a567a62f9f86",
          "sha256": "2c9c029f25d8e287288876e8faaf4462ff8d2bb5c5251e62e39ed77245a2fb1d",
          "sha1": "afc6928fbf220c0da64a068414ef2ba7d722164d",
          "md5": "12f68f225ca61ecb429fb81f01778c88"
        }
      ]
    }
  ]
}
