{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.24.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4hu6kew2fnfs5mmeyqbymjjzou"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.24.6-SNAPSHOT.aar",
          "url": "core-0.24.6-SNAPSHOT.aar",
          "size": 269319,
          "sha512": "ffa35f154b72e669983151175aad2ce47e75b315aac3db478c3f86bf9bcd773ffac3120c72189d4ee3e8970f2fb485c8c31262dae77323742e19b094a8ad1ce7",
          "sha256": "700bb09bc6907cd759d39c3811237b807f5a1f5ae8cac226fc6811656fafb308",
          "sha1": "ca81d4c88044510fa0bdcab912fdaf8e4a37ed28",
          "md5": "dcb1c346c61e187e7162e1136dd49dd0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.24.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.24.6-SNAPSHOT.aar",
          "url": "core-0.24.6-SNAPSHOT.aar",
          "size": 269319,
          "sha512": "ffa35f154b72e669983151175aad2ce47e75b315aac3db478c3f86bf9bcd773ffac3120c72189d4ee3e8970f2fb485c8c31262dae77323742e19b094a8ad1ce7",
          "sha256": "700bb09bc6907cd759d39c3811237b807f5a1f5ae8cac226fc6811656fafb308",
          "sha1": "ca81d4c88044510fa0bdcab912fdaf8e4a37ed28",
          "md5": "dcb1c346c61e187e7162e1136dd49dd0"
        }
      ]
    }
  ]
}
