{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.29.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jtlafxkhrbgjddsb44tcl7ot6q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.7.aar",
          "url": "utils-0.29.7.aar",
          "size": 40158,
          "sha512": "c797df62a6557419f0923953c846dd4391501c93b8c310afad52bd5a95e60796e2a5e565f0649cb88af3b1ae18cd7a2027976793214da0eeee87cb3b9b1fe43c",
          "sha256": "aa25b63f149567111433814aa086b79a164d6dfd1a1bdbb3168cc1aa15baef48",
          "sha1": "924f2012d1692161a8bf6a316aadaa998f9cb9ff",
          "md5": "4e7e4cd4143165be34fef862342b8974"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.29.7.aar",
          "url": "utils-0.29.7.aar",
          "size": 40158,
          "sha512": "c797df62a6557419f0923953c846dd4391501c93b8c310afad52bd5a95e60796e2a5e565f0649cb88af3b1ae18cd7a2027976793214da0eeee87cb3b9b1fe43c",
          "sha256": "aa25b63f149567111433814aa086b79a164d6dfd1a1bdbb3168cc1aa15baef48",
          "sha1": "924f2012d1692161a8bf6a316aadaa998f9cb9ff",
          "md5": "4e7e4cd4143165be34fef862342b8974"
        }
      ]
    }
  ]
}
