{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.33.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "g3fcevxhdrcyxgfxkbyanfojpq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta04.aar",
          "url": "core-0.33.0-beta04.aar",
          "size": 327623,
          "sha512": "dd982b18aa87c1a89273e1edcf6a589ae9185eff961467495d694c4d2577e4e7b8d60a4f3520907c94d7ca06152848873a069c1040469218cdfa8608ec319bb6",
          "sha256": "9796d98822cdf2b407281b889698d81882d28f5ae28f799fbacb522fd0632bd2",
          "sha1": "e921ac839abad8bc863a35ebd0f53ca7c159a0f8",
          "md5": "32ecac6e2a9f1aaab0844cc0124cdbb0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.33.0-beta04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.33.0-beta04.aar",
          "url": "core-0.33.0-beta04.aar",
          "size": 327623,
          "sha512": "dd982b18aa87c1a89273e1edcf6a589ae9185eff961467495d694c4d2577e4e7b8d60a4f3520907c94d7ca06152848873a069c1040469218cdfa8608ec319bb6",
          "sha256": "9796d98822cdf2b407281b889698d81882d28f5ae28f799fbacb522fd0632bd2",
          "sha1": "e921ac839abad8bc863a35ebd0f53ca7c159a0f8",
          "md5": "32ecac6e2a9f1aaab0844cc0124cdbb0"
        }
      ]
    }
  ]
}
