{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.37.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "u4hckh5agrfzxfz6bo75qmru64"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.8.aar",
          "url": "ui-integration-0.37.8.aar",
          "size": 99929,
          "sha512": "537774b04ccdeb61b065c3f9a4b162982e9fa8dee3f00d5341419b6de95a305ef8ccc1201e72796459afc5dc4c8a8cb43cfadd6e2f0af5a52a1fe6cfe95c8afd",
          "sha256": "e3ca8d37b60f97c515e2c3fa13b5147c82bb2275dad9ecf03041619ce623d53b",
          "sha1": "24bdb3b057f5c5c2ac2dec74ef266b1ddfeac479",
          "md5": "63aa700895a9aaedb4c42dd30e858a6e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.37.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.37.8"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.8"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.8.aar",
          "url": "ui-integration-0.37.8.aar",
          "size": 99929,
          "sha512": "537774b04ccdeb61b065c3f9a4b162982e9fa8dee3f00d5341419b6de95a305ef8ccc1201e72796459afc5dc4c8a8cb43cfadd6e2f0af5a52a1fe6cfe95c8afd",
          "sha256": "e3ca8d37b60f97c515e2c3fa13b5147c82bb2275dad9ecf03041619ce623d53b",
          "sha1": "24bdb3b057f5c5c2ac2dec74ef266b1ddfeac479",
          "md5": "63aa700895a9aaedb4c42dd30e858a6e"
        }
      ]
    }
  ]
}
