{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "0.82.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.82.0.aar",
          "url": "accessibility-toolbox-0.82.0.aar",
          "size": 24627,
          "sha512": "64c4db02b2c7e0717a3e80bf0548c5e3cc452f2a14aaa7a05b26634895e9e826ca807c8cca5eb33ff2587afadf30cf2e4561da46ca8151febe13b3707eaef227",
          "sha256": "fd3647ee0e723ca7d0424f73c8a7f589eb58fb97edfdc73275e93c5a15f107b7",
          "sha1": "a4f07dcecf76965006a78e0ae1ee6a40a8569050",
          "md5": "0ba6ad0c77910689f8e5f0f78e8ffb10"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.82.0.aar",
          "url": "accessibility-toolbox-0.82.0.aar",
          "size": 24627,
          "sha512": "64c4db02b2c7e0717a3e80bf0548c5e3cc452f2a14aaa7a05b26634895e9e826ca807c8cca5eb33ff2587afadf30cf2e4561da46ca8151febe13b3707eaef227",
          "sha256": "fd3647ee0e723ca7d0424f73c8a7f589eb58fb97edfdc73275e93c5a15f107b7",
          "sha1": "a4f07dcecf76965006a78e0ae1ee6a40a8569050",
          "md5": "0ba6ad0c77910689f8e5f0f78e8ffb10"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "accessibility-toolbox-0.82.0-sources.jar",
          "url": "accessibility-toolbox-0.82.0-sources.jar",
          "size": 12626,
          "sha512": "3f9f1585c239ae14a313f5dbb39fd0740cabfdcc246f25446e9a35fbb02fc3130bf900290b16da4fd10cad62bffc1808a7c9ccf4c0daa6e4dc2cec96f29b79a4",
          "sha256": "e308d2ec23f593561dfe3673da36dedf37758c2fabba00219c0103ee805e6323",
          "sha1": "140aa188dff002bc42265fcd111b2dd72e44ad5b",
          "md5": "7e8a5b0da1c0f32e0cc9ccd7ece33d94"
        }
      ]
    }
  ]
}
