{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.71.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.4.aar",
          "url": "core-0.71.4.aar",
          "size": 591505,
          "sha512": "7a9efcee34c6eef99e68626c0cad73b32211be3c9d1d01c31861e0adcf0602ddbe844a434d13fdc1c75769b24218181d1f5e0d4d07176f74db59fbb86a3d2fd5",
          "sha256": "f19bdd1b9acfe9031f096c2e537eeb99f8cde56fcdc471dbf0e003a84730fcca",
          "sha1": "88f918ba6bf623eef1998c02d2e6b6b7f15ca3c5",
          "md5": "724dbb9c75be96c15394439b2266fcba"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.4.aar",
          "url": "core-0.71.4.aar",
          "size": 591505,
          "sha512": "7a9efcee34c6eef99e68626c0cad73b32211be3c9d1d01c31861e0adcf0602ddbe844a434d13fdc1c75769b24218181d1f5e0d4d07176f74db59fbb86a3d2fd5",
          "sha256": "f19bdd1b9acfe9031f096c2e537eeb99f8cde56fcdc471dbf0e003a84730fcca",
          "sha1": "88f918ba6bf623eef1998c02d2e6b6b7f15ca3c5",
          "md5": "724dbb9c75be96c15394439b2266fcba"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.71.4-sources.jar",
          "url": "core-0.71.4-sources.jar",
          "size": 327567,
          "sha512": "8bc5f0d6d9caf59e355b36ab56eb15d12a321582345c76bab757e5ec803648486776f9efdf896d1abd9645a913af030bcc992277205a3b93a3a1e493b0e48ed8",
          "sha256": "9aae260d412d7a5305bd8525f95aaa363709e76781eae6b3c0c42d429047e1fa",
          "sha1": "91c59eda370fa26ab374fcf2e46c1fd26928ac2c",
          "md5": "4a656e1038f2d93f8a1bd7eeefe57cef"
        }
      ]
    }
  ]
}
