{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.37.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5mapnmlp2zdz7aj7mau373bjqq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.0.aar",
          "url": "core-0.37.0.aar",
          "size": 351946,
          "sha512": "182e2ad8de733e0a77145a5f00802863056ef9c18843ffb869cf676db69e2dcb6eb7b84335aa999ecb0c29527d835bd5f0c20ef9ecab04bd4c22bad3df7765ce",
          "sha256": "030a499ed03dd931b52a4f441da51a98f070329f92678dcdf98ac4d69ab98d0e",
          "sha1": "c4b24a63d76c67b99debc893efc0c714e56a5ab7",
          "md5": "454cb6ebaa1e362f17252f5a3daca101"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.37.0.aar",
          "url": "core-0.37.0.aar",
          "size": 351946,
          "sha512": "182e2ad8de733e0a77145a5f00802863056ef9c18843ffb869cf676db69e2dcb6eb7b84335aa999ecb0c29527d835bd5f0c20ef9ecab04bd4c22bad3df7765ce",
          "sha256": "030a499ed03dd931b52a4f441da51a98f070329f92678dcdf98ac4d69ab98d0e",
          "sha1": "c4b24a63d76c67b99debc893efc0c714e56a5ab7",
          "md5": "454cb6ebaa1e362f17252f5a3daca101"
        }
      ]
    }
  ]
}
