{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pxwkauswsvh2la5rhzsezbbsem"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.6.aar",
          "url": "core-0.29.6.aar",
          "size": 287573,
          "sha512": "d9b04f1b90353dfa232d4ec9285b33f362e9eed73cb1e4bb60eab0ef56dc8bcb4bdf9acbee89d8256a3a47809ee90258624a3f3cfd5a0419287a887e4cf97cb6",
          "sha256": "76a6559ef0f6bfb918efb745d5847caab26a9b9a1a1423e4f5b0d09c4e62dcf3",
          "sha1": "aa19b0977f4ed296565576458da49aa065fbeceb",
          "md5": "522c681b8679e1bde0f8c55559d9a0e0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.6.aar",
          "url": "core-0.29.6.aar",
          "size": 287573,
          "sha512": "d9b04f1b90353dfa232d4ec9285b33f362e9eed73cb1e4bb60eab0ef56dc8bcb4bdf9acbee89d8256a3a47809ee90258624a3f3cfd5a0419287a887e4cf97cb6",
          "sha256": "76a6559ef0f6bfb918efb745d5847caab26a9b9a1a1423e4f5b0d09c4e62dcf3",
          "sha1": "aa19b0977f4ed296565576458da49aa065fbeceb",
          "md5": "522c681b8679e1bde0f8c55559d9a0e0"
        }
      ]
    }
  ]
}
