{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "utils",
    "version": "0.48.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.48.4.aar",
          "url": "utils-0.48.4.aar",
          "size": 44388,
          "sha512": "81ed0c0bc372e258edb77c8dacd0ebd2562ac9022584c26025c6ba2b8aac655381086a5246f170427e31d585bfa4a696126e3a443184c3d7f163eabe238a0620",
          "sha256": "94d105ca10974f142adfa5d5511f5c9719d51fae25080be8a0f571f8930bdab4",
          "sha1": "5a3f497c16c8609133185c10f631ffb92566d2be",
          "md5": "5a1bdf29400176b4de2648bd5c9d0846"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.48.4.aar",
          "url": "utils-0.48.4.aar",
          "size": 44388,
          "sha512": "81ed0c0bc372e258edb77c8dacd0ebd2562ac9022584c26025c6ba2b8aac655381086a5246f170427e31d585bfa4a696126e3a443184c3d7f163eabe238a0620",
          "sha256": "94d105ca10974f142adfa5d5511f5c9719d51fae25080be8a0f571f8930bdab4",
          "sha1": "5a3f497c16c8609133185c10f631ffb92566d2be",
          "md5": "5a1bdf29400176b4de2648bd5c9d0846"
        }
      ]
    }
  ]
}
