{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.phoneauth",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 138287,
          "sha512": "31f21e0fd173a951c1c63096d4bb1f77581c5616f199cfcfb7d20264ee4c006736c9bcd7343b2f695a2f1154191604ab784c7e41f19dfef0b6f5e8f995751ff4",
          "sha256": "a058afa91b59e564efa226f1b4661ca690b0d145be3bb651aa9233cb7468fd6e",
          "sha1": "e14c8668792d52ca71b746e11a60730b781a9836",
          "md5": "44d481c8a830031a15a1a7521c2648ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.phoneauth",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 138287,
          "sha512": "31f21e0fd173a951c1c63096d4bb1f77581c5616f199cfcfb7d20264ee4c006736c9bcd7343b2f695a2f1154191604ab784c7e41f19dfef0b6f5e8f995751ff4",
          "sha256": "a058afa91b59e564efa226f1b4661ca690b0d145be3bb651aa9233cb7468fd6e",
          "sha1": "e14c8668792d52ca71b746e11a60730b781a9836",
          "md5": "44d481c8a830031a15a1a7521c2648ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 24089,
          "sha512": "2a1dc2b0466c63d23124da6b1706c606194b5b5bca23d7ab4b624b896d9a58c5a1a0fadadb5facb77397a8c2fe1258684fa1e13687e26f0f46e14e526323d0b4",
          "sha256": "1d0335ec4eefe8c8dbba8e4e11dd75c88f1c766da4ca3df02908493755d5ccca",
          "sha1": "0353f59bda7c1ec47c4d0aa6d3c37c4aadc4f362",
          "md5": "b2225e63965cca33162c480697e750a0"
        }
      ]
    }
  ]
}
