{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.50.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.50.0.aar",
          "url": "ui-integration-0.50.0.aar",
          "size": 100867,
          "sha512": "c22bebaf1f19985a596b066338a15faecfc816e6c77eed901318a47bcc77db867cf19be74203d42e145777abdbc790c25754de4f03f12d4c67b194d311fdd8ee",
          "sha256": "842c665fcc14ed3e8f6b8ae38899a6e7c8aa418add2313b13de1f51a9cfd70ae",
          "sha1": "cbc1a3fa66b009c73d99254ac25b07d5fe174f61",
          "md5": "6521e34f2f032981afcd5ef582440899"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.50.0.aar",
          "url": "ui-integration-0.50.0.aar",
          "size": 100867,
          "sha512": "c22bebaf1f19985a596b066338a15faecfc816e6c77eed901318a47bcc77db867cf19be74203d42e145777abdbc790c25754de4f03f12d4c67b194d311fdd8ee",
          "sha256": "842c665fcc14ed3e8f6b8ae38899a6e7c8aa418add2313b13de1f51a9cfd70ae",
          "sha1": "cbc1a3fa66b009c73d99254ac25b07d5fe174f61",
          "md5": "6521e34f2f032981afcd5ef582440899"
        }
      ]
    }
  ]
}
