{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.38.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "i2hthj6spjfn5l6ya6riaggcoi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.38.1.aar",
          "url": "ui-integration-0.38.1.aar",
          "size": 100044,
          "sha512": "2b18cb2be0fb59ce08a86710825eb127feda9e9df37663f21b3dcb157d0e4f70677bce9a5d050fe7316f1b6b47a22e53f5e73976d2ee35494b5f7327404a6af0",
          "sha256": "ffaaa2d68bf155676aad6be0be7ded3ffae57d1429d42d17ee97d3037daf54a6",
          "sha1": "ebe8988cf5214e726314b40e60e385c25711521c",
          "md5": "59cb0311d1527ec0f9e288a04c693e27"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.38.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.38.1"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.38.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.38.1.aar",
          "url": "ui-integration-0.38.1.aar",
          "size": 100044,
          "sha512": "2b18cb2be0fb59ce08a86710825eb127feda9e9df37663f21b3dcb157d0e4f70677bce9a5d050fe7316f1b6b47a22e53f5e73976d2ee35494b5f7327404a6af0",
          "sha256": "ffaaa2d68bf155676aad6be0be7ded3ffae57d1429d42d17ee97d3037daf54a6",
          "sha1": "ebe8988cf5214e726314b40e60e385c25711521c",
          "md5": "59cb0311d1527ec0f9e288a04c693e27"
        }
      ]
    }
  ]
}
