{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.72.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.0.aar",
          "url": "core-0.72.0.aar",
          "size": 593827,
          "sha512": "083498982e69e70a44542b610b856541a5d499b1ed3bc77eed3bf1417560d552a7f9dd491747e031bdf9e69881811ab72634a7da821a0388e00efbd710765e8e",
          "sha256": "a62233739cfcfab0a3b03c5ef68a5bff619ca3294d101a85fdc441f030b6a0ca",
          "sha1": "513acb45dcb334e9c2de0b1558104e8700263ad7",
          "md5": "d80af9274830e8741d5403abf9f0d0a1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.0.aar",
          "url": "core-0.72.0.aar",
          "size": 593827,
          "sha512": "083498982e69e70a44542b610b856541a5d499b1ed3bc77eed3bf1417560d552a7f9dd491747e031bdf9e69881811ab72634a7da821a0388e00efbd710765e8e",
          "sha256": "a62233739cfcfab0a3b03c5ef68a5bff619ca3294d101a85fdc441f030b6a0ca",
          "sha1": "513acb45dcb334e9c2de0b1558104e8700263ad7",
          "md5": "d80af9274830e8741d5403abf9f0d0a1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.72.0-sources.jar",
          "url": "core-0.72.0-sources.jar",
          "size": 329081,
          "sha512": "383ad726ca66af756ac4e581e1d89d832eae84927b64039fcd884815ccb4adc83bb3cae5ca81c4bc2aaa5f4b048b69541a62b3e9e6dcbee137b68597a1a95a01",
          "sha256": "af02bfaf0afeabcfc1eb5df484d91f5297866fc9067d6acc20206a59378988f5",
          "sha1": "cdcc4eabb295575826a9f41f75acf3e0d10f9f76",
          "md5": "8e907eea2131dbb2711661ed88c142c4"
        }
      ]
    }
  ]
}
