{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.29.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jtlafxkhrbgjddsb44tcl7ot6q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.7.aar",
          "url": "core-0.29.7.aar",
          "size": 287572,
          "sha512": "143dfe6a3e8aa78d59e27c0146bccf87cfbd32e0c099673e40e08bfe226c4c8e18ab665359ae4181d481b60b63e2381a0a13d56ff0ab3f6f839d2ce6ff1a4346",
          "sha256": "8b2063d487b6d1a8ac610ce0ed91d244bb03405ae4da9ca7c17b74f1275fc081",
          "sha1": "c6dc22bdb33a14c51c639a7850b577245674e0c7",
          "md5": "4e870c88e41ae9d24a2e60eaab34369d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.29.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.29.7.aar",
          "url": "core-0.29.7.aar",
          "size": 287572,
          "sha512": "143dfe6a3e8aa78d59e27c0146bccf87cfbd32e0c099673e40e08bfe226c4c8e18ab665359ae4181d481b60b63e2381a0a13d56ff0ab3f6f839d2ce6ff1a4346",
          "sha256": "8b2063d487b6d1a8ac610ce0ed91d244bb03405ae4da9ca7c17b74f1275fc081",
          "sha1": "c6dc22bdb33a14c51c639a7850b577245674e0c7",
          "md5": "4e870c88e41ae9d24a2e60eaab34369d"
        }
      ]
    }
  ]
}
