{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "accessibility-toolbox",
    "version": "0.70.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.70.0.aar",
          "url": "accessibility-toolbox-0.70.0.aar",
          "size": 25700,
          "sha512": "ac58b7558ae7e376f0f2ad236bac284f6a4f619b2e6b1b89a340789a264ed4e2eeb4e38dd0f17cfa9b7888bba7f02f47316a7ffcda9150a65a3bd1584fd1f235",
          "sha256": "9f7c50a74c449780c2bab7c077a66f793add1d60e6d3e69592766add5e506080",
          "sha1": "44bd0173f3defbc77ecad3d6fabe64487eea99e9",
          "md5": "602c9696b28782dc3e5ff563183ba7e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.70.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "accessibility-toolbox-0.70.0.aar",
          "url": "accessibility-toolbox-0.70.0.aar",
          "size": 25700,
          "sha512": "ac58b7558ae7e376f0f2ad236bac284f6a4f619b2e6b1b89a340789a264ed4e2eeb4e38dd0f17cfa9b7888bba7f02f47316a7ffcda9150a65a3bd1584fd1f235",
          "sha256": "9f7c50a74c449780c2bab7c077a66f793add1d60e6d3e69592766add5e506080",
          "sha1": "44bd0173f3defbc77ecad3d6fabe64487eea99e9",
          "md5": "602c9696b28782dc3e5ff563183ba7e1"
        }
      ]
    }
  ]
}
