{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.75.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.3.aar",
          "url": "core-0.75.3.aar",
          "size": 638473,
          "sha512": "963eef1e5629ad9d57f9a91c4f7627562535dfaef36b0ef3258fdfbc6aa513b02275224465e4b7be088fb9eb8c18ca6e4452911c6d15b8407df37707eb9b6bd5",
          "sha256": "4163fc46913cc32cecb2f77b633c2727870874b5e6be9f0b7966b9621bb4a205",
          "sha1": "165c505c01404336a43013e82cf349f0757c183d",
          "md5": "b4372737850374fa258a58b5e70a3862"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.75.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.75.3.aar",
          "url": "core-0.75.3.aar",
          "size": 638473,
          "sha512": "963eef1e5629ad9d57f9a91c4f7627562535dfaef36b0ef3258fdfbc6aa513b02275224465e4b7be088fb9eb8c18ca6e4452911c6d15b8407df37707eb9b6bd5",
          "sha256": "4163fc46913cc32cecb2f77b633c2727870874b5e6be9f0b7966b9621bb4a205",
          "sha1": "165c505c01404336a43013e82cf349f0757c183d",
          "md5": "b4372737850374fa258a58b5e70a3862"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.75.3-sources.jar",
          "url": "core-0.75.3-sources.jar",
          "size": 343839,
          "sha512": "12a0f7fad4c84110214b68530a803542366e9e93e41326c5b29269dab7005a1bcaa15820035cec60d2c6d1c6a5608115dde5258c7af46b5ffe693f9d74947e07",
          "sha256": "891995881c0a05a9dbdf79e49f64490151c0c213ace268a6d926ba9862fea4ef",
          "sha1": "caeae6d28cb570949159c87f4ad809a11202c105",
          "md5": "568e70449dedd6f4b89c24536d850de7"
        }
      ]
    }
  ]
}
