{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.80.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.3.aar",
          "url": "mlkit-scanner-engine-0.80.3.aar",
          "size": 63883,
          "sha512": "b3f391837d3e24c6fdbc1c50e9a0b4cee8c7e4643fdbe8f24f347b340c888d254cde35cdcdd6b1c4bca2227f904cab3be48f9ce49ccbf526a6c49d472e757234",
          "sha256": "e5a3b82e37102dc765b37f5e20095b3e16007ce7bd05e96ef47aa8da844e1a18",
          "sha1": "a87726aaeb60776d0e212f88e579ccf8647ea0e3",
          "md5": "a84d750e8aac80b0cf49dd7715bbb689"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.80.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.80.3"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.3.aar",
          "url": "mlkit-scanner-engine-0.80.3.aar",
          "size": 63883,
          "sha512": "b3f391837d3e24c6fdbc1c50e9a0b4cee8c7e4643fdbe8f24f347b340c888d254cde35cdcdd6b1c4bca2227f904cab3be48f9ce49ccbf526a6c49d472e757234",
          "sha256": "e5a3b82e37102dc765b37f5e20095b3e16007ce7bd05e96ef47aa8da844e1a18",
          "sha1": "a87726aaeb60776d0e212f88e579ccf8647ea0e3",
          "md5": "a84d750e8aac80b0cf49dd7715bbb689"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.3-sources.jar",
          "url": "mlkit-scanner-engine-0.80.3-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
