{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.37.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6eexwf5wyrditlxgzyd76h2xae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.9.aar",
          "url": "ui-integration-0.37.9.aar",
          "size": 99957,
          "sha512": "f912c3285e2848d96ea9267e6f5ef6f44f816372522f68fde2644e8be25d3ac83b20bbf255a18d7168e4191f53c9c5139a93444576fc2d46d23934a0506d1d2e",
          "sha256": "82c76a8053fd615be1c4ba0a6f1e380a58e0cb4125ce88066b43ec615d3588bb",
          "sha1": "134339395e08899f78036513b06a2167d8b7c4eb",
          "md5": "781b4d1c8f70eba71520525c8829f246"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.37.9"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.37.9"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.37.9"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.37.9.aar",
          "url": "ui-integration-0.37.9.aar",
          "size": 99957,
          "sha512": "f912c3285e2848d96ea9267e6f5ef6f44f816372522f68fde2644e8be25d3ac83b20bbf255a18d7168e4191f53c9c5139a93444576fc2d46d23934a0506d1d2e",
          "sha256": "82c76a8053fd615be1c4ba0a6f1e380a58e0cb4125ce88066b43ec615d3588bb",
          "sha1": "134339395e08899f78036513b06a2167d8b7c4eb",
          "md5": "781b4d1c8f70eba71520525c8829f246"
        }
      ]
    }
  ]
}
