{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4fidkbhpcfc5ncwzvfc7lt4zwy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.2.aar",
          "url": "core-0.32.2.aar",
          "size": 325928,
          "sha512": "3e835a59cc58e986d4bbea3666d92ff907b2c257f96b24c60a81ffee2b17ed1351e579b58e1618769219d48692ae1fdf745ad52a3e7c42a451495cfd96a2e324",
          "sha256": "b6b6d2363141b779c009b06c2f032e1f78392fd317665dfcd70ba7491d648fe7",
          "sha1": "2d9896a77a3c2c90300d165f0b804f3962aa48e2",
          "md5": "051d504a6bf66ad5f461a27517cc98aa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.2.aar",
          "url": "core-0.32.2.aar",
          "size": 325928,
          "sha512": "3e835a59cc58e986d4bbea3666d92ff907b2c257f96b24c60a81ffee2b17ed1351e579b58e1618769219d48692ae1fdf745ad52a3e7c42a451495cfd96a2e324",
          "sha256": "b6b6d2363141b779c009b06c2f032e1f78392fd317665dfcd70ba7491d648fe7",
          "sha1": "2d9896a77a3c2c90300d165f0b804f3962aa48e2",
          "md5": "051d504a6bf66ad5f461a27517cc98aa"
        }
      ]
    }
  ]
}
