{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.39.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vyzcic7h3jgrrmxmk7vu2u4jkm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.39.5.aar",
          "url": "ui-integration-0.39.5.aar",
          "size": 100138,
          "sha512": "ed1979135184b16d94ca5686e8eb70522bf8e4b6ccfaa2450e3c27b2f3cd3867a47a2408fa079347aa6acf81afd8dbbb3a0f75e707fbca5325b097c95878644f",
          "sha256": "7caa7fcfc7e791e019e250e357a136aa3f6b6036c009e22f026bec349f436618",
          "sha1": "33f7c1a40fd244e3965cbb98be90b7a93f9e897a",
          "md5": "8fba546dd6f06a91c31d337515a9ea7a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.39.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.39.5"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.5"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.39.5.aar",
          "url": "ui-integration-0.39.5.aar",
          "size": 100138,
          "sha512": "ed1979135184b16d94ca5686e8eb70522bf8e4b6ccfaa2450e3c27b2f3cd3867a47a2408fa079347aa6acf81afd8dbbb3a0f75e707fbca5325b097c95878644f",
          "sha256": "7caa7fcfc7e791e019e250e357a136aa3f6b6036c009e22f026bec349f436618",
          "sha1": "33f7c1a40fd244e3965cbb98be90b7a93f9e897a",
          "md5": "8fba546dd6f06a91c31d337515a9ea7a"
        }
      ]
    }
  ]
}
