{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.82.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.4.aar",
          "url": "mlkit-scanner-engine-0.82.4.aar",
          "size": 68558,
          "sha512": "bdc11d794f0cd43042d8b8ce366512143f61be9c946c7979bb98c34ae68cd5dd823501f4e42b64bf8fa8501de91d6f0f0a6321aa97b6bcae2b5dfeb96aafd520",
          "sha256": "6d9ef1c495720af5b6eaed2ef50267cece20390a051019b4c321d14e9f06ce91",
          "sha1": "d547649b1e3b4122f9ad6485370f941c611a27a9",
          "md5": "86e26b0954b6da518c4266c06d498ca1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.82.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.82.4"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.82.4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.4.aar",
          "url": "mlkit-scanner-engine-0.82.4.aar",
          "size": 68558,
          "sha512": "bdc11d794f0cd43042d8b8ce366512143f61be9c946c7979bb98c34ae68cd5dd823501f4e42b64bf8fa8501de91d6f0f0a6321aa97b6bcae2b5dfeb96aafd520",
          "sha256": "6d9ef1c495720af5b6eaed2ef50267cece20390a051019b4c321d14e9f06ce91",
          "sha1": "d547649b1e3b4122f9ad6485370f941c611a27a9",
          "md5": "86e26b0954b6da518c4266c06d498ca1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.82.4-sources.jar",
          "url": "mlkit-scanner-engine-0.82.4-sources.jar",
          "size": 7461,
          "sha512": "221159708b9b3989fce5be7004949d5bc0fd9004ca06e5e7133c8463ef545036a99acfbbff07d8a5f7c45086a01c1027bb7ab5ed21ab5a39c3a946d89a0d1642",
          "sha256": "4c1778dc04c1bff7ab6efb7aef8d27e937239e5676c3213b6d304cf1b24234f8",
          "sha1": "2568d2be894590900c461738ce35d7ec6f448558",
          "md5": "652b419bbfc5db29899d2c1abb8fc63c"
        }
      ]
    }
  ]
}
