{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.39.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tltlxzwu3bci7i7vv4dc65rjne"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.3.aar",
          "url": "core-0.39.3.aar",
          "size": 367765,
          "sha512": "e94a169d24ec3cf3ecbc057224d51667af4016f64159faf77ee205d0e5826b168e57a6a5c40f3176117d666fe43085befa8a5117ffeddc23ea3a1c5dab072cd7",
          "sha256": "4bc83c7c34e1f4006f4bc173215b245d37228f88c0a68c7dd7c0257741c92556",
          "sha1": "fa2f9559d8c93465ef6c3f2d7731550cbce20646",
          "md5": "dc272d9aec37710d3d961fff52665844"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.39.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.39.3.aar",
          "url": "core-0.39.3.aar",
          "size": 367765,
          "sha512": "e94a169d24ec3cf3ecbc057224d51667af4016f64159faf77ee205d0e5826b168e57a6a5c40f3176117d666fe43085befa8a5117ffeddc23ea3a1c5dab072cd7",
          "sha256": "4bc83c7c34e1f4006f4bc173215b245d37228f88c0a68c7dd7c0257741c92556",
          "sha1": "fa2f9559d8c93465ef6c3f2d7731550cbce20646",
          "md5": "dc272d9aec37710d3d961fff52665844"
        }
      ]
    }
  ]
}
