{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.27.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "e7j45vwqpfdjdculia3jsmcsmm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.27.1.aar",
          "url": "core-0.27.1.aar",
          "size": 273356,
          "sha512": "df3124b21d459864be3f05fb29fa5b4c05260c32476a98b12fd48416344d1bd265d65bd27df854b0dcd9fec1f0a4a1a8882973d0f327f6d917382c6aab7f11a9",
          "sha256": "1ae467323740ee07424115ab7d9340ee204316fc486caabd22bf32bccc8290a5",
          "sha1": "d621a9463bb6101c7f5574bc003678fba3083fd1",
          "md5": "23f566bd24ee7ea62b3dfb05249c9742"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.27.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.27.1.aar",
          "url": "core-0.27.1.aar",
          "size": 273356,
          "sha512": "df3124b21d459864be3f05fb29fa5b4c05260c32476a98b12fd48416344d1bd265d65bd27df854b0dcd9fec1f0a4a1a8882973d0f327f6d917382c6aab7f11a9",
          "sha256": "1ae467323740ee07424115ab7d9340ee204316fc486caabd22bf32bccc8290a5",
          "sha1": "d621a9463bb6101c7f5574bc003678fba3083fd1",
          "md5": "23f566bd24ee7ea62b3dfb05249c9742"
        }
      ]
    }
  ]
}
