{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "ui-integration",
    "version": "0.38.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bqdx6kdjbzbfflbiktn3pzs4vq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.38.0.aar",
          "url": "ui-integration-0.38.0.aar",
          "size": 99980,
          "sha512": "25798de4f209e594809462d82eadeac485b79378748aeb3e148148262e38a29d51ac632bc62fe352b42db0012bdabf4c920a85986190c33dc05fae64b211628b",
          "sha256": "0779714aee6150164605ede53a0d53312acea215daf52624f421e5fb09b164a7",
          "sha1": "4c12817ccafce56bb1aaa6c006672ce5d9a560ce",
          "md5": "88569c481db091d8caa35748960b85b6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.38.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.38.0"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.38.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-integration-0.38.0.aar",
          "url": "ui-integration-0.38.0.aar",
          "size": 99980,
          "sha512": "25798de4f209e594809462d82eadeac485b79378748aeb3e148148262e38a29d51ac632bc62fe352b42db0012bdabf4c920a85986190c33dc05fae64b211628b",
          "sha256": "0779714aee6150164605ede53a0d53312acea215daf52624f421e5fb09b164a7",
          "sha1": "4c12817ccafce56bb1aaa6c006672ce5d9a560ce",
          "md5": "88569c481db091d8caa35748960b85b6"
        }
      ]
    }
  ]
}
