{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.80.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.16.aar",
          "url": "mlkit-scanner-engine-0.80.16.aar",
          "size": 63984,
          "sha512": "74adae8ebdf9d0d5c90e06d9160abbac10062f70f3b5313727d90998cc508b3789d78dac26ab420c64120475d0d86adde433d090038bc21644cdae8bcd3986ab",
          "sha256": "efc59ca7f15fc1e341c3ff6997c6f527d0141bec09e74771ddfaed47e904f57f",
          "sha1": "51a02c2afbd0b4af0c8415f7dada69424c31d603",
          "md5": "136e081898a450669dd64a9dd22ad386"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.80.16"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.80.16"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.16"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.16.aar",
          "url": "mlkit-scanner-engine-0.80.16.aar",
          "size": 63984,
          "sha512": "74adae8ebdf9d0d5c90e06d9160abbac10062f70f3b5313727d90998cc508b3789d78dac26ab420c64120475d0d86adde433d090038bc21644cdae8bcd3986ab",
          "sha256": "efc59ca7f15fc1e341c3ff6997c6f527d0141bec09e74771ddfaed47e904f57f",
          "sha1": "51a02c2afbd0b4af0c8415f7dada69424c31d603",
          "md5": "136e081898a450669dd64a9dd22ad386"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.16-sources.jar",
          "url": "mlkit-scanner-engine-0.80.16-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
