{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.72.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.3.aar",
          "url": "core-0.72.3.aar",
          "size": 595736,
          "sha512": "9ae7c2ed7109435e47d279dc7f7039f0a2710677dfc72c35d8fe30ca759d0a02e5aecc5f55e54509cd11ae4dee6bd17e51b552d7eb9a42b86fee376eb4654231",
          "sha256": "602c33c6e40d3e97b76f7306e54811262a6355adf3a447a2fae97a222e02ffb4",
          "sha1": "0979f14bbe9526d6d1eae0fc6f4695256514822c",
          "md5": "c862cef2bea6d4fb390de20c4819b17a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.72.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.72.3.aar",
          "url": "core-0.72.3.aar",
          "size": 595736,
          "sha512": "9ae7c2ed7109435e47d279dc7f7039f0a2710677dfc72c35d8fe30ca759d0a02e5aecc5f55e54509cd11ae4dee6bd17e51b552d7eb9a42b86fee376eb4654231",
          "sha256": "602c33c6e40d3e97b76f7306e54811262a6355adf3a447a2fae97a222e02ffb4",
          "sha1": "0979f14bbe9526d6d1eae0fc6f4695256514822c",
          "md5": "c862cef2bea6d4fb390de20c4819b17a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.72.3-sources.jar",
          "url": "core-0.72.3-sources.jar",
          "size": 330257,
          "sha512": "8e7ed96d069e2d021b2648b8e474bb281dfd9d22947ffc8170de4b7c59564cd7626faf1765c619d1dffa50efb8a14d336a39500065617e88b0a7dd9ecc5b9dc4",
          "sha256": "ba3799905b58a1ec0107a48d39bf75572ea44249d3418254937928d38a247d5e",
          "sha1": "cf602abd55ba4ad4478b261b62bdb155dd3a91f6",
          "md5": "46540579e8d75c07aca44aeffe271a41"
        }
      ]
    }
  ]
}
