{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.71.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.2.aar",
          "url": "core-0.71.2.aar",
          "size": 589890,
          "sha512": "ba71d563eb8518062aa99f8157a7408ac21b09eaf7668e5469a54685443129b9f7b63d431a2d294c31d199404c483db7cb77f8ad9693a4b0d01623dbe765f555",
          "sha256": "04096aa20f1b62d7c2399edb56a2f5b96ed8a0c5c2b3c1e3e8433567ec120816",
          "sha1": "470b38bc75348565a437db3baf849161e72e076c",
          "md5": "2109d82b6abebe735924a9ca20955780"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.71.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.5-RELEASE"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "eu.rekisoft.android.util",
          "module": "LazyWorker",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.71.2.aar",
          "url": "core-0.71.2.aar",
          "size": 589890,
          "sha512": "ba71d563eb8518062aa99f8157a7408ac21b09eaf7668e5469a54685443129b9f7b63d431a2d294c31d199404c483db7cb77f8ad9693a4b0d01623dbe765f555",
          "sha256": "04096aa20f1b62d7c2399edb56a2f5b96ed8a0c5c2b3c1e3e8433567ec120816",
          "sha1": "470b38bc75348565a437db3baf849161e72e076c",
          "md5": "2109d82b6abebe735924a9ca20955780"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.71.2-sources.jar",
          "url": "core-0.71.2-sources.jar",
          "size": 326559,
          "sha512": "6069529ac32e8f09b8bfd1ceabf0b7407c118a19603bc35279aabe47a9a657856ac9e2c1081cfee9af38affdcbb5933e665ea536bf1594ce0209304d900fe77c",
          "sha256": "cf67a1c4ecfe0703f275f381fcb80bed42d8681579c413f6a39d8f9a56804b61",
          "sha1": "7c81836556ad1f53b92bd7bd5329dc118a22a47f",
          "md5": "cd26c132460635d75bb690cbdd2f295e"
        }
      ]
    }
  ]
}
