{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.32.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4pup4szq2neoldqbonx2hyf2ly"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.6.aar",
          "url": "core-0.32.6.aar",
          "size": 326041,
          "sha512": "45e52f540da757e70f2d9a968596800456213f483f92a0b5931c6671ae00fd1decccf83ce4250983baaf348e1fc21a6106c7c1c515506071d9804117e9571efc",
          "sha256": "11688b7a48aa3e13af0d8bafa999cc38fc161075edabcdedc8c9c7d3853471c7",
          "sha1": "820e322f97045202dfe8a4d32db505b15a8721d0",
          "md5": "21a3f317ecbdd702f0aa6b7a8ec1aeb3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.32.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.32.6.aar",
          "url": "core-0.32.6.aar",
          "size": 326041,
          "sha512": "45e52f540da757e70f2d9a968596800456213f483f92a0b5931c6671ae00fd1decccf83ce4250983baaf348e1fc21a6106c7c1c515506071d9804117e9571efc",
          "sha256": "11688b7a48aa3e13af0d8bafa999cc38fc161075edabcdedc8c9c7d3853471c7",
          "sha1": "820e322f97045202dfe8a4d32db505b15a8721d0",
          "md5": "21a3f317ecbdd702f0aa6b7a8ec1aeb3"
        }
      ]
    }
  ]
}
