{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "mlkit-scanner-engine",
    "version": "0.80.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.13.aar",
          "url": "mlkit-scanner-engine-0.80.13.aar",
          "size": 63997,
          "sha512": "8827906592f5eb8284dfbc9da452dc4271d5a6ad9311dea3c95ce5cb755fbcfdb2aaa419f26226d06f623a21fcf6fc3e11d2a109ce187faa412e8327f509881e",
          "sha256": "03f82b23a7e6594b7e983749dc5520e02a33bb831755953f59dc2957cd3fd5dc",
          "sha1": "1d2b06dd6e451c68d1251f8fb046e0f7114d48d0",
          "md5": "72a7c3120c37360df63145487f853149"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "core",
          "version": {
            "requires": "0.80.13"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "ui",
          "version": {
            "requires": "0.80.13"
          }
        },
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.80.13"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.13.aar",
          "url": "mlkit-scanner-engine-0.80.13.aar",
          "size": 63997,
          "sha512": "8827906592f5eb8284dfbc9da452dc4271d5a6ad9311dea3c95ce5cb755fbcfdb2aaa419f26226d06f623a21fcf6fc3e11d2a109ce187faa412e8327f509881e",
          "sha256": "03f82b23a7e6594b7e983749dc5520e02a33bb831755953f59dc2957cd3fd5dc",
          "sha1": "1d2b06dd6e451c68d1251f8fb046e0f7114d48d0",
          "md5": "72a7c3120c37360df63145487f853149"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mlkit-scanner-engine-0.80.13-sources.jar",
          "url": "mlkit-scanner-engine-0.80.13-sources.jar",
          "size": 5243,
          "sha512": "2f8a3bb3b9df2e98cb5e5514c868a13ce555751f34a932f09ba31aa5efbdec7900e0ac96729ba547cb678a275840ccc87ceffa9f1cc2fa0957e62d846539deed",
          "sha256": "493fdeed36f2ede5084b4622837a59ddbcb010d1cce3d630a47cec06259bfe1f",
          "sha1": "e639ac3512a5ad63d0ee1cb0be49e735a78e92dc",
          "md5": "d5f3c0506f9d580f38cae010914ee424"
        }
      ]
    }
  ]
}
