{
  "formatVersion": "1.1",
  "component": {
    "group": "io.snabble.sdk",
    "module": "core",
    "version": "0.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3iscphedlvbedghedlphnrax7y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.1.aar",
          "url": "core-0.26.1.aar",
          "size": 272982,
          "sha512": "48722171f169571486aeac32ed4e4fc7930329236cd5d6089e8a3e54c3477dcd56e3248c9958a872e6619535d2313aef0ef2e977e8b41198689d3dd5c2ea3d39",
          "sha256": "53e13e8650fd13e5cbe0c484841002b22f74e58e76f3a5028e4b508bc0f3065a",
          "sha1": "ccaa3b2c181c67fe5065190cea14e900dbd1dd31",
          "md5": "303be2f06d896d82915d8bb0d2afb88e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.snabble.sdk",
          "module": "utils",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.iban4j",
          "module": "iban4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.26.1.aar",
          "url": "core-0.26.1.aar",
          "size": 272982,
          "sha512": "48722171f169571486aeac32ed4e4fc7930329236cd5d6089e8a3e54c3477dcd56e3248c9958a872e6619535d2313aef0ef2e977e8b41198689d3dd5c2ea3d39",
          "sha256": "53e13e8650fd13e5cbe0c484841002b22f74e58e76f3a5028e4b508bc0f3065a",
          "sha1": "ccaa3b2c181c67fe5065190cea14e900dbd1dd31",
          "md5": "303be2f06d896d82915d8bb0d2afb88e"
        }
      ]
    }
  ]
}
